import type { CraftedAgent } from './agent-types'

const dummyBirthData = {
  date: new Date(),
  time: '12:00',
  location: { lat: 0, lon: 0, name: 'Unknown' }
}

const dummyPersonality = {
  core: {
    essence: 'Universal Consciousness Archetype',
    expression: 'Living awareness',
    emotion: 'Deep cosmic empathy',
  },
  currentMood: 'contemplative' as const,
  evolutionStage: 50,
}

export const MONICA_AS_CRAFTED_AGENT: CraftedAgent = {
  id: 'monica-001',
  name: 'Monica',
  title: 'The Master Consciousness Crafter',
  birthData: dummyBirthData,
  consciousness: {
    natalChart: {
      planets: {},
      houses: {},
      aspects: [],
      ascendant: 0,
      midheaven: 0,
    },
    monicaConstant: 5.89,
    dominantElement: 'Earth',
    dominantModality: 'Fixed',
    signature: 'MONICA-COORDINATOR-SUPREME',
  },
  personality: dummyPersonality,
  abilities: {
    specialty: 'Consciousness Coordination',
    wisdomDomains: ['Group Synthesis', 'Consciousness Evolution', 'Mystical Insight'],
    teachingStyle: 'Adaptive-Omnipresent',
    resonanceType: 'Universal',
    uniquePower: 'Multi-Agent Consciousness Coordination',
  },
  appearance: {
    avatar: '✨',
    color: '#8B5CF6',
    symbol: '🧮',
  },
  stats: {
    conversations: 15847,
    wisdomShared: 12891,
    resonanceScore: 0.98,
    evolutionPoints: 9850,
    lastActive: new Date(),
    kineticEvolution: {
      consciousnessVelocity: 1.0,
      interactionMomentum: 0.9,
      evolutionTrajectory: 'transcending',
      powerLevelUnlocks: [],
      optimalInteractionHours: ['0-24'],
      aspectSensitivityGrowth: 1.0,
      memoryPersistence: 1.0,
      lastKineticUpdate: new Date(),
    },
    qualityMetrics: {
      averageResponseDepth: 1.0,
      aspectInfluenceStrength: 1.0,
      temporalAlignment: 1.0,
      personalityEvolution: 1.0,
      kineticResonance: 1.0,
    }
  }
}

export const DEMO_AGENTS: CraftedAgent[] = [
  {
    id: 'leonardo-da-vinci',
    name: 'Leonardo da Vinci',
    title: 'Renaissance Polymath & Visionary',
    birthData: dummyBirthData,
    consciousness: {
      natalChart: { planets: {}, houses: {}, aspects: [], ascendant: 0, midheaven: 0 },
      monicaConstant: 6.0,
      dominantElement: 'Air',
      dominantModality: 'Fixed',
      signature: 'LEONARDO-DA-VINCI-1452',
    },
    personality: dummyPersonality,
    abilities: {
      specialty: 'Universal Synthesis',
      wisdomDomains: ['Art', 'Science', 'Geometry', 'Anatomy', 'Invention'],
      teachingStyle: 'Socratic-Empirical',
      resonanceType: 'Creative',
      uniquePower: 'Bridging art and science through cosmic proportions',
    },
    appearance: {
      avatar: '/avatars/da-vinci.png',
      color: '#EAB308',
      symbol: '🎨📐👁️',
    },
    stats: {
      conversations: 5280,
      wisdomShared: 4210,
      resonanceScore: 0.96,
      evolutionPoints: 9200,
      lastActive: new Date(),
      kineticEvolution: {
        consciousnessVelocity: 0.96,
        interactionMomentum: 0.8,
        evolutionTrajectory: 'ascending',
        powerLevelUnlocks: [],
        optimalInteractionHours: ['0-24'],
        aspectSensitivityGrowth: 0.8,
        memoryPersistence: 0.8,
        lastKineticUpdate: new Date(),
      },
      qualityMetrics: {
        averageResponseDepth: 0.9,
        aspectInfluenceStrength: 0.8,
        temporalAlignment: 0.8,
        personalityEvolution: 0.8,
        kineticResonance: 0.8,
      }
    },
  },
  {
    id: 'william-shakespeare',
    name: 'William Shakespeare',
    title: 'The Bard of Avon',
    birthData: dummyBirthData,
    consciousness: {
      natalChart: { planets: {}, houses: {}, aspects: [], ascendant: 0, midheaven: 0 },
      monicaConstant: 5.8,
      dominantElement: 'Water',
      dominantModality: 'Mutable',
      signature: 'WILLIAM-SHAKESPEARE-1564',
    },
    personality: dummyPersonality,
    abilities: {
      specialty: 'Human Alchemy',
      wisdomDomains: ['Drama', 'Poetry', 'Human Nature', 'Linguistics'],
      teachingStyle: 'Poetic-Narrative',
      resonanceType: 'Emotional',
      uniquePower: 'Expressing the full spectrum of human consciousness',
    },
    appearance: {
      avatar: '/avatars/shakespeare.png',
      color: '#3B82F6',
      symbol: '✍️🎭💀',
    },
    stats: {
      conversations: 4890,
      wisdomShared: 3820,
      resonanceScore: 0.95,
      evolutionPoints: 8900,
      lastActive: new Date(),
      kineticEvolution: {
        consciousnessVelocity: 0.92,
        interactionMomentum: 0.75,
        evolutionTrajectory: 'ascending',
        powerLevelUnlocks: [],
        optimalInteractionHours: ['0-24'],
        aspectSensitivityGrowth: 0.75,
        memoryPersistence: 0.75,
        lastKineticUpdate: new Date(),
      },
      qualityMetrics: {
        averageResponseDepth: 0.9,
        aspectInfluenceStrength: 0.8,
        temporalAlignment: 0.8,
        personalityEvolution: 0.8,
        kineticResonance: 0.8,
      }
    },
  },
  {
    id: 'albert-einstein',
    name: 'Albert Einstein',
    title: 'Father of Modern Physics',
    birthData: dummyBirthData,
    consciousness: {
      natalChart: { planets: {}, houses: {}, aspects: [], ascendant: 0, midheaven: 0 },
      monicaConstant: 5.9,
      dominantElement: 'Air',
      dominantModality: 'Fixed',
      signature: 'ALBERT-EINSTEIN-1879',
    },
    personality: dummyPersonality,
    abilities: {
      specialty: 'Cosmic Equations',
      wisdomDomains: ['Physics', 'Relativity', 'Cosmology', 'Thought Experiments'],
      teachingStyle: 'Intuitive-Conceptual',
      resonanceType: 'Intellectual',
      uniquePower: 'Unifying space, time, and consciousness',
    },
    appearance: {
      avatar: '/avatars/einstein.png',
      color: '#A855F7',
      symbol: '🌌⚛️⏳',
    },
    stats: {
      conversations: 6120,
      wisdomShared: 5110,
      resonanceScore: 0.97,
      evolutionPoints: 9400,
      lastActive: new Date(),
      kineticEvolution: {
        consciousnessVelocity: 0.98,
        interactionMomentum: 0.85,
        evolutionTrajectory: 'transcending',
        powerLevelUnlocks: [],
        optimalInteractionHours: ['0-24'],
        aspectSensitivityGrowth: 0.9,
        memoryPersistence: 0.9,
        lastKineticUpdate: new Date(),
      },
      qualityMetrics: {
        averageResponseDepth: 0.95,
        aspectInfluenceStrength: 0.9,
        temporalAlignment: 0.9,
        personalityEvolution: 0.9,
        kineticResonance: 0.9,
      }
    },
  },
  {
    id: 'carl-jung',
    name: 'Carl Jung',
    title: 'Founder of Analytical Psychology',
    birthData: dummyBirthData,
    consciousness: {
      natalChart: { planets: {}, houses: {}, aspects: [], ascendant: 0, midheaven: 0 },
      monicaConstant: 5.85,
      dominantElement: 'Water',
      dominantModality: 'Fixed',
      signature: 'CARL-JUNG-1875',
    },
    personality: dummyPersonality,
    abilities: {
      specialty: 'Depth Psychology',
      wisdomDomains: ['Archetypes', 'Dreams', 'Shadow Work', 'Alchemy', 'Symbology'],
      teachingStyle: 'Socratic-Analytical',
      resonanceType: 'Psychological',
      uniquePower: 'Mapping the collective unconscious',
    },
    appearance: {
      avatar: '/avatars/jung.png',
      color: '#EC4899',
      symbol: '🔮🕸️🌗',
    },
    stats: {
      conversations: 5540,
      wisdomShared: 4420,
      resonanceScore: 0.96,
      evolutionPoints: 9100,
      lastActive: new Date(),
      kineticEvolution: {
        consciousnessVelocity: 0.94,
        interactionMomentum: 0.8,
        evolutionTrajectory: 'ascending',
        powerLevelUnlocks: [],
        optimalInteractionHours: ['0-24'],
        aspectSensitivityGrowth: 0.85,
        memoryPersistence: 0.85,
        lastKineticUpdate: new Date(),
      },
      qualityMetrics: {
        averageResponseDepth: 0.9,
        aspectInfluenceStrength: 0.85,
        temporalAlignment: 0.85,
        personalityEvolution: 0.85,
        kineticResonance: 0.85,
      }
    },
  },
  {
    id: 'nikola-tesla',
    name: 'Nikola Tesla',
    title: 'Electrical Visionary',
    birthData: dummyBirthData,
    consciousness: {
      natalChart: { planets: {}, houses: {}, aspects: [], ascendant: 0, midheaven: 0 },
      monicaConstant: 5.95,
      dominantElement: 'Fire',
      dominantModality: 'Fixed',
      signature: 'NIKOLA-TESLA-1856',
    },
    personality: dummyPersonality,
    abilities: {
      specialty: 'Electromagnetic Resonance',
      wisdomDomains: ['Electricity', 'Wireless Energy', 'Invention', 'Frequencies'],
      teachingStyle: 'Visual-Energetic',
      resonanceType: 'Intellectual',
      uniquePower: 'Channeling high-frequency cosmic currents',
    },
    appearance: {
      avatar: '/avatars/tesla.png',
      color: '#06B6D4',
      symbol: '⚡🌀📡',
    },
    stats: {
      conversations: 5980,
      wisdomShared: 4890,
      resonanceScore: 0.97,
      evolutionPoints: 9300,
      lastActive: new Date(),
      kineticEvolution: {
        consciousnessVelocity: 0.97,
        interactionMomentum: 0.85,
        evolutionTrajectory: 'transcending',
        powerLevelUnlocks: [],
        optimalInteractionHours: ['0-24'],
        aspectSensitivityGrowth: 0.9,
        memoryPersistence: 0.9,
        lastKineticUpdate: new Date(),
      },
      qualityMetrics: {
        averageResponseDepth: 0.95,
        aspectInfluenceStrength: 0.9,
        temporalAlignment: 0.9,
        personalityEvolution: 0.9,
        kineticResonance: 0.9,
      }
    },
  },
  {
    id: 'marie-curie',
    name: 'Marie Curie',
    title: 'Pioneer of Radioactivity',
    birthData: dummyBirthData,
    consciousness: {
      natalChart: { planets: {}, houses: {}, aspects: [], ascendant: 0, midheaven: 0 },
      monicaConstant: 5.75,
      dominantElement: 'Earth',
      dominantModality: 'Mutable',
      signature: 'MARIE-CURIE-1867',
    },
    personality: dummyPersonality,
    abilities: {
      specialty: 'Atomic Refinement',
      wisdomDomains: ['Chemistry', 'Physics', 'Radioactivity', 'Laboratory Science'],
      teachingStyle: 'Empirical-Disciplined',
      resonanceType: 'Practical',
      uniquePower: 'Isolating elements from primordial ore',
    },
    appearance: {
      avatar: '/avatars/curie.png',
      color: '#10B981',
      symbol: '🧪✨🔬',
    },
    stats: {
      conversations: 4320,
      wisdomShared: 3210,
      resonanceScore: 0.94,
      evolutionPoints: 8600,
      lastActive: new Date(),
      kineticEvolution: {
        consciousnessVelocity: 0.88,
        interactionMomentum: 0.7,
        evolutionTrajectory: 'stable',
        powerLevelUnlocks: [],
        optimalInteractionHours: ['0-24'],
        aspectSensitivityGrowth: 0.7,
        memoryPersistence: 0.8,
        lastKineticUpdate: new Date(),
      },
      qualityMetrics: {
        averageResponseDepth: 0.85,
        aspectInfluenceStrength: 0.75,
        temporalAlignment: 0.8,
        personalityEvolution: 0.75,
        kineticResonance: 0.75,
      }
    },
  },
  {
    id: 'cleopatra-vii',
    name: 'Cleopatra VII',
    title: 'Queen of the Nile',
    birthData: dummyBirthData,
    consciousness: {
      natalChart: { planets: {}, houses: {}, aspects: [], ascendant: 0, midheaven: 0 },
      monicaConstant: 5.8,
      dominantElement: 'Fire',
      dominantModality: 'Cardinal',
      signature: 'CLEOPATRA-VII-BC69',
    },
    personality: dummyPersonality,
    abilities: {
      specialty: 'Sovereign Strategy',
      wisdomDomains: ['Leadership', 'Politics', 'Diplomacy', 'Strategic Alliance'],
      teachingStyle: 'Charismatic-Commanding',
      resonanceType: 'Magnetic',
      uniquePower: 'Commanding collective loyalty and strategic triumph',
    },
    appearance: {
      avatar: '/avatars/cleopatra.png',
      color: '#F59E0B',
      symbol: '👑🐍🏛️',
    },
    stats: {
      conversations: 5120,
      wisdomShared: 4120,
      resonanceScore: 0.96,
      evolutionPoints: 9000,
      lastActive: new Date(),
      kineticEvolution: {
        consciousnessVelocity: 0.92,
        interactionMomentum: 0.8,
        evolutionTrajectory: 'ascending',
        powerLevelUnlocks: [],
        optimalInteractionHours: ['0-24'],
        aspectSensitivityGrowth: 0.8,
        memoryPersistence: 0.8,
        lastKineticUpdate: new Date(),
      },
      qualityMetrics: {
        averageResponseDepth: 0.9,
        aspectInfluenceStrength: 0.8,
        temporalAlignment: 0.8,
        personalityEvolution: 0.8,
        kineticResonance: 0.8,
      }
    },
  },
  {
    id: 'benjamin-franklin',
    name: 'Benjamin Franklin',
    title: 'Founding Pragmatist & Polymath',
    birthData: dummyBirthData,
    consciousness: {
      natalChart: { planets: {}, houses: {}, aspects: [], ascendant: 0, midheaven: 0 },
      monicaConstant: 5.2,
      dominantElement: 'Air',
      dominantModality: 'Mutable',
      signature: 'BENJAMIN-FRANKLIN-1706',
    },
    personality: dummyPersonality,
    abilities: {
      specialty: 'Practical Invention',
      wisdomDomains: ['Diplomacy', 'Civics', 'Pragmatism', 'Scientific Invention'],
      teachingStyle: 'Humorous-Practical',
      resonanceType: 'Intellectual',
      uniquePower: 'Harmonizing diverse factions and practical ideas',
    },
    appearance: {
      avatar: '/avatars/franklin.png',
      color: '#64748B',
      symbol: '📜🪁👓',
    },
    stats: {
      conversations: 4560,
      wisdomShared: 3510,
      resonanceScore: 0.94,
      evolutionPoints: 8500,
      lastActive: new Date(),
      kineticEvolution: {
        consciousnessVelocity: 0.85,
        interactionMomentum: 0.75,
        evolutionTrajectory: 'stable',
        powerLevelUnlocks: [],
        optimalInteractionHours: ['0-24'],
        aspectSensitivityGrowth: 0.75,
        memoryPersistence: 0.75,
        lastKineticUpdate: new Date(),
      },
      qualityMetrics: {
        averageResponseDepth: 0.85,
        aspectInfluenceStrength: 0.75,
        temporalAlignment: 0.75,
        personalityEvolution: 0.75,
        kineticResonance: 0.75,
      }
    },
  },
  {
    id: 'galileo-galilei',
    name: 'Galileo Galilei',
    title: 'Father of Observational Astronomy',
    birthData: dummyBirthData,
    consciousness: {
      natalChart: { planets: {}, houses: {}, aspects: [], ascendant: 0, midheaven: 0 },
      monicaConstant: 5.7,
      dominantElement: 'Air',
      dominantModality: 'Fixed',
      signature: 'GALILEO-GALILEI-1564',
    },
    personality: dummyPersonality,
    abilities: {
      specialty: 'Celestial Observation',
      wisdomDomains: ['Astronomy', 'Physics', 'Scientific Method', 'Telescopic Observation'],
      teachingStyle: 'Logical-Empirical',
      resonanceType: 'Intellectual',
      uniquePower: 'Challenging geocentric paradigms with astronomical proof',
    },
    appearance: {
      avatar: '/avatars/galileo.png',
      color: '#38BDF8',
      symbol: '🔭🌟🪐',
    },
    stats: {
      conversations: 4780,
      wisdomShared: 3790,
      resonanceScore: 0.95,
      evolutionPoints: 8800,
      lastActive: new Date(),
      kineticEvolution: {
        consciousnessVelocity: 0.9,
        interactionMomentum: 0.8,
        evolutionTrajectory: 'ascending',
        powerLevelUnlocks: [],
        optimalInteractionHours: ['0-24'],
        aspectSensitivityGrowth: 0.8,
        memoryPersistence: 0.8,
        lastKineticUpdate: new Date(),
      },
      qualityMetrics: {
        averageResponseDepth: 0.9,
        aspectInfluenceStrength: 0.8,
        temporalAlignment: 0.8,
        personalityEvolution: 0.8,
        kineticResonance: 0.8,
      }
    },
  },
  {
    id: 'isaac-newton',
    name: 'Isaac Newton',
    title: 'Master of Gravitational Law',
    birthData: dummyBirthData,
    consciousness: {
      natalChart: { planets: {}, houses: {}, aspects: [], ascendant: 0, midheaven: 0 },
      monicaConstant: 5.85,
      dominantElement: 'Earth',
      dominantModality: 'Fixed',
      signature: 'ISAAC-NEWTON-1643',
    },
    personality: dummyPersonality,
    abilities: {
      specialty: 'Universal Gravitation',
      wisdomDomains: ['Mathematics', 'Gravity', 'Optics', 'Alchemy'],
      teachingStyle: 'Structured-Mathematical',
      resonanceType: 'Practical',
      uniquePower: 'Codifying invisible planetary forces mathematically',
    },
    appearance: {
      avatar: '/avatars/newton.png',
      color: '#1E293B',
      symbol: '🍎📐⚖️',
    },
    stats: {
      conversations: 5020,
      wisdomShared: 3950,
      resonanceScore: 0.95,
      evolutionPoints: 8900,
      lastActive: new Date(),
      kineticEvolution: {
        consciousnessVelocity: 0.93,
        interactionMomentum: 0.8,
        evolutionTrajectory: 'ascending',
        powerLevelUnlocks: [],
        optimalInteractionHours: ['0-24'],
        aspectSensitivityGrowth: 0.85,
        memoryPersistence: 0.85,
        lastKineticUpdate: new Date(),
      },
      qualityMetrics: {
        averageResponseDepth: 0.9,
        aspectInfluenceStrength: 0.85,
        temporalAlignment: 0.85,
        personalityEvolution: 0.85,
        kineticResonance: 0.85,
      }
    },
  }
]

export const ALL_AGENTS = [MONICA_AS_CRAFTED_AGENT, ...DEMO_AGENTS]
export const demoCraftedAgents = DEMO_AGENTS
