nodeLinker: node-modules
enableGlobalCache: false

# Network resilience settings for Vercel builds
httpTimeout: 300000
httpRetry: 3
enableNetwork: true

# Registry settings
npmRegistryServer: "https://registry.yarnpkg.com"
