# Yarn configuration for WhatToEatNext project
# Optimized for CI/CD and development workflows

# Enable Yarn Berry features
nodeLinker: node-modules

# Enable PnP for better performance (optional)
# nodeLinker: pnp

# Network settings for CI/CD
networkSettings:
  httpTimeout: 300000
  httpRetry: 3

# Cache settings
enableGlobalCache: true
compressionLevel: mixed

# Security settings
enableHardenedMode: true
enableImmutableInstalls: true

# Logging settings
logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard

# Package extensions for compatibility
packageExtensions:
  "next@*":
    peerDependencies:
      "react": "*"
      "react-dom": "*"
  "@types/*@*":
    peerDependencies:
      "typescript": "*"

# Plugins
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

# Workspace settings
workspaces:
  - "apps/*"
  - "packages/*"
  - "scripts/*"

# Publish settings
publishConfig:
  access: public
  registry: "https://registry.npmjs.org/"

# Install settings
installConfig:
  hoistingLimits: workspaces
  enableScripts: true
  enableGlobalCache: true 