import { Project, SyntaxKind } from 'ts-morph';

const project = new Project();
project.addSourceFilesAtPaths('src/data/cuisines/**/*.ts');

const additions = {
  "french.ts": [
    { name: "Authentic Beef Bourguignon", description: "The definitive French stew. Beef is slow-braised in a full-bodied Burgundy wine, transforming tough fibers into melting tenderness, enriched with pearl onions, mushrooms, and lardons.", details: { cuisine: "French (Burgundy)", prepTimeMinutes: 30, cookTimeMinutes: 180, baseServingSize: 6, spiceLevel: "None", season: ["winter"] }, ingredients: [{ amount: 3, unit: "lbs", name: "Beef chuck", notes: "Cut into large cubes." }, { amount: 1, unit: "bottle", name: "Red Burgundy wine", notes: "Pinot Noir." }], instructions: ["Step 1: Fry lardons until crisp; reserve fat.", "Step 2: Sear beef cubes in lardon fat.", "Step 3: Sauté aromatics; add flour to create a roux.", "Step 4: Pour in wine and stock; return beef.", "Step 5: Simmer for 3 hours; add mushrooms and onions at the end."], classifications: { mealType: ["dinner"], cookingMethods: ["braising"] }, elementalProperties: { Fire: 0.15, Water: 0.35, Earth: 0.45, Air: 0.05 }, astrologicalAffinities: { planets: ["Saturn"], signs: ["capricorn"], lunarPhases: ["Waning Gibbous"] }, nutritionPerServing: { calories: 620, proteinG: 48, carbsG: 15, fatG: 38, fiberG: 3, sodiumMg: 850, sugarG: 4, vitamins: ["Vitamin B12"], minerals: ["Iron"] }, substitutions: [] },
    { name: "Authentic Bouillabaisse", description: "The soul of Marseille. A complex fisherman's stew utilizing at least four types of Mediterranean fish, flavored with saffron, fennel, and orange zest, served with 'rouille'—a fierce chili-garlic-saffron emulsion.", details: { cuisine: "French (Provence)", prepTimeMinutes: 45, cookTimeMinutes: 45, baseServingSize: 4, spiceLevel: "Medium", season: ["summer"] }, ingredients: [{ amount: 2, unit: "lbs", name: "Mixed white fish", notes: "Rascasse, sea robin, etc." }, { amount: 1, unit: "pinch", name: "Saffron", notes: "High quality." }], instructions: ["Step 1: Sauté leeks, onions, and fennel.", "Step 2: Add tomatoes, aromatics, and saffron.", "Step 3: Boil fish heads/bones to create base stock.", "Step 4: Poach large fish pieces in the stock.", "Step 5: Serve broth over bread; fish on the side."], classifications: { mealType: ["dinner"], cookingMethods: ["simmering", "poaching"] }, elementalProperties: { Fire: 0.20, Water: 0.60, Earth: 0.10, Air: 0.10 }, astrologicalAffinities: { planets: ["Neptune"], signs: ["pisces"], lunarPhases: ["Full Moon"] }, nutritionPerServing: { calories: 450, proteinG: 52, carbsG: 18, fatG: 14, fiberG: 4, sodiumMg: 1200, sugarG: 6, vitamins: ["Vitamin B12"], minerals: ["Selenium"] }, substitutions: [] },
    { name: "Authentic Quiche Lorraine", description: "A structural triumph of fat and air. A shortcrust pastry shell holds a rich, aerated custard of heavy cream and eggs, punctuated only by smoky bacon (lardons), strictly omitting cheese in its original form.", details: { cuisine: "French (Lorraine)", prepTimeMinutes: 30, cookTimeMinutes: 40, baseServingSize: 6, spiceLevel: "None", season: ["all"] }, ingredients: [{ amount: 1, unit: "shell", name: "Pâte Brisée", notes: "Shortcrust pastry." }, { amount: 1, unit: "cup", name: "Crème Fraîche", notes: "Or heavy cream." }], instructions: ["Step 1: Blind bake the pastry shell.", "Step 2: Fry lardons until crisp.", "Step 3: Whisk eggs and cream; season with nutmeg.", "Step 4: Place lardons in shell; pour in custard.", "Step 5: Bake at 375°F until just set and jiggly."], classifications: { mealType: ["brunch", "lunch"], cookingMethods: ["baking"] }, elementalProperties: { Fire: 0.15, Water: 0.25, Earth: 0.35, Air: 0.25 }, astrologicalAffinities: { planets: ["Venus"], signs: ["taurus"], lunarPhases: ["First Quarter"] }, nutritionPerServing: { calories: 480, proteinG: 18, carbsG: 25, fatG: 38, fiberG: 1, sodiumMg: 750, sugarG: 2, vitamins: ["Vitamin A"], minerals: ["Calcium"] }, substitutions: [] },
    { name: "Authentic Ratatouille (Confit Byaldi)", description: "The refined, structural version of the Provencal stew. Paper-thin rounds of summer vegetables are layered in an infinite spiral over a 'piperade' base, slow-roasted until their flavors unify into a sweet, concentrated essence.", details: { cuisine: "French (Provence)", prepTimeMinutes: 45, cookTimeMinutes: 90, baseServingSize: 4, spiceLevel: "None", season: ["summer"] }, ingredients: [{ amount: 2, unit: "whole", name: "Zucchini/Eggplant", notes: "Sliced into 1mm rounds." }, { amount: 1, unit: "cup", name: "Piperade", notes: "Roasted pepper and tomato sauce." }], instructions: ["Step 1: Create a thick piperade base in a round dish.", "Step 2: Slice vegetables with a mandoline for precision.", "Step 3: Layer vegetables in an overlapping spiral.", "Step 4: Top with parchment paper to steam-roast.", "Step 5: Bake at 300°F for 90 minutes."], classifications: { mealType: ["dinner", "side", "vegan"], cookingMethods: ["roasting"] }, elementalProperties: { Fire: 0.10, Water: 0.40, Earth: 0.40, Air: 0.10 }, astrologicalAffinities: { planets: ["Sun"], signs: ["leo"], lunarPhases: ["Full Moon"] }, nutritionPerServing: { calories: 220, proteinG: 6, carbsG: 28, fatG: 8, fiberG: 12, sodiumMg: 450, sugarG: 14, vitamins: ["Vitamin C", "Vitamin A"], minerals: ["Potassium"] }, substitutions: [] },
    { name: "Authentic Soufflé au Chocolat", description: "The most fragile structure in French pastry. A rich chocolate base is lightened with an intense volume of whipped egg whites, relying on the physical expansion of trapped air to rise high above the ramekin.", details: { cuisine: "French", prepTimeMinutes: 20, cookTimeMinutes: 15, baseServingSize: 2, spiceLevel: "None", season: ["all"] }, ingredients: [{ amount: 100, unit: "g", name: "Dark chocolate", notes: "70% cocoa." }, { amount: 3, unit: "large", name: "Egg whites", notes: "Whipped to stiff peaks." }], instructions: ["Step 1: Melt chocolate with butter; stir in yolks.", "Step 2: Whip egg whites with sugar until glossy.", "Step 3: Fold whites into chocolate matrix in thirds.", "Step 4: Butter and sugar ramekins; pour in batter.", "Step 5: Bake at 400°F; do not open the door."], classifications: { mealType: ["dessert"], cookingMethods: ["baking", "whipping"] }, elementalProperties: { Fire: 0.15, Water: 0.10, Earth: 0.25, Air: 0.50 }, astrologicalAffinities: { planets: ["Mercury"], signs: ["gemini"], lunarPhases: ["First Quarter"] }, nutritionPerServing: { calories: 350, proteinG: 12, carbsG: 32, fatG: 22, fiberG: 4, sodiumMg: 110, sugarG: 24, vitamins: ["Magnesium"], minerals: ["Iron"] }, substitutions: [] }
  ],
  "greek.ts": [
    { name: "Authentic Moussaka", description: "The architectural giant of Greek cuisine. Layers of fried eggplant and spiced lamb ragu are topped with a massive, 2-inch thick layer of stiff Greek béchamel, baked until the surface forms a dark, scorched crust.", details: { cuisine: "Greek", prepTimeMinutes: 60, cookTimeMinutes: 60, baseServingSize: 8, spiceLevel: "Mild", season: ["autumn", "winter"] }, ingredients: [{ amount: 2, unit: "large", name: "Eggplants", notes: "Sliced and fried." }, { amount: 1, unit: "lb", name: "Ground lamb", notes: "Spiced with cinnamon." }], instructions: ["Step 1: Fry eggplant slices until golden.", "Step 2: Prepare a thick lamb ragu with tomato and wine.", "Step 3: Make a stiff béchamel enriched with egg yolks.", "Step 4: Layer eggplant, then meat, then béchamel.", "Step 5: Bake at 375°F until the top is deeply browned."], classifications: { mealType: ["dinner"], cookingMethods: ["layering", "baking"] }, elementalProperties: { Fire: 0.20, Water: 0.20, Earth: 0.50, Air: 0.10 }, astrologicalAffinities: { planets: ["Saturn"], signs: ["capricorn"], lunarPhases: ["Full Moon"] }, nutritionPerServing: { calories: 680, proteinG: 32, carbsG: 45, fatG: 48, fiberG: 8, sodiumMg: 850, sugarG: 10, vitamins: ["Vitamin A", "Vitamin K"], minerals: ["Potassium", "Iron"] }, substitutions: [] },
    { name: "Authentic Spanakopita", description: "A study in paper-thin stratification. Dozens of layers of buttered phyllo pastry encapsulate a moisture-controlled filling of spinach, feta, and dill, baked until the exterior shatters at the touch.", details: { cuisine: "Greek", prepTimeMinutes: 45, cookTimeMinutes: 45, baseServingSize: 8, spiceLevel: "None", season: ["all"] }, ingredients: [{ amount: 1, unit: "lb", name: "Phyllo pastry", notes: "Defrosted." }, { amount: 2, unit: "lbs", name: "Fresh spinach", notes: "Wilted and squeezed completely dry." }], instructions: ["Step 1: Wring spinach until zero water remains.", "Step 2: Mix with feta, eggs, and massive amounts of dill.", "Step 3: Layer 10 sheets of phyllo, brushing each with butter.", "Step 4: Spread filling; top with 10 more buttered sheets.", "Step 5: Score top layers; bake until golden and crisp."], classifications: { mealType: ["lunch", "appetizer"], cookingMethods: ["baking", "layering"] }, elementalProperties: { Fire: 0.25, Water: 0.10, Earth: 0.35, Air: 0.30 }, astrologicalAffinities: { planets: ["Venus"], signs: ["libra"], lunarPhases: ["First Quarter"] }, nutritionPerServing: { calories: 420, proteinG: 14, carbsG: 38, fatG: 28, fiberG: 6, sodiumMg: 950, sugarG: 2, vitamins: ["Vitamin K", "Vitamin A"], minerals: ["Calcium", "Iron"] }, substitutions: [] },
    { name: "Authentic Pastitsio", description: "The Greek pasta bake. Tubular pasta is aligned horizontally, bonded by egg and cheese, topped with a rich meat sauce and a dense, structural layer of béchamel, creating a perfect cross-section when sliced.", details: { cuisine: "Greek", prepTimeMinutes: 45, cookTimeMinutes: 60, baseServingSize: 8, spiceLevel: "None", season: ["winter"] }, ingredients: [{ amount: 500, unit: "g", name: "Pastitsio pasta", notes: "Long tubes (No. 2)." }, { amount: 1, unit: "lb", name: "Ground beef", notes: "Spiced with cloves and cinnamon." }], instructions: ["Step 1: Boil pasta; toss with egg whites and kefalotyri.", "Step 2: Prepare meat sauce with tomato and warm spices.", "Step 3: Align pasta tubes in a deep baking dish.", "Step 4: Layer meat sauce, then a thick béchamel.", "Step 5: Bake at 350°F until the surface is rigid and golden."], classifications: { mealType: ["dinner"], cookingMethods: ["baking", "layering"] }, elementalProperties: { Fire: 0.20, Water: 0.20, Earth: 0.55, Air: 0.05 }, astrologicalAffinities: { planets: ["Jupiter"], signs: ["sagittarius"], lunarPhases: ["Full Moon"] }, nutritionPerServing: { calories: 720, proteinG: 38, carbsG: 75, fatG: 42, fiberG: 4, sodiumMg: 1100, sugarG: 8, vitamins: ["Vitamin B12"], minerals: ["Calcium", "Iron"] }, substitutions: [] },
    { name: "Authentic Gemista", description: "Vegetables filled with the essence of summer. Tomatoes and peppers are hollowed and stuffed with a kinetic mixture of rice, herbs, and the vegetable's own pulp, then slow-roasted until the skins collapse and caramelize.", details: { cuisine: "Greek", prepTimeMinutes: 45, cookTimeMinutes: 90, baseServingSize: 4, spiceLevel: "None", season: ["summer"] }, ingredients: [{ amount: 8, unit: "whole", name: "Tomatoes/Bell Peppers", notes: "Large and firm." }, { amount: 1, unit: "cup", name: "Short-grain rice", notes: "Raw." }], instructions: ["Step 1: Hollow out vegetables; reserve the pulp.", "Step 2: Sauté onion, garlic, and rice; add vegetable pulp.", "Step 3: Fold in massive amounts of parsley and mint.", "Step 4: Stuff vegetables 3/4 full (rice will expand).", "Step 5: Bake with potatoes in a lake of olive oil."], classifications: { mealType: ["dinner", "lunch", "vegan"], cookingMethods: ["roasting", "stuffing"] }, elementalProperties: { Fire: 0.15, Water: 0.35, Earth: 0.45, Air: 0.05 }, astrologicalAffinities: { planets: ["Sun"], signs: ["leo"], lunarPhases: ["Full Moon"] }, nutritionPerServing: { calories: 450, proteinG: 8, carbsG: 62, fatG: 22, fiberG: 8, sodiumMg: 550, sugarG: 12, vitamins: ["Vitamin C", "Vitamin A"], minerals: ["Potassium"] }, substitutions: [] },
    { name: "Authentic Galaktoboureko", description: "The supreme Greek dessert. A thick semolina custard is encased in buttered phyllo, baked until golden, and then drowned in a cold lemon-scented syrup, resulting in a dual texture of shattering pastry and silken cream.", details: { cuisine: "Greek", prepTimeMinutes: 30, cookTimeMinutes: 45, baseServingSize: 12, spiceLevel: "None", season: ["celebration"] }, ingredients: [{ amount: 1, unit: "quart", name: "Whole milk", notes: "For the custard." }, { amount: 1, unit: "cup", name: "Fine semolina", notes: "Thickener." }], instructions: ["Step 1: Cook milk, sugar, and semolina until very thick.", "Step 2: Temper in egg yolks and butter.", "Step 3: Line dish with buttered phyllo; pour in custard.", "Step 4: Cover with more phyllo; bake until dark golden.", "Step 5: Pour cold lemon syrup over the bubbling hot pastry."], classifications: { mealType: ["dessert"], cookingMethods: ["boiling", "baking", "syrup-saturation"] }, elementalProperties: { Fire: 0.15, Water: 0.40, Earth: 0.35, Air: 0.10 }, astrologicalAffinities: { planets: ["Venus"], signs: ["taurus"], lunarPhases: ["Full Moon"] }, nutritionPerServing: { calories: 420, proteinG: 10, carbsG: 65, fatG: 18, fiberG: 1, sodiumMg: 180, sugarG: 45, vitamins: ["Riboflavin"], minerals: ["Calcium"] }, substitutions: [] }
  ]
};

// I will now iterate and add these to the dinner.all arrays
for (const [filename, recipes] of Object.entries(additions)) {
    const sf = project.getSourceFile(filename);
    if (!sf) continue;
    
    const objectLiterals = sf.getDescendantsOfKind(SyntaxKind.ObjectLiteralExpression);
    const dishesObjProp = objectLiterals.find(obj => obj.getProperty('dishes'))?.getProperty('dishes');

    if (dishesObjProp) {
        const dishesObj = dishesObjProp.getInitializer();
        const dinnerObj = dishesObj.getProperty('dinner')?.getInitializer();
        if (dinnerObj) {
            const allArray = dinnerObj.getProperty('all')?.getInitializer();
            if (allArray && allArray.getKind() === SyntaxKind.ArrayLiteralExpression) {
                recipes.forEach(recipe => {
                    allArray.addElement(JSON.stringify(recipe, null, 2));
                });
            }
        }
    }
    sf.saveSync();
}

console.log("Added recipes to French and Greek.");
