import { Project, SyntaxKind } from 'ts-morph';

const project = new Project();
project.addSourceFilesAtPaths('src/data/cuisines/**/*.ts');

const additions = {
  "african.ts": [
    { name: "Authentic Bobotie", description: "The national dish of South Africa. A complex, spiced minced meat bake topped with a savory egg custard and baked until the surface is golden and set, reflecting a fusion of Dutch and Indonesian influences.", details: { cuisine: "South African", prepTimeMinutes: 20, cookTimeMinutes: 45, baseServingSize: 6, spiceLevel: "Medium", season: ["all"] }, ingredients: [{ amount: 1, unit: "lb", name: "Ground beef", notes: "Lean." }, { amount: 2, unit: "slices", name: "White bread", notes: "Soaked in milk." }], instructions: ["Step 1: Sauté meat with aromatics and curry spices.", "Step 2: Fold in soaked bread.", "Step 3: Spread into baking dish.", "Step 4: Pour egg-milk custard over the top.", "Step 5: Bake at 350°F until golden."], classifications: { mealType: ["dinner"], cookingMethods: ["baking"] }, elementalProperties: { Fire: 0.25, Water: 0.20, Earth: 0.45, Air: 0.10 }, astrologicalAffinities: { planets: ["Jupiter"], signs: ["sagittarius"], lunarPhases: ["Full Moon"] }, nutritionPerServing: { calories: 420, proteinG: 28, carbsG: 12, fatG: 32, fiberG: 2, sodiumMg: 650, sugarG: 8, vitamins: ["Vitamin B12"], minerals: ["Iron"] }, substitutions: [] },
    { name: "Authentic Peri-Peri Chicken", description: "A high-kinetic, fiercely spicy Mozambican/Portuguese fusion. Chicken is marinated in a violent emulsion of bird's eye chilies, lemon, and garlic, then grilled over high heat until charred and electric.", details: { cuisine: "African (Mozambican)", prepTimeMinutes: 60, cookTimeMinutes: 20, baseServingSize: 4, spiceLevel: "Very High", season: ["summer"] }, ingredients: [{ amount: 1, unit: "whole", name: "Chicken", notes: "Spatchcocked." }, { amount: 0.5, unit: "cup", name: "Peri-Peri sauce", notes: "Homemade with bird's eye chilies." }], instructions: ["Step 1: Spatchcock the chicken.", "Step 2: Marinate in peri-peri sauce for 24 hours.", "Step 3: Grill over high heat, skin-side down first.", "Step 4: Baste continuously with marinade.", "Step 5: Rest before carving."], classifications: { mealType: ["dinner"], cookingMethods: ["grilling"] }, elementalProperties: { Fire: 0.65, Water: 0.05, Earth: 0.20, Air: 0.10 }, astrologicalAffinities: { planets: ["Mars"], signs: ["aries"], lunarPhases: ["First Quarter"] }, nutritionPerServing: { calories: 480, proteinG: 42, carbsG: 2, fatG: 34, fiberG: 0, sodiumMg: 850, sugarG: 1, vitamins: ["Vitamin C"], minerals: ["Zinc"] }, substitutions: [] },
    { name: "Authentic Bunny Chow", description: "Durban's structural masterpiece. A hollowed-out loaf of white bread serves as a vessel for a fiercely hot, slow-simmered lamb or bean curry, designed to be eaten entirely with the hands.", details: { cuisine: "South African (Durban)", prepTimeMinutes: 15, cookTimeMinutes: 60, baseServingSize: 2, spiceLevel: "High", season: ["all"] }, ingredients: [{ amount: 1, unit: "loaf", name: "White bread", notes: "Unsliced." }, { amount: 1, unit: "lb", name: "Lamb or mutton", notes: "Curried." }], instructions: ["Step 1: Prepare a thick, spicy lamb curry.", "Step 2: Hollow out a half-loaf of bread.", "Step 3: Fill the cavity with curry.", "Step 4: Place the removed bread 'plug' on top.", "Step 5: Serve with carrot salad."], classifications: { mealType: ["lunch"], cookingMethods: ["simmering", "assembling"] }, elementalProperties: { Fire: 0.40, Water: 0.10, Earth: 0.45, Air: 0.05 }, astrologicalAffinities: { planets: ["Saturn"], signs: ["capricorn"], lunarPhases: ["Full Moon"] }, nutritionPerServing: { calories: 750, proteinG: 35, carbsG: 85, fatG: 38, fiberG: 6, sodiumMg: 1200, sugarG: 4, vitamins: ["Iron"], minerals: ["Zinc"] }, substitutions: [] },
    { name: "Authentic Suya", description: "The iconic West African street food. Skewered beef is coated in 'Yaji'—a potent, high-protein spice matrix made from ground peanuts, ginger, and chilies—then grilled rapidly to a smoky finish.", details: { cuisine: "West African (Nigerian)", prepTimeMinutes: 30, cookTimeMinutes: 10, baseServingSize: 2, spiceLevel: "High", season: ["all"] }, ingredients: [{ amount: 1, unit: "lb", name: "Beef flank", notes: "Sliced paper-thin." }, { amount: 1, unit: "cup", name: "Kuli-Kuli powder", notes: "Ground peanut cake." }], instructions: ["Step 1: Slice beef against the grain thinly.", "Step 2: Coat slices heavily in Yaji spice mix.", "Step 3: Skewer the meat.", "Step 4: Grill over charcoal until charred.", "Step 5: Serve with raw onions and extra spice."], classifications: { mealType: ["snack", "dinner"], cookingMethods: ["grilling"] }, elementalProperties: { Fire: 0.55, Water: 0.05, Earth: 0.30, Air: 0.10 }, astrologicalAffinities: { planets: ["Mars"], signs: ["aries"], lunarPhases: ["First Quarter"] }, nutritionPerServing: { calories: 420, proteinG: 45, carbsG: 8, fatG: 22, fiberG: 2, sodiumMg: 750, sugarG: 2, vitamins: ["Vitamin B12"], minerals: ["Iron"] }, substitutions: [] },
    { name: "Authentic Ndolé", description: "Cameroon's nutritional titan. A dense, savory stew of bitterleaves, ground peanuts, and crayfish, resulting in a complex, creamy, and slightly bitter profile that is deeply restorative.", details: { cuisine: "Cameroonian", prepTimeMinutes: 45, cookTimeMinutes: 60, baseServingSize: 4, spiceLevel: "Medium", season: ["all"] }, ingredients: [{ amount: 2, unit: "cups", name: "Bitterleaves", notes: "Washed multiple times to reduce bitterness." }, { amount: 1, unit: "cup", name: "Ground peanuts", notes: "Freshly boiled and blended." }], instructions: ["Step 1: Wash bitterleaves vigorously.", "Step 2: Blend boiled peanuts into a paste.", "Step 3: Sauté meat/shrimp with aromatics.", "Step 4: Stir in peanut paste and bitterleaves.", "Step 5: Simmer until thick and creamy."], classifications: { mealType: ["dinner"], cookingMethods: ["simmering"] }, elementalProperties: { Fire: 0.15, Water: 0.30, Earth: 0.50, Air: 0.05 }, astrologicalAffinities: { planets: ["Saturn"], signs: ["virgo"], lunarPhases: ["Waning Crescent"] }, nutritionPerServing: { calories: 520, proteinG: 38, carbsG: 15, fatG: 38, fiberG: 12, sodiumMg: 850, sugarG: 4, vitamins: ["Vitamin A", "Vitamin K"], minerals: ["Iron", "Magnesium"] }, substitutions: [] }
  ],
  "chinese.ts": [
    { name: "Authentic Lion's Head Meatballs", description: "Huaiyang's structural masterpiece. Massive, airy pork meatballs are gently braised in a clear broth with cabbage leaves, designed to resemble a lion's head and mane, achieving a 'melt-in-mouth' texture through high fat content and minimal binding.", details: { cuisine: "Chinese (Huaiyang)", prepTimeMinutes: 30, cookTimeMinutes: 90, baseServingSize: 4, spiceLevel: "None", season: ["winter"] }, ingredients: [{ amount: 1, unit: "lb", name: "Pork belly", notes: "Hand-chopped into 3mm cubes." }, { amount: 0.5, unit: "lb", name: "Napa cabbage", notes: "Large leaves." }], instructions: ["Step 1: Hand-chop pork to maintain texture.", "Step 2: Gently mix with water chestnuts and aromatics.", "Step 3: Form into 4 massive spheres.", "Step 4: Briefly sear, then cover with cabbage leaves.", "Step 5: Braise in clear stock for 1.5 hours."], classifications: { mealType: ["dinner"], cookingMethods: ["braising"] }, elementalProperties: { Fire: 0.15, Water: 0.45, Earth: 0.30, Air: 0.10 }, astrologicalAffinities: { planets: ["Moon"], signs: ["cancer"], lunarPhases: ["Full Moon"] }, nutritionPerServing: { calories: 580, proteinG: 22, carbsG: 8, fatG: 52, fiberG: 3, sodiumMg: 750, sugarG: 2, vitamins: ["Vitamin B12"], minerals: ["Zinc"] }, substitutions: [] },
    { name: "Authentic Scallion Oil Noodles", description: "The essence of Shanghai. A study in aromatic extraction where scallions are slowly fried in oil until charred and brittle, creating a deep, umami-rich base for perfectly chewy wheat noodles.", details: { cuisine: "Chinese (Shanghai)", prepTimeMinutes: 5, cookTimeMinutes: 15, baseServingSize: 2, spiceLevel: "None", season: ["all"] }, ingredients: [{ amount: 2, unit: "portions", name: "Fresh wheat noodles", notes: "Thin." }, { amount: 1, unit: "bunch", name: "Scallions", notes: "Whites and greens separated." }], instructions: ["Step 1: Fry scallion whites in oil until golden.", "Step 2: Add greens and fry until dark brown and brittle.", "Step 3: Remove scallions; stir soy sauce and sugar into oil.", "Step 4: Boil noodles until al dente.", "Step 5: Toss noodles in the aromatic oil; top with crispy scallions."], classifications: { mealType: ["lunch", "breakfast"], cookingMethods: ["infusing", "boiling"] }, elementalProperties: { Fire: 0.30, Water: 0.10, Earth: 0.40, Air: 0.20 }, astrologicalAffinities: { planets: ["Mercury"], signs: ["gemini"], lunarPhases: ["New Moon"] }, nutritionPerServing: { calories: 450, proteinG: 12, carbsG: 65, fatG: 24, fiberG: 3, sodiumMg: 950, sugarG: 5, vitamins: ["Vitamin B6"], minerals: ["Manganese"] }, substitutions: [] },
    { name: "Authentic Biang Biang Noodles", description: "The architectural giant of Shaanxi. Massive, belt-thick noodles are hand-pulled and 'biang-ed' against the counter, then topped with raw garlic and chili flakes which are violently flash-cooked by a pour of smoking hot oil.", details: { cuisine: "Chinese (Shaanxi)", prepTimeMinutes: 45, cookTimeMinutes: 5, baseServingSize: 2, spiceLevel: "High", season: ["all"] }, ingredients: [{ amount: 2, unit: "cups", name: "High-gluten flour", notes: "For elasticity." }, { amount: 0.5, unit: "cup", name: "Chili flakes", notes: "Coarse." }], instructions: ["Step 1: Knead a high-hydration dough until elastic.", "Step 2: Roll and pull into wide belts, slapping the counter.", "Step 3: Boil belts for 2 minutes.", "Step 4: Top with raw garlic, scallions, and chili flakes.", "Step 5: Pour 400°F oil directly onto the spices."], classifications: { mealType: ["lunch", "dinner"], cookingMethods: ["pulling", "boiling", "flash-frying"] }, elementalProperties: { Fire: 0.50, Water: 0.15, Earth: 0.25, Air: 0.10 }, astrologicalAffinities: { planets: ["Mars", "Jupiter"], signs: ["aries", "sagittarius"], lunarPhases: ["First Quarter"] }, nutritionPerServing: { calories: 520, proteinG: 14, carbsG: 75, fatG: 22, fiberG: 4, sodiumMg: 850, sugarG: 2, vitamins: ["Niacin"], minerals: ["Iron"] }, substitutions: [] },
    { name: "Authentic Squirrel-Shaped Mandarin Fish", description: "A triumph of Suzhou knife work and temperature control. A whole fish is carved into deep diamonds that expand like fur when deep-fried, then drenched in a vibrant, high-viscosity sweet and sour sauce.", details: { cuisine: "Chinese (Jiangsu)", prepTimeMinutes: 45, cookTimeMinutes: 10, baseServingSize: 2, spiceLevel: "None", season: ["spring"] }, ingredients: [{ amount: 1, unit: "whole", name: "Mandarin fish", notes: "Deboned but head/tail intact." }, { amount: 1, unit: "cup", name: "Tomato sauce/Vinegar", notes: "For the glaze." }], instructions: ["Step 1: Execute 45-degree diamond cuts on the fillets.", "Step 2: Dredge in starch, ensuring it enters all cuts.", "Step 3: Deep fry until the diamond cubes fan out.", "Step 4: Prepare a high-gloss sweet and sour sauce.", "Step 5: Pour sauce over the 'furry' fish while hot."], classifications: { mealType: ["dinner", "celebration"], cookingMethods: ["deep-frying", "knife-work"] }, elementalProperties: { Fire: 0.40, Water: 0.25, Earth: 0.15, Air: 0.20 }, astrologicalAffinities: { planets: ["Venus"], signs: ["libra"], lunarPhases: ["Full Moon"] }, nutritionPerServing: { calories: 480, proteinG: 32, carbsG: 45, fatG: 18, fiberG: 1, sodiumMg: 650, sugarG: 32, vitamins: ["Vitamin C"], minerals: ["Selenium"] }, substitutions: [] },
    { name: "Authentic Dongpo Pork", description: "The alchemical reduction of Hangzhou. Thick cubes of pork belly are slow-braised in a dark, aromatic matrix of Shaoxing wine and soy sauce until the fat becomes purely structural jelly and the meat can be eaten with a spoon.", details: { cuisine: "Chinese (Zhejiang)", prepTimeMinutes: 15, cookTimeMinutes: 180, baseServingSize: 4, spiceLevel: "None", season: ["winter"] }, ingredients: [{ amount: 2, unit: "lbs", name: "Pork belly", notes: "Skin-on." }, { amount: 2, unit: "cups", name: "Shaoxing wine", notes: "High quality." }], instructions: ["Step 1: Blanch pork belly and cut into massive cubes.", "Step 2: Tie with twine to maintain structural shape.", "Step 3: Place skin-side down on ginger and scallions.", "Step 4: Cover with wine and soy; simmer for 3 hours.", "Step 5: Steam for final 30 minutes to render fat to jelly."], classifications: { mealType: ["dinner"], cookingMethods: ["braising", "steaming"] }, elementalProperties: { Fire: 0.10, Water: 0.45, Earth: 0.40, Air: 0.05 }, astrologicalAffinities: { planets: ["Saturn", "Moon"], signs: ["capricorn", "cancer"], lunarPhases: ["Waning Gibbous"] }, nutritionPerServing: { calories: 850, proteinG: 22, carbsG: 12, fatG: 78, fiberG: 1, sodiumMg: 1100, sugarG: 15, vitamins: ["Vitamin B12"], minerals: ["Zinc"] }, substitutions: [] }
  ]
};

// I will now iterate and add these to the dinner.all arrays
for (const [filename, recipes] of Object.entries(additions)) {
    const sf = project.getSourceFile(filename);
    if (!sf) continue;
    
    const objectLiterals = sf.getDescendantsOfKind(SyntaxKind.ObjectLiteralExpression);
    const dishesObjProp = objectLiterals.find(obj => obj.getProperty('dishes'))?.getProperty('dishes');

    if (dishesObjProp) {
        const dishesObj = dishesObjProp.getInitializer();
        const dinnerObj = dishesObj.getProperty('dinner')?.getInitializer();
        if (dinnerObj) {
            const allArray = dinnerObj.getProperty('all')?.getInitializer();
            if (allArray && allArray.getKind() === SyntaxKind.ArrayLiteralExpression) {
                recipes.forEach(recipe => {
                    allArray.addElement(JSON.stringify(recipe, null, 2));
                });
            }
        }
    }
    sf.saveSync();
}

console.log("Added recipes to African and Chinese.");
