# Docker Compose override for local development
# This file automatically extends docker-compose.yml when running docker-compose up

version: "3.8"

services:
  whattoeatnext:
    # Override for development
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - CHOKIDAR_USEPOLLING=true
      - NEXT_PUBLIC_ENABLE_ASTRO_DEBUG=true
      - NEXT_PUBLIC_API_CACHE_TIME=60 # Shorter cache for development
    volumes:
      # Mount source code for hot reload
      - .:/app:cached
      # Prevent overwriting node_modules
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
      - "9229:9229" # Node.js debugger port
    command: yarn dev

    # Development-specific health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
