import * as Astronomy from "astronomy-engine";
import fixture from "../../../docs/physics/esms_conformance.json";
import { PLANET_WEIGHTS, normalizePlanetWeight } from "@/data/planets";
import {
  ESMS_K_MAX,
  formatMicroEsms,
  parseMicroEsms,
  quantizeEsms,
} from "@/lib/economy/esmsQuantization";
import {
  ASCENDANT_VESSEL_WEIGHT,
  calculateAlchemicalFromPlanets,
  getGravitationalInertia,
  getTidalPull,
  inertialMassWeight,
  PLANET_MEAN_GEOCENTRIC_AU,
} from "@/utils/planetaryAlchemyMapping";

describe("ESMS 2.0 Unified Physics Model Conformance Suite", () => {
  it("has 20 golden test charts in fixture", () => {
    expect(fixture.version).toBe("2.3.0");
    expect(fixture.charts.length).toBe(20);
  });

  fixture.charts.forEach((chart) => {
    it(`evaluates ${chart.id} (${chart.name}) without NaN/null`, () => {
      const positions = chart.planetary_positions as Record<string, { sign: string; degree: number; distance?: number }>;
      const isDiurnal = chart.is_diurnal ?? true;
      const {
        Spirit: spirit,
        Essence: essence,
        Matter: matter,
        Substance: substance,
      } = calculateAlchemicalFromPlanets(positions, isDiurnal);

      expect(Number.isFinite(spirit)).toBe(true);
      expect(Number.isFinite(essence)).toBe(true);
      expect(Number.isFinite(matter)).toBe(true);
      expect(Number.isFinite(substance)).toBe(true);

      // REGRESSION — the vessel must actually LAND. The Python port zeroed the
      // Ascendant weight (its period entry is that scale's log-minimum) and
      // every diurnal chart collapsed to Matter = Substance = 0 while all the
      // finiteness assertions above kept passing. Only a value assertion sees it.
      expect(matter).toBeGreaterThan(0);
      expect(substance).toBeGreaterThan(0);

      // CROSS-RUNTIME PARITY — the v2.3 fixture is generated by the Python
      // canonical engine. The TS canonical engine must reproduce every
      // full-precision float64 value exactly, including dignity and aspects.
      const expected = (chart as { expected?: Record<string, number> })
        .expected;
      expect(expected).toBeDefined();
      expect(spirit).toBe(expected!.spirit);
      expect(essence).toBe(expected!.essence);
      expect(matter).toBe(expected!.matter);
      expect(substance).toBe(expected!.substance);

      // §6 MAINNET GATE — the TS quantizer must reproduce the fixture's
      // expected_micro integers byte-identically. Python asserts the same
      // integers from its quantizer.
      const micro = (chart as { expected_micro?: Record<string, number> }).expected_micro;
      expect(micro).toBeDefined();
      expect(quantizeEsms(spirit)).toBe(micro!.spirit);
      expect(quantizeEsms(essence)).toBe(micro!.essence);
      expect(quantizeEsms(matter)).toBe(micro!.matter);
      expect(quantizeEsms(substance)).toBe(micro!.substance);
    });
  });

  it("quantizer: floor never round, and malformed input throws", () => {
    expect(quantizeEsms(1.9999999)).toBe(1_999_999); // floor, not round
    expect(quantizeEsms(0)).toBe(0);
    for (const bad of [NaN, Infinity, -Infinity, -0.001, ESMS_K_MAX + 1]) {
      expect(() => quantizeEsms(bad)).toThrow(TypeError);
    }
  });

  it("quantizer: no float dequantize — the exact-decimal path is the round trip", () => {
    // NEGATIVE CONTROL, the measured §6 rule-5 amendment: pure floor cannot
    // round-trip a float dequantize (q=249's representative multiplies back to
    // 248.99…), so dequantized floats must never re-enter the quantizer.
    expect(Math.floor((249 / 1e6) * 1e6)).toBe(248);
    // The integer-math decimal path is lossless for every integer.
    expect(formatMicroEsms(249)).toBe("0.000249");
    for (let q = 0; q < 2000; q++) {
      expect(parseMicroEsms(formatMicroEsms(q))).toBe(q);
    }
    for (const chart of fixture.charts as Array<{ expected_micro?: Record<string, number> }>) {
      for (const q of Object.values(chart.expected_micro ?? {})) {
        expect(parseMicroEsms(formatMicroEsms(q))).toBe(q);
      }
    }
  });

  it("pins the source tables to the fixture — the shared parity witness", () => {
    expect((fixture as { epoch_mean_geocentric_au?: Record<string, number> }).epoch_mean_geocentric_au)
      .toEqual(PLANET_MEAN_GEOCENTRIC_AU);
    expect((fixture as { mass_weights?: Record<string, number> }).mass_weights)
      .toEqual(PLANET_WEIGHTS);
  });

  it("annihilates no charted body on the inertial mass scale", () => {
    // normalizePlanetWeight anchors AT Pluto, so Pluto is exactly 0 on that
    // scale — the same extremum-annihilation that zeroed the Ascendant on the
    // period scale (PR #683). POSITIVE CONTROL first: the trap is real.
    expect(normalizePlanetWeight(PLANET_WEIGHTS.Pluto)).toBe(0);
    // The inertial scale anchors one decade below Pluto (RULED): all bodies > 0.
    expect(inertialMassWeight("Sun")).toBe(1.0);
    for (const body of Object.keys(PLANET_MEAN_GEOCENTRIC_AU)) {
      expect(inertialMassWeight(body)).toBeGreaterThan(0);
    }
    // Re-derivable pin, mirrored in test_esms_conformance.py.
    const expectPluto =
      (Math.log10(0.0022) - Math.log10(0.00022)) /
      (Math.log10(333054.2532) - Math.log10(0.00022));
    expect(inertialMassWeight("Pluto")).toBeCloseTo(expectPluto, 12);
  });

  it("makes Λ relative: r = r̄ gives exactly the weight, and the real Moon no longer detonates", () => {
    // REGRESSION: under the old M/r², the Moon's real distance (0.00257 AU)
    // produced inertia ≈ 43,043 vs the Sun's 0.51 — live natal ESMS was 99.99%
    // Moon and canonical kalchm overflowed into the φ fallback (spec §7).
    const rBar = PLANET_MEAN_GEOCENTRIC_AU.Moon;
    expect(getGravitationalInertia("Moon", rBar)).toBe(inertialMassWeight("Moon"));
    const atPerigee = getGravitationalInertia("Moon", 0.002384073736896684);
    expect(atPerigee).toBeLessThan(0.25); // O(weight), not 43,043
    expect(atPerigee).toBeGreaterThan(inertialMassWeight("Moon")); // perigee amplifies
  });

  it("re-derives the epoch-mean geocentric distances from the ephemeris", () => {
    // PLANET_MEAN_GEOCENTRIC_AU is MEASURED, and this is where it is re-measured
    // — the stated basis (2026 epoch, 6-hour grid, astronomy-engine GeoVector)
    // run for real, not trusted as a comment. If astronomy-engine or the epoch
    // definition changes, THIS fails and names the cause.
    const epoch = (fixture as { epoch?: { startUtc: string; samples: number; stepHours: number } }).epoch;
    expect(epoch).toBeDefined();
    const bodies: Array<[string, Astronomy.Body]> = [
      ["Sun", Astronomy.Body.Sun], ["Moon", Astronomy.Body.Moon],
      ["Mercury", Astronomy.Body.Mercury], ["Venus", Astronomy.Body.Venus],
      ["Mars", Astronomy.Body.Mars], ["Jupiter", Astronomy.Body.Jupiter],
      ["Saturn", Astronomy.Body.Saturn], ["Uranus", Astronomy.Body.Uranus],
      ["Neptune", Astronomy.Body.Neptune], ["Pluto", Astronomy.Body.Pluto],
    ];
    const start = Date.parse(epoch!.startUtc);
    const stepMs = epoch!.stepHours * 3600 * 1000;
    const sums: Record<string, number> = {};
    for (let i = 0; i < epoch!.samples; i++) {
      const t = Astronomy.MakeTime(new Date(start + i * stepMs));
      for (const [name, body] of bodies) {
        const v = Astronomy.GeoVector(body, t, true);
        sums[name] = (sums[name] ?? 0) + Math.hypot(v.x, v.y, v.z) / epoch!.samples;
      }
    }
    for (const [name] of bodies) {
      expect(sums[name]).toBeCloseTo(PLANET_MEAN_GEOCENTRIC_AU[name], 10);
    }
  });

  it("pins the Ascendant vessel weight to the RULED anchor 1.0 in both runtimes", () => {
    // test_esms_conformance.py pins the identical value on the Python side.
    expect(ASCENDANT_VESSEL_WEIGHT).toBe(1.0);
    expect(getGravitationalInertia("Ascendant")).toBe(1.0); // r = 1.0 AU
    expect(getTidalPull("Ascendant")).toBe(1.0);
    // POSITIVE CONTROL — what the accidental `?? 1.0` fallback used to produce:
    // Earth's relative MASS through the mass normalizer, ≈ 0.3249, not a ruling.
    expect(PLANET_WEIGHTS["Ascendant" as keyof typeof PLANET_WEIGHTS]).toBeUndefined();
    expect(normalizePlanetWeight(1.0)).toBeCloseTo(0.3248835368415509, 12);
    expect(normalizePlanetWeight(1.0)).not.toBe(ASCENDANT_VESSEL_WEIGHT);
  });
});
