# Prometheus Configuration for alchm.kitchen Production Monitoring
# Comprehensive monitoring setup for microservices architecture

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'alchm-kitchen-monitor'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load alerting rules
rule_files:
  - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # NGINX Load Balancer
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:8080']
    scrape_interval: 10s
    metrics_path: /nginx-health
    scrape_timeout: 5s

  # Alchemical Core Services
  - job_name: 'alchemical-core'
    static_configs:
      - targets:
          - 'alchemical-core-1:9090'
          - 'alchemical-core-2:9091'
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s
    params:
      format: ['prometheus']

  # Kitchen Intelligence Services
  - job_name: 'kitchen-intelligence'
    static_configs:
      - targets:
          - 'kitchen-intelligence-1:9092'
          - 'kitchen-intelligence-2:9093'
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s
    params:
      format: ['prometheus']

  # WebSocket Service
  - job_name: 'websocket-service'
    static_configs:
      - targets: ['websocket-service:9094']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s

  # PostgreSQL Database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s
    scrape_timeout: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: postgres-exporter:9187

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-cluster:6379']
    scrape_interval: 15s
    scrape_timeout: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: redis-exporter:9121

  # Node/Container metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    scrape_timeout: 5s

  # Docker container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    scrape_timeout: 5s

  # API Health Checks
  - job_name: 'api-health'
    metrics_path: /health
    scrape_interval: 30s
    scrape_timeout: 10s
    static_configs:
      - targets:
          - 'alchemical-core-1:8000'
          - 'alchemical-core-2:8000'
          - 'kitchen-intelligence-1:8100'
          - 'kitchen-intelligence-2:8100'
          - 'websocket-service:8001'
    relabel_configs:
      - source_labels: [__address__]
        target_label: service_endpoint

  # Custom application metrics
  - job_name: 'alchm-custom-metrics'
    metrics_path: /api/metrics
    scrape_interval: 30s
    scrape_timeout: 10s
    static_configs:
      - targets:
          - 'alchemical-core-1:8000'
          - 'alchemical-core-2:8000'
          - 'kitchen-intelligence-1:8100'
          - 'kitchen-intelligence-2:8100'
    basic_auth:
      username: 'prometheus'
      password: 'monitoring_secret'

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention.time: 15d
    retention.size: 10GB

# Remote write configuration (for long-term storage)
# remote_write:
#   - url: "https://prometheus-remote-write.example.com/api/v1/write"
#     basic_auth:
#       username: "remote_user"
#       password: "remote_password"