"use client";

/**
 * Recipe Suggestion Carousel
 * Displays a swipeable carousel of recipe suggestions generated by the
 * planetary recommendation pipeline. Supports touch gestures, prev/next
 * navigation, pagination dots, and integrates natal-chart personalization
 * indicators when the user is signed in.
 *
 * @file src/components/recipe-builder/RecipeSuggestionCarousel.tsx
 */

import Link from "next/link";
import React, { useRef, type TouchEvent as ReactTouchEvent } from "react";
import { saveRecipeToStore } from "@/utils/generatedRecipeStore";
import { createLogger } from "@/utils/logger";
import type { RecommendedMeal } from "@/utils/menuPlanner/recommendationBridge";

const logger = createLogger("RecipeSuggestionCarousel");

// ===== Element helpers =====

const ELEMENT_ICONS: Record<string, string> = {
  Fire: "🔥",
  Water: "💧",
  Earth: "🌍",
  Air: "💨",
};

const ELEMENT_COLORS: Record<string, string> = {
  Fire: "bg-red-500",
  Water: "bg-blue-500",
  Earth: "bg-amber-700",
  Air: "bg-sky-400",
};

// ===== Loading skeleton =====

function CarouselSkeleton() {
  return (
    <div className="bg-white rounded-2xl shadow-lg border-2 border-purple-100 p-6 mx-6 animate-pulse">
      <div className="h-6 bg-gray-200 rounded w-3/4 mb-3" />
      <div className="h-4 bg-gray-100 rounded w-1/3 mb-4" />
      <div className="h-4 bg-gray-100 rounded w-full mb-2" />
      <div className="h-4 bg-gray-100 rounded w-5/6 mb-6" />
      <div className="flex gap-2 mb-4">
        {[1, 2, 3, 4, 5, 6].map((i) => (
          <div key={i} className="h-6 w-16 bg-gray-100 rounded-full" />
        ))}
      </div>
      <div className="h-10 bg-gray-200 rounded-xl w-full" />
    </div>
  );
}

// ===== Main carousel card =====

interface RecipeSuggestionCarouselProps {
  suggestions: RecommendedMeal[];
  currentIndex: number;
  onIndexChange: (index: number) => void;
  isLoading: boolean;
  isPersonalized?: boolean;
  onSaveToQueue?: (meal: RecommendedMeal) => void;
}

export default function RecipeSuggestionCarousel({
  suggestions,
  currentIndex,
  onIndexChange,
  isLoading,
  isPersonalized = false,
  onSaveToQueue,
}: RecipeSuggestionCarouselProps) {
  const touchStartX = useRef<number | null>(null);
  const touchEndX = useRef<number | null>(null);
  const MIN_SWIPE = 50;

  // Expandable sections state
  const [expandedSections, setExpandedSections] = React.useState<Record<string, boolean>>({});

  const toggleSection = (section: string) => {
    setExpandedSections((prev) => ({ ...prev, [section]: !prev[section] }));
  };

  // ---- Navigation ----
  const handlePrev = () => {
    if (currentIndex > 0) onIndexChange(currentIndex - 1);
  };
  const handleNext = () => {
    if (currentIndex < suggestions.length - 1) onIndexChange(currentIndex + 1);
  };

  // ---- Touch swipe ----
  const onTouchStart = (e: ReactTouchEvent) => {
    touchStartX.current = e.targetTouches[0].clientX;
    touchEndX.current = null;
  };
  const onTouchMove = (e: ReactTouchEvent) => {
    touchEndX.current = e.targetTouches[0].clientX;
  };
  const onTouchEnd = () => {
    if (!touchStartX.current || !touchEndX.current) return;
    const dist = touchStartX.current - touchEndX.current;
    if (dist > MIN_SWIPE) handleNext();
    else if (dist < -MIN_SWIPE) handlePrev();
    touchStartX.current = null;
    touchEndX.current = null;
  };

  // ---- Loading state ----
  if (isLoading) {
    return (
      <div className="space-y-4">
        <div className="flex items-center justify-center gap-2 text-amber-600 py-2">
          <svg className="animate-spin h-5 w-5" viewBox="0 0 24 24" fill="none">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
          </svg>
          <span className="text-sm font-medium">Consulting the cosmos for your perfect recipe...</span>
        </div>
        <CarouselSkeleton />
      </div>
    );
  }

  // ---- Empty state ----
  if (suggestions.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-12 text-center text-gray-500 bg-white rounded-2xl shadow-sm border border-gray-100">
        <span className="text-4xl mb-3">🌌</span>
        <p className="font-medium text-gray-700">No recipes found</p>
        <p className="text-sm mt-1">Try different ingredients or preferences</p>
      </div>
    );
  }

  const current = suggestions[currentIndex];
  if (!current) return null;

  const recipe = current.recipe;
  const displayScore = current.personalizedScore ?? current.score;
  const scorePercent = Math.round(displayScore * 100);

  const handleSave = () => {
    if (recipe?.id) {
      saveRecipeToStore(recipe);
      logger.info(`Saved recipe to store: ${recipe.name}`);
    }
    onSaveToQueue?.(current);
  };

  return (
    <div className="space-y-4">
      {/* Header bar */}
      <div className="flex items-center justify-between px-1">
        <div className="flex items-center gap-2">
          <span className="text-sm font-semibold text-gray-700">
            Recipe {currentIndex + 1} of {suggestions.length}
          </span>
          {isPersonalized && (
            <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-purple-100 text-purple-700 text-xs font-medium">
              ✨ Personalized
            </span>
          )}
          {current.isPersonalized && current.personalizationBoost && current.personalizationBoost > 1.05 && (
            <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-indigo-50 text-indigo-600 text-xs">
              🌟 Chart aligned
            </span>
          )}
        </div>
        <div className="flex items-center gap-1">
          <button
            onClick={handlePrev}
            disabled={currentIndex === 0}
            className="w-8 h-8 rounded-full bg-white shadow border border-gray-200 flex items-center justify-center text-sm transition-all hover:bg-gray-50 disabled:opacity-30 disabled:cursor-not-allowed"
            aria-label="Previous recipe"
          >
            ←
          </button>
          <button
            onClick={handleNext}
            disabled={currentIndex === suggestions.length - 1}
            className="w-8 h-8 rounded-full bg-white shadow border border-gray-200 flex items-center justify-center text-sm transition-all hover:bg-gray-50 disabled:opacity-30 disabled:cursor-not-allowed"
            aria-label="Next recipe"
          >
            →
          </button>
        </div>
      </div>

      {/* Main card with touch support */}
      <div
        className="relative"
        onTouchStart={onTouchStart}
        onTouchMove={onTouchMove}
        onTouchEnd={onTouchEnd}
      >
        <div className="bg-white rounded-2xl shadow-lg border-2 border-purple-100 overflow-hidden transition-all">
          {/* Card header */}
          <div className="p-5 pb-3">
            <div className="flex items-start justify-between gap-3 mb-2">
              <div className="flex-1 min-w-0">
                <h3 className="text-xl font-bold text-gray-800 leading-tight">
                  {recipe.name}
                </h3>
                <div className="flex flex-wrap items-center gap-2 mt-1.5">
                  {recipe.cuisine && (
                    <span className="px-2 py-0.5 bg-blue-100 text-blue-700 rounded text-xs font-medium capitalize">
                      {recipe.cuisine}
                    </span>
                  )}
                  {current.mealType && (
                    <span className="px-2 py-0.5 bg-amber-100 text-amber-700 rounded text-xs font-medium capitalize">
                      {current.mealType}
                    </span>
                  )}
                  {recipe.prepTime && (
                    <span className="px-2 py-0.5 bg-gray-100 text-gray-600 rounded text-xs">
                      ⏱ {recipe.prepTime}
                    </span>
                  )}
                  {recipe.numberOfServings && (
                    <span className="px-2 py-0.5 bg-gray-100 text-gray-600 rounded text-xs">
                      🍽 {recipe.numberOfServings} servings
                    </span>
                  )}
                </div>
              </div>

              {/* Score badge */}
              <div className="shrink-0 text-center">
                <div className="w-14 h-14 rounded-full bg-gradient-to-br from-purple-500 to-pink-500 flex flex-col items-center justify-center text-white shadow-md">
                  <span className="text-lg font-bold leading-none">{scorePercent}</span>
                  <span className="text-[9px] opacity-80">match</span>
                </div>
              </div>
            </div>

            {/* Description */}
            {recipe.description && (
              <p className="text-sm text-gray-600 line-clamp-2 mt-2">
                {recipe.description}
              </p>
            )}
          </div>

          {/* Elemental profile */}
          {recipe.elementalProperties && (
            <div className="px-5 pb-3">
              <div className="text-xs font-semibold text-gray-500 mb-2 uppercase tracking-wide">
                Elemental Profile
              </div>
              <div className="grid grid-cols-4 gap-2">
                {(["Fire", "Water", "Earth", "Air"] as const).map((el) => {
                  const val = recipe.elementalProperties?.[el] ?? 0;
                  const pct = Math.round(val * 100);
                  return (
                    <div key={el} className="space-y-1">
                      <div className="flex items-center justify-between text-xs">
                        <span>{ELEMENT_ICONS[el]}</span>
                        <span className="text-gray-500">{pct}%</span>
                      </div>
                      <div className="h-1.5 bg-gray-100 rounded-full overflow-hidden">
                        <div
                          className={`h-full rounded-full ${ELEMENT_COLORS[el]}`}
                          style={{ width: `${pct}%` }}
                        />
                      </div>
                      <div className="text-[10px] text-gray-400 text-center">{el}</div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}

          {/* Scores breakdown */}
          <div className="px-5 pb-3 flex flex-wrap gap-2">
            <div className="px-2.5 py-1 bg-indigo-50 rounded-lg text-center">
              <div className="text-xs font-semibold text-indigo-600">
                {Math.round(current.dayAlignment * 100)}%
              </div>
              <div className="text-[10px] text-indigo-400">Day align</div>
            </div>
            <div className="px-2.5 py-1 bg-purple-50 rounded-lg text-center">
              <div className="text-xs font-semibold text-purple-600">
                {Math.round(current.planetaryAlignment * 100)}%
              </div>
              <div className="text-[10px] text-purple-400">Planetary</div>
            </div>
            {current.personalizationBoost && (
              <div className="px-2.5 py-1 bg-pink-50 rounded-lg text-center">
                <div className="text-xs font-semibold text-pink-600">
                  {current.personalizationBoost > 1
                    ? `+${Math.round((current.personalizationBoost - 1) * 100)}%`
                    : `${Math.round((current.personalizationBoost - 1) * 100)}%`}
                </div>
                <div className="text-[10px] text-pink-400">Chart boost</div>
              </div>
            )}
            {(recipe as any).alchemicalProperties?.monicaConstant != null && (
              <div className="px-2.5 py-1 bg-amber-50 rounded-lg text-center">
                <div className="text-xs font-semibold text-amber-600">
                  {Number((recipe as any).alchemicalProperties.monicaConstant).toFixed(2)}
                </div>
                <div className="text-[10px] text-amber-400">Monica</div>
              </div>
            )}
          </div>

          {/* Reasons */}
          {current.reasons.length > 0 && (
            <div className="mx-5 mb-3 p-3 bg-purple-50 rounded-xl">
              <div className="text-xs font-semibold text-purple-700 mb-1.5">
                Why this recipe?
              </div>
              <ul className="space-y-0.5">
                {current.reasons.slice(0, 4).map((reason, i) => (
                  <li key={i} className="flex items-start gap-1.5 text-xs text-purple-700">
                    <span className="text-purple-400 mt-0.5">✓</span>
                    {reason}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Key ingredients — expandable */}
          {recipe.ingredients && recipe.ingredients.length > 0 && (
            <div className="px-5 pb-3">
              <button
                onClick={() => toggleSection("ingredients")}
                className="flex items-center justify-between w-full text-xs font-semibold text-gray-500 mb-2 uppercase tracking-wide hover:text-gray-700 transition-colors"
              >
                <span>Ingredients ({recipe.ingredients.length})</span>
                <span className="text-sm">{expandedSections["ingredients"] ? "▲" : "▼"}</span>
              </button>
              <div className="flex flex-wrap gap-1.5">
                {(expandedSections["ingredients"]
                  ? recipe.ingredients
                  : recipe.ingredients.slice(0, 8)
                ).map((ing, idx) => (
                  <span
                    key={idx}
                    className="px-2 py-1 bg-gray-100 text-gray-700 text-xs rounded-lg"
                  >
                    {ing.amount} {ing.unit} {ing.name}
                  </span>
                ))}
                {!expandedSections["ingredients"] && recipe.ingredients.length > 8 && (
                  <button
                    onClick={() => toggleSection("ingredients")}
                    className="px-2 py-1 bg-purple-50 text-purple-600 text-xs rounded-lg hover:bg-purple-100 transition-colors"
                  >
                    +{recipe.ingredients.length - 8} more
                  </button>
                )}
              </div>
            </div>
          )}

          {/* Instructions — expandable */}
          {recipe.instructions && recipe.instructions.length > 0 && (
            <div className="px-5 pb-4">
              <button
                onClick={() => toggleSection("steps")}
                className="flex items-center justify-between w-full text-xs font-semibold text-gray-500 mb-2 uppercase tracking-wide hover:text-gray-700 transition-colors"
              >
                <span>Cooking Steps ({recipe.instructions.length})</span>
                <span className="text-sm">{expandedSections["steps"] ? "▲" : "▼"}</span>
              </button>
              <ol className="space-y-1.5">
                {(expandedSections["steps"]
                  ? recipe.instructions
                  : recipe.instructions.slice(0, 4)
                ).map((step, idx) => (
                  <li key={idx} className="flex gap-2 text-sm text-gray-700">
                    <span className="shrink-0 w-5 h-5 rounded-full bg-purple-100 text-purple-700 text-xs font-bold flex items-center justify-center mt-0.5">
                      {idx + 1}
                    </span>
                    <span>{step}</span>
                  </li>
                ))}
                {!expandedSections["steps"] && recipe.instructions.length > 4 && (
                  <li>
                    <button
                      onClick={() => toggleSection("steps")}
                      className="text-xs text-purple-600 pl-7 hover:text-purple-800 transition-colors"
                    >
                      + {recipe.instructions.length - 4} more steps
                    </button>
                  </li>
                )}
              </ol>
            </div>
          )}

          {/* Seasonal adaptation notes */}
          {recipe.seasonalAdaptation?.seasonalIngredientSubstitutions &&
            recipe.seasonalAdaptation.seasonalIngredientSubstitutions.length > 0 && (
              <div className="mx-5 mb-3 p-3 bg-green-50 rounded-xl">
                <div className="text-xs font-semibold text-green-700 mb-1">
                  🌿 Seasonal Tips ({recipe.seasonalAdaptation.currentSeason})
                </div>
                {recipe.seasonalAdaptation.seasonalIngredientSubstitutions
                  .slice(0, 2)
                  .map((sub, i) => (
                    <p key={i} className="text-xs text-green-600">
                      Swap {sub.original} → {sub.seasonal} ({sub.reason})
                    </p>
                  ))}
              </div>
            )}

          {/* Action buttons */}
          <div className="px-5 pb-5 flex gap-2 border-t border-gray-100 pt-3">
            <button
              onClick={handleSave}
              className="flex-1 py-2.5 rounded-xl text-sm font-semibold bg-gradient-to-r from-purple-600 to-pink-600 text-white hover:from-purple-700 hover:to-pink-700 transition-all shadow-sm hover:shadow-md active:scale-[0.98]"
            >
              Save Recipe
            </button>
            {recipe.id && (
              <Link
                href={`/generated-recipe/${recipe.id}`}
                className="px-4 py-2.5 rounded-xl text-sm font-semibold border border-purple-200 text-purple-700 hover:bg-purple-50 transition-all"
              >
                Full Recipe
              </Link>
            )}
          </div>
        </div>
      </div>

      {/* Pagination dots */}
      <div className="flex justify-center gap-1.5 py-1">
        {suggestions.map((_, idx) => (
          <button
            key={idx}
            onClick={() => onIndexChange(idx)}
            className={`rounded-full transition-all ${
              idx === currentIndex
                ? "w-6 h-2 bg-purple-500"
                : "w-2 h-2 bg-gray-300 hover:bg-gray-400"
            }`}
            aria-label={`Go to recipe ${idx + 1}`}
          />
        ))}
      </div>

      {/* Swipe hint for mobile */}
      <p className="text-center text-xs text-gray-400">
        Swipe or use arrows to explore {suggestions.length} suggestions
      </p>
    </div>
  );
}
