"use client";

/**
 * Recipe Suggestion Carousel
 *
 * Displays a swipeable carousel of alchemical recipe suggestions generated by the
 * planetary recommendation pipeline. Supports touch gestures, desktop arrow navigation,
 * pagination indicators, pantry item matching, and 1-click grocery cart addition.
 * Each card's content lives in `./carousel/`.
 *
 * @file src/components/recipe-builder/RecipeSuggestionCarousel.tsx
 */

import {
  AnimatePresence,
  motion,
  useMotionValue,
  useTransform,
  type MotionValue,
  type PanInfo,
  type Transition,
  type Variants,
} from "framer-motion";
import React, { useEffect, useState } from "react";
import type { RecommendedMeal } from "@/utils/menuPlanner/recommendationBridge";
import {
  CarouselEmpty,
  CarouselHeader,
  CarouselLoading,
  CarouselPagination,
  NavButton,
} from "./carousel/CarouselChrome";
import RecipeDossierCard from "./carousel/RecipeDossierCard";

/** Drag distance (px) or flick velocity (px/s) that turns the card. */
const SWIPE_OFFSET = 80;
const SWIPE_VELOCITY = 300;

const SLIDE_TRANSITION: Transition = {
  x: { type: "spring", stiffness: 350, damping: 30 },
  opacity: { duration: 0.15 },
  scale: { duration: 0.15 },
};

const cardVariants: Variants = {
  enter: (dir: number) => ({ x: Math.sign(dir) * 150, opacity: 0, scale: 0.98 }),
  center: { x: 0, opacity: 1, scale: 1, transition: SLIDE_TRANSITION },
  exit: (dir: number) => ({ x: Math.sign(dir) * -150, opacity: 0, scale: 0.98, transition: SLIDE_TRANSITION }),
};

interface RecipeSuggestionCarouselProps {
  suggestions: RecommendedMeal[];
  currentIndex: number;
  onIndexChange: (index: number) => void;
  isLoading: boolean;
  isPersonalized?: boolean;
  onSaveToQueue?: (meal: RecommendedMeal) => void;
}

interface SwipeSlideProps {
  direction: number;
  onDragEnd: (event: unknown, info: PanInfo) => void;
  x: MotionValue<number>;
  rotate: MotionValue<number>;
  children: React.ReactNode;
}

function SwipeSlide({ direction, onDragEnd, x, rotate, children }: SwipeSlideProps): React.JSX.Element {
  return (
    <motion.div
      custom={direction}
      variants={cardVariants}
      initial="enter"
      animate="center"
      exit="exit"
      drag="x"
      dragConstraints={{ left: 0, right: 0 }}
      dragElastic={0.6}
      onDragEnd={onDragEnd}
      style={{ x, rotate }}
      aria-roledescription="slide"
      className="w-full select-none cursor-grab active:cursor-grabbing"
    >
      {children}
    </motion.div>
  );
}

/** Index changes with a slide direction, plus the drag gesture that triggers them. */
function useCarouselNavigation(
  currentIndex: number,
  count: number,
  onIndexChange: (index: number) => void,
): {
  direction: number;
  goTo: (index: number) => void;
  handleDragEnd: (event: unknown, info: PanInfo) => void;
  x: MotionValue<number>;
  rotate: MotionValue<number>;
} {
  const [direction, setDirection] = useState(0);
  const x = useMotionValue(0);
  const rotate = useTransform(x, [-200, 200], [-3, 3]);

  useEffect(() => {
    x.set(0);
  }, [currentIndex, x]);

  const goTo = (index: number): void => {
    if (index < 0 || index >= count || index === currentIndex) return;
    setDirection(index > currentIndex ? 1 : -1);
    onIndexChange(index);
  };

  const handleDragEnd = (_event: unknown, info: PanInfo): void => {
    if (info.offset.x < -SWIPE_OFFSET || info.velocity.x < -SWIPE_VELOCITY) goTo(currentIndex + 1);
    else if (info.offset.x > SWIPE_OFFSET || info.velocity.x > SWIPE_VELOCITY) goTo(currentIndex - 1);
  };

  return { direction, goTo, handleDragEnd, x, rotate };
}

export default function RecipeSuggestionCarousel({
  suggestions,
  currentIndex,
  onIndexChange,
  isLoading,
  isPersonalized = false,
  onSaveToQueue,
}: RecipeSuggestionCarouselProps): React.JSX.Element | null {
  const { direction, goTo, handleDragEnd, x, rotate } = useCarouselNavigation(
    currentIndex,
    suggestions.length,
    onIndexChange,
  );

  if (isLoading) return <CarouselLoading />;
  if (suggestions.length === 0) return <CarouselEmpty />;
  const current = suggestions[currentIndex];
  if (!current) return null;

  return (
    <section aria-roledescription="carousel" aria-label="Recipe suggestions" className="space-y-4 relative px-0 md:px-2">
      <CarouselHeader current={current} position={currentIndex + 1} total={suggestions.length} isPersonalized={isPersonalized} />
      <div className="relative group/carousel">
        <NavButton direction="prev" disabled={currentIndex === 0} onClick={() => goTo(currentIndex - 1)} />
        <NavButton direction="next" disabled={currentIndex === suggestions.length - 1} onClick={() => goTo(currentIndex + 1)} />
        {/* Viewport crops the sliding cards */}
        <div className="overflow-hidden p-1 -m-1">
          <AnimatePresence initial={false} custom={direction} mode="wait">
            <SwipeSlide
              // Keyed by recipe too, so a fresh generation landing on the same
              // index remounts the card and clears its saved/cart state.
              key={`${currentIndex}-${current.recipe.id || current.recipe.name}`}
              direction={direction}
              onDragEnd={handleDragEnd}
              x={x}
              rotate={rotate}
            >
              <RecipeDossierCard meal={current} onSaved={onSaveToQueue} />
            </SwipeSlide>
          </AnimatePresence>
        </div>
      </div>
      <CarouselPagination count={suggestions.length} currentIndex={currentIndex} onSelect={goTo} />
      <p className="text-center text-[11px] font-mono text-muted-foreground select-none">
        Swipe or use arrows to examine {suggestions.length} celestial syntheses
      </p>
    </section>
  );
}
