"use client";

/**
 * Recipe Suggestion Carousel
 *
 * Displays a swipeable carousel of alchemical recipe suggestions generated by the
 * planetary recommendation pipeline. Supports touch gestures, desktop arrow navigation,
 * pagination indicators, pantry item matching, and 1-click grocery cart addition.
 *
 * @file src/components/recipe-builder/RecipeSuggestionCarousel.tsx
 */

import { motion, AnimatePresence, useMotionValue, useTransform } from "framer-motion";
import {
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  Sparkles,
  Clock,
  Users,
  ShoppingBag,
  Bookmark,
  ExternalLink,
  Check,
  PackageCheck,
  Flame,
  Compass,
} from "lucide-react";
import Link from "next/link";
import React, { useState, useEffect } from "react";
import { useOptionalGroceryCart } from "@/contexts/GroceryCartContext";
import { usePantry } from "@/hooks/usePantry";
import { saveRecipeToStore } from "@/utils/generatedRecipeStore";
import { createLogger } from "@/utils/logger";
import type { RecommendedMeal } from "@/utils/menuPlanner/recommendationBridge";

const logger = createLogger("RecipeSuggestionCarousel");

// ===== Element helpers =====

const ELEMENT_ICONS: Record<string, string> = {
  Fire: "\uD83D\uDD25",
  Water: "\uD83D\uDCA7",
  Earth: "\uD83C\uDF0D",
  Air: "\uD83D\uDCA8",
};

const ELEMENT_BAR_COLORS: Record<string, string> = {
  Fire: "bg-gradient-to-r from-amber-500 to-red-500 shadow-[0_0_8px_rgba(245,158,11,0.5)]",
  Water: "bg-gradient-to-r from-blue-500 to-cyan-400 shadow-[0_0_8px_rgba(6,182,212,0.5)]",
  Earth: "bg-gradient-to-r from-emerald-600 to-amber-500 shadow-[0_0_8px_rgba(16,185,129,0.5)]",
  Air: "bg-gradient-to-r from-sky-400 to-indigo-400 shadow-[0_0_8px_rgba(56,189,248,0.5)]",
};

// ===== Loading skeleton =====

function CarouselSkeleton(): React.ReactNode {
  return (
    <div className="rounded-2xl border border-white/10 bg-black/60 p-6 mx-2 md:mx-6 animate-pulse backdrop-blur-xl">
      <div className="h-7 bg-white/10 rounded w-3/4 mb-3" />
      <div className="h-4 bg-white/5 rounded w-1/3 mb-4" />
      <div className="h-4 bg-white/5 rounded w-full mb-2" />
      <div className="h-4 bg-white/5 rounded w-5/6 mb-6" />
      <div className="flex gap-2 mb-4">
        {[1, 2, 3, 4, 5].map((i) => (
          <div key={i} className="h-6 w-20 bg-white/10 rounded-full" />
        ))}
      </div>
      <div className="h-12 bg-white/10 rounded-xl w-full" />
    </div>
  );
}

// ===== Main carousel card =====

interface RecipeSuggestionCarouselProps {
  suggestions: RecommendedMeal[];
  currentIndex: number;
  onIndexChange: (index: number) => void;
  isLoading: boolean;
  isPersonalized?: boolean;
  onSaveToQueue?: (meal: RecommendedMeal) => void;
}

const cardVariants = {
  enter: (dir: number) => ({
    x: dir > 0 ? 150 : dir < 0 ? -150 : 0,
    opacity: 0,
    scale: 0.98,
  }),
  center: {
    x: 0,
    opacity: 1,
    scale: 1,
    transition: {
      x: { type: "spring" as const, stiffness: 350, damping: 30 },
      opacity: { duration: 0.15 },
      scale: { duration: 0.15 },
    },
  },
  exit: (dir: number) => ({
    x: dir < 0 ? 150 : dir > 0 ? -150 : 0,
    opacity: 0,
    scale: 0.98,
    transition: {
      x: { type: "spring" as const, stiffness: 350, damping: 30 },
      opacity: { duration: 0.15 },
      scale: { duration: 0.15 },
    },
  }),
};

export default function RecipeSuggestionCarousel({
  suggestions,
  currentIndex,
  onIndexChange,
  isLoading,
  isPersonalized = false,
  onSaveToQueue,
}: RecipeSuggestionCarouselProps): React.ReactNode {
  const [direction, setDirection] = useState<number>(0);
  const x = useMotionValue(0);
  const rotate = useTransform(x, [-200, 200], [-3, 3]);

  // Context integrations
  const { hasItem } = usePantry();
  const groceryCart = useOptionalGroceryCart();

  // Local interaction states
  const [expandedSections, setExpandedSections] = useState<Record<string, boolean>>({});
  const [isSaved, setIsSaved] = useState(false);
  const [cartSuccessNotice, setCartSuccessNotice] = useState<string | null>(null);

  const toggleSection = (section: string): void => {
    setExpandedSections((prev) => ({ ...prev, [section]: !prev[section] }));
  };

  // Reset states on index change
  useEffect(() => {
    x.set(0);
    setIsSaved(false);
    setCartSuccessNotice(null);
  }, [currentIndex, x]);

  // ---- Navigation ----
  const handlePrev = (): void => {
    if (currentIndex > 0) {
      setDirection(-1);
      onIndexChange(currentIndex - 1);
    }
  };
  const handleNext = (): void => {
    if (currentIndex < suggestions.length - 1) {
      setDirection(1);
      onIndexChange(currentIndex + 1);
    }
  };

  // ---- Drag swipe handler ----
  const handleDragEnd = (_event: unknown, info: { offset: { x: number }; velocity: { x: number } }): void => {
    const swipeThreshold = 80;
    const offset = info.offset.x;
    const velocity = info.velocity.x;

    if (offset < -swipeThreshold || velocity < -300) {
      handleNext();
    } else if (offset > swipeThreshold || velocity > 300) {
      handlePrev();
    }
  };

  // ---- Loading state ----
  if (isLoading) {
    return (
      <div className="space-y-4">
        <div className="flex items-center justify-center gap-2 text-purple-300 py-2">
          <svg className="animate-spin h-5 w-5 text-amber-400" viewBox="0 0 24 24" fill="none">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
          </svg>
          <span className="text-sm font-mono tracking-wide">
            Consulting the celestial transits for your synthesis...
          </span>
        </div>
        <CarouselSkeleton />
      </div>
    );
  }

  // ---- Empty state ----
  if (suggestions.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-12 text-center text-gray-400 rounded-2xl border border-white/10 bg-black/40 backdrop-blur-xl">
        <span className="text-4xl mb-3" aria-hidden>
          \u2728
        </span>
        <p className="font-semibold text-white tracking-wide">No recipes synthesized yet</p>
        <p className="text-xs font-mono text-muted-foreground mt-1">
          Adjust ingredients or cosmic preferences above and click Generate Recipes
        </p>
      </div>
    );
  }

  const current = suggestions[currentIndex];
  if (!current) return null;

  const { recipe } = current;
  const displayScore = current.personalizedScore ?? current.score;
  const scorePercent = Math.round(displayScore * 100);

  const handleSave = (): void => {
    if (recipe.id) {
      saveRecipeToStore(recipe);
      logger.info(`Saved recipe to store: ${recipe.name}`);
    }
    setIsSaved(true);
    onSaveToQueue?.(current);
  };

  const handleAddToCart = (): void => {
    if (!groceryCart) return;
    const servings = recipe.numberOfServings ?? 2;
    const addedCount = groceryCart.addRecipe(
      {
        id: recipe.id || recipe.name.toLowerCase().replace(/\s+/g, "-"),
        name: recipe.name,
        baseServings: servings,
        ingredients: (recipe.ingredients || []).map((i) => ({
          name: i.name,
          amount: typeof i.amount === "number" ? i.amount : parseFloat(String(i.amount)) || 1,
          unit: i.unit || "",
        })),
      },
      servings,
    );
    setCartSuccessNotice(`Added ${addedCount} ingredients to grocery cart`);
    groceryCart.open();
  };

  return (
    <div className="space-y-4 relative px-0 md:px-2">
      {/* Header bar */}
      <div className="flex items-center justify-between px-1">
        <div className="flex items-center gap-2">
          <span className="text-xs font-mono tracking-wider uppercase text-muted-foreground">
            Alchemical Synthesis {currentIndex + 1} of {suggestions.length}
          </span>
          {isPersonalized && (
            <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full border border-purple-500/30 bg-purple-500/10 text-purple-300 text-[11px] font-mono">
              <Sparkles className="h-2.5 w-2.5 text-amber-300" />
              Personalized
            </span>
          )}
          {current.isPersonalized && current.personalizationBoost && current.personalizationBoost > 1.05 && (
            <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full border border-indigo-500/30 bg-indigo-500/10 text-indigo-300 text-[11px] font-mono">
              <Flame className="h-2.5 w-2.5 text-indigo-400" />
              Chart aligned
            </span>
          )}
        </div>
      </div>

      {/* Main card container with floating nav buttons */}
      <div className="relative group/carousel">
        {/* Floating Side Buttons (Desktop only) */}
        <button
          onClick={handlePrev}
          disabled={currentIndex === 0}
          className="hidden md:flex absolute left-[-20px] lg:left-[-24px] top-1/2 -translate-y-1/2 z-20 w-11 h-11 rounded-full bg-black/80 backdrop-blur-md shadow-xl border border-white/15 items-center justify-center text-purple-300 hover:bg-purple-600 hover:text-white transition-all duration-300 disabled:opacity-20 disabled:pointer-events-none hover:scale-105 active:scale-95"
          aria-label="Previous recipe"
        >
          <ChevronLeft className="w-5 h-5" />
        </button>

        <button
          onClick={handleNext}
          disabled={currentIndex === suggestions.length - 1}
          className="hidden md:flex absolute right-[-20px] lg:right-[-24px] top-1/2 -translate-y-1/2 z-20 w-11 h-11 rounded-full bg-black/80 backdrop-blur-md shadow-xl border border-white/15 items-center justify-center text-purple-300 hover:bg-purple-600 hover:text-white transition-all duration-300 disabled:opacity-20 disabled:pointer-events-none hover:scale-105 active:scale-95"
          aria-label="Next recipe"
        >
          <ChevronRight className="w-5 h-5" />
        </button>

        {/* Viewport container to crop sliding cards */}
        <div className="overflow-hidden p-1 -m-1">
          <AnimatePresence initial={false} custom={direction} mode="wait">
            <motion.div
              key={currentIndex}
              custom={direction}
              variants={cardVariants}
              initial="enter"
              animate="center"
              exit="exit"
              drag="x"
              dragConstraints={{ left: 0, right: 0 }}
              dragElastic={0.6}
              onDragEnd={handleDragEnd}
              style={{ x, rotate }}
              className="w-full select-none cursor-grab active:cursor-grabbing"
            >
              <div className="relative overflow-hidden rounded-2xl border border-white/15 bg-gradient-to-b from-black/80 via-black/70 to-purple-950/20 backdrop-blur-2xl shadow-[0_8px_32px_rgba(0,0,0,0.6)] transition-all">
                {/* Top aura line */}
                <div
                  className="h-1 w-full bg-gradient-to-r from-purple-500 via-indigo-500 to-amber-500"
                  aria-hidden
                />

                {/* Card header */}
                <div className="p-5 pb-3">
                  <div className="flex items-start justify-between gap-4 mb-2">
                    <div className="flex-1 min-w-0">
                      <h3 className="font-serif text-2xl font-bold text-white tracking-wide leading-tight">
                        {recipe.name}
                      </h3>
                      <div className="flex flex-wrap items-center gap-2 mt-2">
                        {recipe.cuisine && (
                          <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-lg border border-purple-500/30 bg-purple-500/10 text-purple-200 text-xs font-medium capitalize">
                            <Compass className="h-3 w-3 text-purple-400" />
                            {recipe.cuisine}
                          </span>
                        )}
                        {current.mealType && (
                          <span className="px-2.5 py-0.5 rounded-lg border border-amber-500/30 bg-amber-500/10 text-amber-200 text-xs font-medium capitalize">
                            {current.mealType}
                          </span>
                        )}
                        {recipe.prepTime && (
                          <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-lg border border-white/10 bg-white/5 text-gray-300 text-xs font-mono">
                            <Clock className="h-3 w-3 text-gray-400" />
                            {recipe.prepTime}
                          </span>
                        )}
                        {recipe.numberOfServings && (
                          <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-lg border border-white/10 bg-white/5 text-gray-300 text-xs font-mono">
                            <Users className="h-3 w-3 text-gray-400" />
                            {recipe.numberOfServings} servings
                          </span>
                        )}
                      </div>
                    </div>

                    {/* Score badge with celestial ring */}
                    <div className="shrink-0 text-center">
                      <div className="relative flex h-14 w-14 items-center justify-center rounded-2xl border border-purple-400/30 bg-gradient-to-br from-purple-600/40 via-indigo-600/40 to-amber-500/30 p-0.5 shadow-[0_0_20px_rgba(168,85,247,0.3)] backdrop-blur-md">
                        <div className="flex flex-col items-center justify-center">
                          <span className="text-lg font-bold text-white leading-none">
                            {scorePercent}%
                          </span>
                          <span className="text-[9px] font-mono uppercase tracking-wider text-purple-200/80">
                            match
                          </span>
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Description */}
                  {recipe.description && (
                    <p className="text-sm text-gray-300/90 line-clamp-2 mt-2 leading-relaxed">
                      {recipe.description}
                    </p>
                  )}
                </div>

                {/* Elemental profile */}
                {recipe.elementalProperties && (
                  <div className="px-5 pb-3">
                    <div className="text-[10px] font-mono uppercase tracking-wider text-muted-foreground mb-2">
                      Elemental Profile
                    </div>
                    <div className="grid grid-cols-4 gap-2.5">
                      {(["Fire", "Water", "Earth", "Air"] as const).map((el) => {
                        const val = recipe.elementalProperties[el];
                        const pct = Math.round(val * 100);
                        return (
                          <div key={el} className="space-y-1 rounded-xl border border-white/5 bg-white/5 p-2 backdrop-blur-sm">
                            <div className="flex items-center justify-between text-xs font-mono">
                              <span>{ELEMENT_ICONS[el]}</span>
                              <span className="text-gray-300">{pct}%</span>
                            </div>
                            <div className="h-1.5 bg-black/40 rounded-full overflow-hidden">
                              <div
                                className={`h-full rounded-full ${ELEMENT_BAR_COLORS[el]}`}
                                style={{ width: `${pct}%` }}
                              />
                            </div>
                            <div className="text-[10px] font-mono text-muted-foreground text-center">
                              {el}
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  </div>
                )}

                {/* Scores telemetry breakdown */}
                <div className="px-5 pb-3 flex flex-wrap gap-2">
                  <div className="px-2.5 py-1 rounded-xl border border-indigo-500/20 bg-indigo-500/10 text-center font-mono">
                    <div className="text-xs font-semibold text-indigo-300">
                      {Math.round(current.dayAlignment * 100)}%
                    </div>
                    <div className="text-[10px] text-muted-foreground">Day align</div>
                  </div>
                  <div className="px-2.5 py-1 rounded-xl border border-purple-500/20 bg-purple-500/10 text-center font-mono">
                    <div className="text-xs font-semibold text-purple-300">
                      {Math.round(current.planetaryAlignment * 100)}%
                    </div>
                    <div className="text-[10px] text-muted-foreground">Planetary</div>
                  </div>
                  {current.personalizationBoost && (
                    <div className="px-2.5 py-1 rounded-xl border border-pink-500/20 bg-pink-500/10 text-center font-mono">
                      <div className="text-xs font-semibold text-pink-300">
                        {current.personalizationBoost > 1
                          ? `+${Math.round((current.personalizationBoost - 1) * 100)}%`
                          : `${Math.round((current.personalizationBoost - 1) * 100)}%`}
                      </div>
                      <div className="text-[10px] text-muted-foreground">Chart boost</div>
                    </div>
                  )}
                  {typeof (recipe as { alchemicalProperties?: { monicaConstant?: number } }).alchemicalProperties?.monicaConstant === "number" && (
                    <div className="px-2.5 py-1 rounded-xl border border-amber-500/20 bg-amber-500/10 text-center font-mono">
                      <div className="text-xs font-semibold text-amber-300">
                        {((recipe as { alchemicalProperties: { monicaConstant: number } }).alchemicalProperties.monicaConstant).toFixed(2)}
                      </div>
                      <div className="text-[10px] text-muted-foreground">Monica</div>
                    </div>
                  )}
                </div>

                {/* Reasons / Cosmic synthesis notes */}
                {current.reasons.length > 0 && (
                  <div className="mx-5 mb-3 p-3.5 rounded-xl border border-purple-500/20 bg-purple-950/20 backdrop-blur-md">
                    <div className="text-xs font-mono uppercase tracking-wider text-purple-300 mb-2 flex items-center gap-1.5">
                      <Sparkles className="h-3 w-3 text-amber-300" />
                      Harmonic Alignment Rationale
                    </div>
                    <ul className="space-y-1">
                      {current.reasons.slice(0, 4).map((reason, i) => (
                        <li key={i} className="flex items-start gap-2 text-xs text-purple-200/90 leading-relaxed">
                          <span className="text-amber-400 mt-0.5">\u2726</span>
                          <span>{reason}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}

                {/* Key ingredients with Pantry detection */}
                {recipe.ingredients && recipe.ingredients.length > 0 && (
                  <div className="px-5 pb-3">
                    <button
                      onClick={() => toggleSection("ingredients")}
                      className="flex items-center justify-between w-full text-xs font-mono uppercase tracking-wider text-muted-foreground mb-2 hover:text-white transition-colors"
                    >
                      <span className="flex items-center gap-1.5">
                        Ingredients ({recipe.ingredients.length})
                      </span>
                      <span className="text-sm">
                        {expandedSections["ingredients"] ? (
                          <ChevronUp className="h-4 w-4" />
                        ) : (
                          <ChevronDown className="h-4 w-4" />
                        )}
                      </span>
                    </button>
                    <div className="flex flex-wrap gap-1.5">
                      {(expandedSections["ingredients"]
                        ? recipe.ingredients
                        : recipe.ingredients.slice(0, 8)
                      ).map((ing, idx) => {
                        const inPantry = hasItem(ing.name);
                        return (
                          <span
                            key={idx}
                            className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-xl text-xs font-medium border backdrop-blur-sm ${
                              inPantry
                                ? "border-emerald-500/40 bg-emerald-500/10 text-emerald-200"
                                : "border-white/10 bg-white/5 text-gray-300"
                            }`}
                          >
                            {inPantry && (
                              <PackageCheck className="h-3 w-3 text-emerald-400 shrink-0" />
                            )}
                            <span>
                              {ing.amount} {ing.unit} {ing.name}
                            </span>
                            {inPantry && (
                              <span className="text-[10px] font-mono text-emerald-400/90">
                                (pantry)
                              </span>
                            )}
                          </span>
                        );
                      })}
                      {!expandedSections["ingredients"] && recipe.ingredients.length > 8 && (
                        <button
                          onClick={() => toggleSection("ingredients")}
                          className="px-2.5 py-1 rounded-xl border border-purple-500/30 bg-purple-500/10 text-purple-300 text-xs font-mono hover:bg-purple-500/20 transition-colors"
                        >
                          +{recipe.ingredients.length - 8} more
                        </button>
                      )}
                    </div>
                  </div>
                )}

                {/* Instructions — expandable */}
                {recipe.instructions && recipe.instructions.length > 0 && (
                  <div className="px-5 pb-4">
                    <button
                      onClick={() => toggleSection("steps")}
                      className="flex items-center justify-between w-full text-xs font-mono uppercase tracking-wider text-muted-foreground mb-2 hover:text-white transition-colors"
                    >
                      <span>Culinary Steps ({recipe.instructions.length})</span>
                      <span className="text-sm">
                        {expandedSections["steps"] ? (
                          <ChevronUp className="h-4 w-4" />
                        ) : (
                          <ChevronDown className="h-4 w-4" />
                        )}
                      </span>
                    </button>
                    <ol className="space-y-2">
                      {(expandedSections["steps"]
                        ? recipe.instructions
                        : recipe.instructions.slice(0, 4)
                      ).map((step, idx) => (
                        <li key={idx} className="flex gap-2.5 text-xs text-gray-300 leading-relaxed">
                          <span className="shrink-0 w-5 h-5 rounded-lg border border-purple-400/30 bg-purple-500/20 text-purple-300 text-[11px] font-mono font-bold flex items-center justify-center mt-0.5">
                            {idx + 1}
                          </span>
                          <span>{step}</span>
                        </li>
                      ))}
                      {!expandedSections["steps"] && recipe.instructions.length > 4 && (
                        <li>
                          <button
                            onClick={() => toggleSection("steps")}
                            className="text-xs text-purple-400 pl-7 hover:text-purple-300 transition-colors font-mono"
                          >
                            + {recipe.instructions.length - 4} more steps
                          </button>
                        </li>
                      )}
                    </ol>
                  </div>
                )}

                {/* Seasonal adaptation notes */}
                {recipe.seasonalAdaptation &&
                  recipe.seasonalAdaptation.seasonalIngredientSubstitutions.length > 0 && (
                    <div className="mx-5 mb-3 p-3 rounded-xl border border-emerald-500/20 bg-emerald-950/20 backdrop-blur-md">
                      <div className="text-xs font-mono uppercase tracking-wider text-emerald-300 mb-1 flex items-center gap-1.5">
                        <span>\uD83C\uDF3F</span>
                        Seasonal Adaptations ({recipe.seasonalAdaptation.currentSeason})
                      </div>
                      {recipe.seasonalAdaptation.seasonalIngredientSubstitutions
                        .slice(0, 2)
                        .map((sub, i) => (
                          <p key={i} className="text-xs text-emerald-200/90 leading-relaxed">
                            Swap {sub.original} \u2192 {sub.seasonal} ({sub.reason})
                          </p>
                        ))}
                    </div>
                  )}

                {/* Cart success feedback */}
                {cartSuccessNotice && (
                  <div className="mx-5 mb-2 py-1.5 px-3 rounded-lg border border-emerald-500/40 bg-emerald-500/10 text-emerald-200 text-xs font-mono flex items-center gap-2">
                    <Check className="h-3.5 w-3.5 text-emerald-400" />
                    <span>{cartSuccessNotice}</span>
                  </div>
                )}

                {/* Action buttons */}
                <div className="px-5 pb-5 flex flex-wrap gap-2.5 border-t border-white/10 pt-4">
                  <button
                    onClick={handleSave}
                    className={`flex-1 inline-flex items-center justify-center gap-2 py-3 px-4 rounded-xl text-xs font-semibold transition-all ${
                      isSaved
                        ? "border border-emerald-500/40 bg-emerald-500/20 text-emerald-300"
                        : "bg-gradient-to-r from-purple-600 to-indigo-600 text-white hover:from-purple-500 hover:to-indigo-500 shadow-lg shadow-purple-600/25 active:scale-[0.98]"
                    }`}
                  >
                    {isSaved ? (
                      <>
                        <Check className="h-4 w-4 text-emerald-400" />
                        <span>Recipe Saved</span>
                      </>
                    ) : (
                      <>
                        <Bookmark className="h-4 w-4" />
                        <span>Save Recipe</span>
                      </>
                    )}
                  </button>

                  {groceryCart && (
                    <button
                      onClick={handleAddToCart}
                      className="inline-flex items-center justify-center gap-2 py-3 px-4 rounded-xl text-xs font-semibold border border-amber-500/40 bg-amber-500/10 text-amber-200 hover:bg-amber-500/20 hover:border-amber-500/60 transition-all active:scale-[0.98]"
                      title="Add missing ingredients to your grocery cart"
                    >
                      <ShoppingBag className="h-4 w-4 text-amber-400" />
                      <span>Add to Cart</span>
                    </button>
                  )}

                  {recipe.id && (
                    <Link
                      href={`/generated-recipe/${recipe.id}`}
                      className="inline-flex items-center justify-center gap-1.5 px-4 py-3 rounded-xl text-xs font-mono font-medium border border-white/15 bg-white/5 text-gray-300 hover:bg-white/10 hover:text-white transition-all"
                    >
                      <span>Full Recipe</span>
                      <ExternalLink className="h-3.5 w-3.5 text-muted-foreground" />
                    </Link>
                  )}
                </div>
              </div>
            </motion.div>
          </AnimatePresence>
        </div>
      </div>

      {/* Pagination indicators */}
      <div className="flex justify-center items-center gap-2 py-2">
        {suggestions.map((_, idx) => (
          <button
            key={idx}
            onClick={() => onIndexChange(idx)}
            className={`rounded-full transition-all duration-300 ${
              idx === currentIndex
                ? "w-7 h-2 bg-gradient-to-r from-purple-400 to-amber-400 shadow-[0_0_10px_rgba(168,85,247,0.7)]"
                : "w-2 h-2 bg-white/20 hover:bg-white/40"
            }`}
            aria-label={`Go to recipe ${idx + 1}`}
          />
        ))}
      </div>

      {/* Navigation hint */}
      <p className="text-center text-[11px] font-mono text-muted-foreground select-none">
        Swipe or use arrows to examine {suggestions.length} celestial syntheses
      </p>
    </div>
  );
}

