version: '3.8'

services:
  # Development service
  whattoeatnext-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - CHOKIDAR_USEPOLLING=true
    volumes:
      # Mount source code for hot reload (development only)
      - ../src:/app/src:ro
      - ../public:/app/public:ro
      - ../next.config.js:/app/next.config.js:ro
      - ../package.json:/app/package.json:ro
    networks:
      - whattoeatnext-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Production service
  whattoeatnext-prod:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
    networks:
      - whattoeatnext-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  whattoeatnext-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  # Optional: Add persistent volumes if needed
  # app-data:
  #   driver: local 