//! Transactional reducers for the culinary data engine.
//!
//! Every reducer runs in a single SpacetimeDB transaction: if it returns `Err`
//! (or panics), *all* table writes it performed are rolled back atomically.
//! That is what makes the fail-closed checks below safe — we validate first and
//! only commit once every precondition holds.

use spacetimedb::{ReducerContext, Table};

// Glob import brings both the row structs *and* the per-table accessor traits
// (e.g. the `ingredient` trait that provides `ctx.db.ingredient()`) into scope.
// Those traits are generated by `#[spacetimedb::table(accessor = ...)]`.
use crate::tables::*;
use crate::words::{self, NutrientLine};

/// Generous upper bounds on free-text fields, to stop a single call from
/// storing multi-megabyte blobs. Real culinary names/instructions are far
/// smaller; these only reject abuse.
const NAME_MAX_LEN: usize = 256;
const INSTRUCTIONS_MAX_LEN: usize = 16_384;

/// Module init hook (no seeding required yet).
#[spacetimedb::reducer(init)]
pub fn init(_ctx: &ReducerContext) {
    log::info!("alchm_culinary module initialized");
}

/// Insert a new raw ingredient.
//
// The wide argument list is the spec-defined reducer signature — reducer
// arguments are the client-facing call surface, so we keep them flat rather
// than wrapping them in a struct.
#[allow(clippy::too_many_arguments)]
#[spacetimedb::reducer]
pub fn add_ingredient(
    ctx: &ReducerContext,
    name: String,
    elemental_signature: ElementalSignature,
    primary_element: u8,
    calories: u32,
    protein_g: f32,
    fat_g: f32,
    carbs_g: f32,
) -> Result<(), String> {
    if name.trim().is_empty() {
        return Err("ingredient name must not be empty".to_string());
    }
    if name.len() > NAME_MAX_LEN {
        return Err(format!("ingredient name must be <= {NAME_MAX_LEN} bytes"));
    }
    if (primary_element as usize) >= words::ELEMENT_COUNT {
        return Err(format!(
            "primary_element must be 0..{} (0=Fire, 1=Earth, 2=Air, 3=Water)",
            words::ELEMENT_COUNT
        ));
    }
    // ESMS components may be any finite real (including negative — an
    // anti-affinity); only NaN/Inf are rejected. Without this, a non-finite
    // signature would silently poison every recipe/cuisine that uses it.
    if !elemental_signature.spirit.is_finite()
        || !elemental_signature.essence.is_finite()
        || !elemental_signature.matter.is_finite()
        || !elemental_signature.substance.is_finite()
    {
        return Err("elemental_signature components must be finite numbers".to_string());
    }
    // Nutrients are physical quantities: finite and non-negative.
    if !protein_g.is_finite() || !fat_g.is_finite() || !carbs_g.is_finite() {
        return Err("protein_g, fat_g, and carbs_g must be finite numbers".to_string());
    }
    if protein_g < 0.0 || fat_g < 0.0 || carbs_g < 0.0 {
        return Err("protein_g, fat_g, and carbs_g must be non-negative".to_string());
    }

    ctx.db
        .ingredient()
        .try_insert(Ingredient {
            ingredient_id: 0,
            name,
            elemental_signature,
            primary_element,
            calories,
            protein_g,
            fat_g,
            carbs_g,
        })
        .map_err(|e| e.to_string())?;
    Ok(())
}

/// Create a cuisine with an empty profile. Companion to
/// [`associate_recipe_to_cuisine`] (you must create a cuisine before linking
/// recipes to it). The profile fills in as recipes are associated.
#[spacetimedb::reducer]
pub fn add_cuisine(ctx: &ReducerContext, name: String) -> Result<(), String> {
    if name.trim().is_empty() {
        return Err("cuisine name must not be empty".to_string());
    }
    if name.len() > NAME_MAX_LEN {
        return Err(format!("cuisine name must be <= {NAME_MAX_LEN} bytes"));
    }
    ctx.db
        .cuisine()
        .try_insert(Cuisine {
            cuisine_id: 0,
            name,
            elemental_profile: ElementalSignature::ZERO,
            primary_element: 0,
        })
        .map_err(|e| e.to_string())?;
    Ok(())
}

/// Create a recipe and its ingredient lines in a single atomic transaction.
///
/// Steps:
/// 1. Validate the recipe metadata and every ingredient line up front.
/// 2. Resolve each `ingredient_id` against the `ingredient` table — **fail
///    closed**: if any is missing, return `Err` before writing anything, so
///    the transaction rolls back with no partial recipe/join rows.
/// 3. Aggregate signatures and nutrients (weighted by `amount`) via the pure
///    logic in [`crate::words`].
/// 4. Insert the computed `recipe` row, then the `recipe_ingredient` join rows.
#[spacetimedb::reducer]
pub fn create_recipe(
    ctx: &ReducerContext,
    name: String,
    instructions: String,
    ingredients: Vec<RecipeIngredientInput>,
) -> Result<(), String> {
    if name.trim().is_empty() {
        return Err("recipe name must not be empty".to_string());
    }
    if name.len() > NAME_MAX_LEN {
        return Err(format!("recipe name must be <= {NAME_MAX_LEN} bytes"));
    }
    if instructions.len() > INSTRUCTIONS_MAX_LEN {
        return Err(format!(
            "recipe instructions must be <= {INSTRUCTIONS_MAX_LEN} bytes"
        ));
    }
    if ingredients.is_empty() {
        return Err("recipe must reference at least one ingredient".to_string());
    }

    // Steps 1 + 2: validate and resolve every ingredient before any write.
    let mut lines: Vec<NutrientLine> = Vec::with_capacity(ingredients.len());
    for input in &ingredients {
        if !input.amount.is_finite() || input.amount <= 0.0 {
            return Err(format!(
                "amount for ingredient {} must be a positive, finite number",
                input.ingredient_id
            ));
        }
        let ingredient = ctx
            .db
            .ingredient()
            .ingredient_id()
            .find(input.ingredient_id)
            .ok_or_else(|| format!("ingredient {} does not exist", input.ingredient_id))?;

        lines.push(NutrientLine {
            signature: ingredient.elemental_signature.to_array(),
            primary_element: ingredient.primary_element,
            calories: ingredient.calories,
            protein_g: ingredient.protein_g,
            fat_g: ingredient.fat_g,
            carbs_g: ingredient.carbs_g,
            amount: input.amount,
        });
    }

    // Step 3: pure aggregation.
    let agg = words::aggregate_recipe(&lines);

    // Step 4: write the recipe, then the join rows referencing its new id.
    let recipe = ctx
        .db
        .recipe()
        .try_insert(Recipe {
            recipe_id: 0,
            name,
            instructions,
            elemental_signature: ElementalSignature::from_array(agg.signature),
            primary_element: agg.primary_element,
            total_calories: agg.total_calories,
            total_protein: agg.total_protein,
            total_fat: agg.total_fat,
            total_carbs: agg.total_carbs,
        })
        .map_err(|e| e.to_string())?;

    for input in ingredients {
        ctx.db
            .recipe_ingredient()
            .try_insert(RecipeIngredient {
                row_id: 0,
                recipe_id: recipe.recipe_id,
                ingredient_id: input.ingredient_id,
                amount: input.amount,
                unit: input.unit,
            })
            .map_err(|e| e.to_string())?;
    }

    Ok(())
}

/// Link a recipe to a cuisine and recompute the cuisine's aggregated profile.
///
/// Fails closed if either id is missing or the pair is already linked, so a
/// failed association never partially writes or double-counts a recipe.
#[spacetimedb::reducer]
pub fn associate_recipe_to_cuisine(
    ctx: &ReducerContext,
    cuisine_id: u64,
    recipe_id: u64,
) -> Result<(), String> {
    if ctx.db.cuisine().cuisine_id().find(cuisine_id).is_none() {
        return Err(format!("cuisine {cuisine_id} does not exist"));
    }
    if ctx.db.recipe().recipe_id().find(recipe_id).is_none() {
        return Err(format!("recipe {recipe_id} does not exist"));
    }

    let already_linked = ctx
        .db
        .cuisine_recipe()
        .cuisine_id()
        .filter(cuisine_id)
        .any(|cr| cr.recipe_id == recipe_id);
    if already_linked {
        return Err(format!(
            "recipe {recipe_id} is already associated with cuisine {cuisine_id}"
        ));
    }

    ctx.db
        .cuisine_recipe()
        .try_insert(CuisineRecipe {
            row_id: 0,
            cuisine_id,
            recipe_id,
        })
        .map_err(|e| e.to_string())?;

    recalc_cuisine_profile(ctx, cuisine_id);
    Ok(())
}

/// Recompute a cuisine's `elemental_profile` (mean of member recipe
/// signatures) and `primary_element` (majority vote over member recipes).
fn recalc_cuisine_profile(ctx: &ReducerContext, cuisine_id: u64) {
    let recipe_ids: Vec<u64> = ctx
        .db
        .cuisine_recipe()
        .cuisine_id()
        .filter(cuisine_id)
        .map(|cr| cr.recipe_id)
        .collect();

    let mut signatures = Vec::with_capacity(recipe_ids.len());
    let mut elements = Vec::with_capacity(recipe_ids.len());
    for recipe_id in recipe_ids {
        if let Some(recipe) = ctx.db.recipe().recipe_id().find(recipe_id) {
            signatures.push(recipe.elemental_signature.to_array());
            elements.push(recipe.primary_element);
        }
    }

    let elemental_profile = ElementalSignature::from_array(words::average_signatures(&signatures));
    let primary_element = words::dominant_element_unweighted(&elements);

    if let Some(existing) = ctx.db.cuisine().cuisine_id().find(cuisine_id) {
        ctx.db.cuisine().cuisine_id().update(Cuisine {
            elemental_profile,
            primary_element,
            ..existing
        });
    }
}
