/**
 * WebAssembly thermodynamics engine — loader, and the fallback that replaces it.
 *
 * The canvas in `OvenConvectionCanvas.tsx` runs a 60 FPS convection simulation.
 * That simulation is defined once, in Rust, at `crates/thermo-core`. This file
 * gives the browser two ways to execute it:
 *
 *   1. The compiled WASM module (`crates/thermo-wasm`), when it loads.
 *   2. {@link FallbackThermoEngine}, a transliteration of the same Rust,
 *      when it does not — server rendering, an offline Tauri window, a
 *      failed fetch, or a browser that declines the module.
 *
 * ── Why the fallback is transliterated rather than merely "equivalent" ──────
 *
 * `[MEASURED 2026-08-16]` Before this file existed, the Rust simulation and the
 * canvas's own TypeScript loop were two independently written models wearing
 * the same name. They disagreed on both constants that matter: buoyancy
 * 0.0005·ΔT against 0.003·ΔT (6× apart — 0.0775 vs 0.465 at a 175 °C oven) and
 * swirl amplitude 0.5 against 0.4. Since the browser silently falls back
 * whenever WASM is unavailable, "graceful degradation" meant rendering a
 * visibly different simulation with nothing anywhere to say so.
 *
 * So the fallback is a line-by-line transliteration, and it is held to that by
 * `src/__tests__/cookingThermoCrossRuntimeParity.test.ts`, which replays a
 * golden trace generated by the Rust and asserts this code reproduces it.
 *
 * ── f32 discipline ──────────────────────────────────────────────────────────
 *
 * The Rust simulation is `f32` throughout; JavaScript numbers are `f64`. Every
 * arithmetic step below is therefore wrapped in `Math.fround`, in the same
 * association order as the Rust. Dropping a single `fround` does not produce a
 * visible bug — it produces a slow divergence that only the golden trace
 * catches.
 */

import type { MethodPhysicsMetrics } from "@/lib/cooking/methodMetrics";

/** f32 narrowing. Aliased because it appears on nearly every line below. */
const f = Math.fround;

/**
 * Simulation constants. These MUST equal `thermo_core::{BUOYANCY_PER_K,
 * SWIRL_AMPLITUDE, CONVECTION_DRAG}` and are asserted against the golden
 * fixture, which carries the Rust f32 values widened to f64.
 */
export const BUOYANCY_PER_K = f(0.003);
export const SWIRL_AMPLITUDE = f(0.4);
export const CONVECTION_DRAG = f(0.98);

/** Floats per particle: `[x, y, z, vx, vy, vz, tempC, radiantIntensity]`. */
export const FLOATS_PER_PARTICLE = 8;

/** Longest delta a single step will integrate, seconds. */
const MAX_STEP_S = 0.05;

/** Matches `MAX_PARTICLES` in `crates/thermo-wasm/src/lib.rs`. */
const MAX_PARTICLES = 4096;

/**
 * What the canvas talks to. Both the WASM engine and the fallback satisfy it,
 * so the render loop never branches on which one it got.
 */
export interface ThermoEngineHandle {
  /** Advance by `dtS` seconds. */
  step(dtS: number, ovenTempC: number, hWm2K: number, radiantSourceK: number): void;
  /** Current particle state, `FLOATS_PER_PARTICLE` floats per particle. */
  view(): Float32Array;
  readonly particleCount: number;
  /** What is actually executing — rendered to the user, so it must be true. */
  readonly engine: "wasm" | "typescript";
  dispose(): void;
}

/**
 * The deterministic particle seed, transliterated from
 * `thermo_core::seeded_particles`.
 *
 * Closed form in the index, no RNG. That is what makes a cross-runtime trace
 * comparison possible at all.
 */
export function seedParticles(n: number): Float32Array {
  const buffer = new Float32Array(n * FLOATS_PER_PARTICLE);
  for (let i = 0; i < n; i += 1) {
    const fi = f(i);
    const o = i * FLOATS_PER_PARTICLE;
    buffer[o] = f(f(f(fi * f(0.37)) % 2) - 1);
    buffer[o + 1] = f(f(fi * f(0.191)) % 1);
    buffer[o + 2] = f(f(f(fi * f(0.53)) % 2) - 1);
    buffer[o + 3] = 0;
    buffer[o + 4] = 0;
    buffer[o + 5] = 0;
    buffer[o + 6] = f(20 + f(f(fi * f(0.7)) % 50));
    buffer[o + 7] = 0;
  }
  return buffer;
}

/**
 * One simulation step, transliterated from `thermo_core::step_oven_simulation`.
 *
 * Operates in place on a flat `Float32Array`. The association order of every
 * expression follows the Rust exactly; `a * b * c` is `(a * b) * c` in both
 * languages, and each intermediate is narrowed to f32 because the Rust
 * intermediates are f32.
 */
export function stepOvenSimulation(
  buffer: Float32Array,
  dtS: number,
  ovenTempC: number,
  hWm2K: number,
  radiantSourceK: number,
): void {
  const dt = f(dtS);
  const buoyancy = f(Math.max(0, f(f(ovenTempC) - 20)) * BUOYANCY_PER_K);
  const hRate = f(f(hWm2K) * f(0.001));

  // r⁴ is constant across particles, exactly as in the Rust.
  const r = f(f(radiantSourceK) / 1000);
  const quartic = f(f(f(f(r * r) * r) * r) * f(0.25));
  const radiantIntensity = quartic < 1 ? quartic : 1;

  const count = buffer.length / FLOATS_PER_PARTICLE;
  for (let i = 0; i < count; i += 1) {
    const o = i * FLOATS_PER_PARTICLE;
    let x = buffer[o];
    let y = buffer[o + 1];
    let z = buffer[o + 2];
    let vx = buffer[o + 3];
    let vy = buffer[o + 4];
    let vz = buffer[o + 5];
    let tempC = buffer[o + 6];

    const phase = f(f(f(x * 2) + f(z * 3)) + f(f(i) * f(0.1)));
    // `sin_f32` in the Rust is `(x as f64).sin() as f32` — the transcendental
    // is evaluated in double precision and only then narrowed.
    const swirlX = f(f(Math.sin(phase)) * SWIRL_AMPLITUDE);
    const swirlZ = f(f(Math.cos(phase)) * SWIRL_AMPLITUDE);

    vx = f(f(vx + f(swirlX * dt)) * CONVECTION_DRAG);
    vy = f(f(vy + f(buoyancy * dt)) * CONVECTION_DRAG);
    vz = f(f(vz + f(swirlZ * dt)) * CONVECTION_DRAG);

    x = f(x + f(vx * dt));
    y = f(y + f(vy * dt));
    z = f(z + f(vz * dt));

    // Wrap into the 1×1×1 render box.
    if (y > 1) y = 0;
    if (x < -1) x = 1;
    if (x > 1) x = -1;
    if (z < -1) z = 1;
    if (z > 1) z = -1;

    // Newton cooling toward the medium, paced by the method's own h.
    tempC = f(tempC + f(f(f(ovenTempC - tempC) * hRate) * dt));

    buffer[o] = x;
    buffer[o + 1] = y;
    buffer[o + 2] = z;
    buffer[o + 3] = vx;
    buffer[o + 4] = vy;
    buffer[o + 5] = vz;
    buffer[o + 6] = tempC;
    buffer[o + 7] = radiantIntensity;
  }
}

/** The pure-TypeScript engine. Correct everywhere, just slower than WASM. */
export class FallbackThermoEngine implements ThermoEngineHandle {
  readonly engine = "typescript" as const;

  private readonly buffer: Float32Array;

  constructor(count: number) {
    const n = Math.min(Math.max(Math.trunc(count) || 1, 1), MAX_PARTICLES);
    this.buffer = seedParticles(n);
  }

  get particleCount(): number {
    return this.buffer.length / FLOATS_PER_PARTICLE;
  }

  step(dtS: number, ovenTempC: number, hWm2K: number, radiantSourceK: number): void {
    // Same clamp as the WASM engine. A backgrounded tab hands back a delta of
    // whole seconds when it wakes; integrating that in one step throws every
    // particle out of the box at once, which reads as the canvas resetting
    // itself whenever the user comes back to the page.
    const dt = Math.min(Math.max(dtS, 0), MAX_STEP_S);
    stepOvenSimulation(this.buffer, dt, ovenTempC, hWm2K, radiantSourceK);
  }

  view(): Float32Array {
    return this.buffer;
  }

  dispose(): void {
    /* nothing to release */
  }
}

// ============================================================================
// WASM loading
// ============================================================================

/**
 * URL the wasm-bindgen bundle is served from.
 *
 * ⚠️ AN ABSOLUTE URL, NOT A MODULE SPECIFIER, and the difference is the whole
 * reason this constant has a comment. `[MEASURED 2026-08-16]` the first version
 * of this loader used `@/lib/wasm/generated/thermo_wasm.js` with
 * `webpackIgnore: true`. Those two cancel out: `webpackIgnore` hands the
 * specifier to the browser untouched, and the browser has never heard of the
 * `@/` alias. Every load failed with
 *
 *     TypeError: Failed to resolve module specifier '@/lib/wasm/generated/...'
 *
 * which the `catch` below swallowed into the fallback — so the canvas ran
 * TypeScript forever, in a build where the WASM module had been compiled,
 * verified and shipped. Nothing anywhere reported a problem.
 *
 * A path under `public/` is fetchable at runtime, so the browser can resolve
 * it, and when it has not been built the failure is an honest 404.
 */
const WASM_MODULE_URL = "/wasm/thermo_wasm.js";

/**
 * Shape of the wasm-bindgen `--target web` output we depend on.
 *
 * Declared structurally rather than imported, because the generated module is
 * gitignored: it is a build product of `bun run build:wasm`, and a checkout
 * that has not run that step must still typecheck and still render.
 */
interface ThermoWasmModule {
  default: (input?: unknown) => Promise<{ memory: WebAssembly.Memory }>;
  ThermoEngine: new (count: number) => {
    step(dtS: number, ovenTempC: number, hWm2K: number, radiantSourceK: number): void;
    readonly buffer_ptr: number;
    readonly buffer_len: number;
    readonly particle_count: number;
    free(): void;
  };
  floats_per_particle: () => number;
}

class WasmThermoEngine implements ThermoEngineHandle {
  readonly engine = "wasm" as const;

  constructor(
    private readonly inner: InstanceType<ThermoWasmModule["ThermoEngine"]>,
    private readonly memory: WebAssembly.Memory,
  ) {}

  get particleCount(): number {
    return this.inner.particle_count;
  }

  step(dtS: number, ovenTempC: number, hWm2K: number, radiantSourceK: number): void {
    this.inner.step(dtS, ovenTempC, hWm2K, radiantSourceK);
  }

  view(): Float32Array {
    // Reconstructed every frame ON PURPOSE. Any allocation inside the module
    // can grow linear memory, and growing it detaches every existing
    // ArrayBuffer view — a cached view would silently start reading a
    // zero-length buffer, which renders as a canvas that simply stops.
    return new Float32Array(this.memory.buffer, this.inner.buffer_ptr, this.inner.buffer_len);
  }

  dispose(): void {
    this.inner.free();
  }
}

let modulePromise: Promise<ThermoWasmModule | null> | null = null;

/**
 * Load the WASM module once per page, or resolve null if it is unavailable.
 *
 * Never throws. Every failure path — no `WebAssembly` global, module not built,
 * fetch blocked, instantiation rejected — resolves to null so the caller takes
 * the fallback. A physics canvas is not worth a runtime error.
 */
async function loadModule(): Promise<ThermoWasmModule | null> {
  if (typeof WebAssembly === "undefined") return null;
  if (modulePromise) return modulePromise;

  modulePromise = (async () => {
    try {
      // Probe before importing. A missing bundle is the NORMAL state of a
      // checkout that has not run `bun run build:wasm`, and Next's dev overlay
      // surfaces a failed dynamic import as an error toast even when it is
      // caught. A 404 here is quiet and equally conclusive.
      const probe = await fetch(WASM_MODULE_URL, { method: "HEAD" });
      if (!probe.ok) return null;

      // `webpackIgnore` keeps the bundler from trying to resolve this at build
      // time — it cannot, the file may not exist yet — and leaves the browser
      // to fetch the URL, which it can.
      const mod = (await import(/* webpackIgnore: true */ WASM_MODULE_URL)) as unknown as ThermoWasmModule;
      if (typeof mod?.default !== "function" || typeof mod?.ThermoEngine !== "function") {
        return null;
      }
      return mod;
    } catch {
      return null;
    }
  })();

  return modulePromise;
}

/**
 * Create the best available engine for `count` particles.
 *
 * Resolves to a WASM engine where possible and a TypeScript one otherwise. The
 * caller reads `.engine` to label the panel — and that label must be whatever
 * actually ran, never a hopeful constant.
 */
export async function createThermoEngine(count: number): Promise<ThermoEngineHandle> {
  const mod = await loadModule();
  if (!mod) return new FallbackThermoEngine(count);

  try {
    const instance = await mod.default();
    // If the module and this file ever disagree about the buffer layout, every
    // particle would be read from the wrong offset — a scrambled canvas with
    // no error. Cheaper to check once than to debug once.
    if (mod.floats_per_particle() !== FLOATS_PER_PARTICLE) return new FallbackThermoEngine(count);
    const engine = new mod.ThermoEngine(count);
    return new WasmThermoEngine(engine, instance.memory);
  } catch {
    return new FallbackThermoEngine(count);
  }
}

/**
 * Pull the simulation's driving parameters out of a method's physics metrics.
 *
 * Defaults are the roasting profile, used only when a method carries no `h` at
 * all — the mass-transfer and microbial methods, where a convection animation
 * is decorative rather than descriptive.
 */
export function simulationInputs(metrics: MethodPhysicsMetrics): {
  ovenTempC: number;
  hWm2K: number;
  radiantSourceK: number;
} {
  return {
    ovenTempC: metrics.medium.celsius,
    hWm2K: metrics.transfer?.typical ?? 25,
    radiantSourceK: metrics.physics.radiantSourceK ?? 505,
  };
}
