/**
 * WebAssembly thermodynamics engine — loader, and the fallback that replaces it.
 *
 * The canvas in `OvenConvectionCanvas.tsx` runs a 60 FPS convection simulation.
 * That simulation is defined once, in Rust, at `crates/thermo-core`. This file
 * gives the browser two ways to execute it:
 *
 *   1. The compiled WASM module (`crates/thermo-wasm`), when it loads.
 *   2. {@link FallbackThermoEngine}, a transliteration of the same Rust,
 *      when it does not — server rendering, an offline Tauri window, a
 *      failed fetch, or a browser that declines the module.
 *
 * ── Why the fallback is transliterated rather than merely "equivalent" ──────
 *
 * `[MEASURED 2026-08-16]` Before this file existed, the Rust simulation and the
 * canvas's own TypeScript loop were two independently written models wearing
 * the same name. They disagreed on both constants that matter: buoyancy
 * 0.0005·ΔT against 0.003·ΔT (6× apart — 0.0775 vs 0.465 at a 175 °C oven) and
 * swirl amplitude 0.5 against 0.4. Since the browser silently falls back
 * whenever WASM is unavailable, "graceful degradation" meant rendering a
 * visibly different simulation with nothing anywhere to say so.
 *
 * So the fallback is a line-by-line transliteration, and it is held to that by
 * `src/__tests__/cookingThermoCrossRuntimeParity.test.ts`, which replays a
 * golden trace generated by the Rust and asserts this code reproduces it.
 *
 * ── f32 discipline ──────────────────────────────────────────────────────────
 *
 * The Rust simulation is `f32` throughout; JavaScript numbers are `f64`. Every
 * arithmetic step below is therefore wrapped in `Math.fround`, in the same
 * association order as the Rust. Dropping a single `fround` does not produce a
 * visible bug — it produces a slow divergence that only the golden trace
 * catches.
 */

import type { MethodPhysicsProfile } from "@/data/cooking/methodPhysics";
import type {
  BoundaryLink,
  BoundaryNetworkInput,
  BoundaryNetworkResult,
} from "@/lib/cooking/boundaryNetwork";
import type { MethodPhysicsMetrics } from "@/lib/cooking/methodMetrics";

/** f32 narrowing. Aliased because it appears on nearly every line below. */
const f = Math.fround;

/**
 * Simulation constants. These MUST equal `thermo_core::{BUOYANCY_PER_K,
 * SWIRL_AMPLITUDE, CONVECTION_DRAG}` and are asserted against the golden
 * fixture, which carries the Rust f32 values widened to f64.
 */
export const BUOYANCY_PER_K = f(0.003);
export const SWIRL_AMPLITUDE = f(0.4);
export const CONVECTION_DRAG = f(0.98);

/** Room temperature, the reference the buoyant ΔT is taken against, °C. */
export const RENDER_AMBIENT_C = f(20);

/** Extra velocity a phase-change tracer carries along its transition direction. */
export const VAPOUR_TRANSIT = f(0.55);

/**
 * Floats per particle:
 * `[x, y, z, vx, vy, vz, tempC, radiantIntensity, phaseFrac]`.
 */
export const FLOATS_PER_PARTICLE = 9;

/**
 * How a medium actually moves heat. Mirrors `thermo_core::HeatRegime`, and the
 * numeric values ARE the wire format — they cross into WASM as a `u8`.
 *
 * `[MEASURED 2026-08-17]` Before this existed the canvas ran one motion model
 * for all 26 methods, so `boiling` was drawn as a dry oven with a glowing
 * element, and `cryo_cooking` at −196 °C was drawn as a hot amber chamber with
 * perfectly still air (the old buoyancy clamped negative superheat to zero).
 * The data to tell them apart was already in `methodPhysics.ts` and none of it
 * reached the simulation.
 */
export const HeatRegime = {
  BuoyantAir: 0,
  Oil: 1,
  RollingBoil: 2,
  CondensingSteam: 3,
  StillLiquid: 4,
  Radiant: 5,
  SolidContact: 6,
  Cryogenic: 7,
  Diffusion: 8,
  Distillation: 9,
} as const;

export type HeatRegime = (typeof HeatRegime)[keyof typeof HeatRegime];

/** Motion parameters for one regime. Mirrors `thermo_core::RegimeParams`. */
export interface RegimeParams {
  buoyancyPerK: number;
  swirl: number;
  drag: number;
  nucleationPerS: number;
  nucleationDir: number;
  coolingSign: number;
}

// ── Volumetric thermal expansion, K⁻¹ ───────────────────────────────────────
// Mirrors `thermo_core::{BETA_AIR_OVEN, BETA_WATER_HOT, BETA_OIL, BETA_LN2}`.
// BASIS is stated once, in the Rust; duplicating the citations here would be a
// second place for them to rot.
const BETA_AIR_OVEN = f(f(1) / f(450));
const BETA_WATER_HOT = f(697.9e-6);
const BETA_OIL = f(7.0e-4);
const BETA_LN2 = f(5.7e-3);

/** Standard gravity as the ISA block fixes it, narrowed to f32. */
const G_M_S2 = f(9.80665);

/**
 * Render-box units per metre. DEFINED so `buoyancyForBeta(BETA_AIR_OVEN)`
 * reproduces {@link BUOYANCY_PER_K} exactly — asserted in the parity test, and
 * in `thermo_core`'s own `derived_air_buoyancy_reproduces_the_shipped_constant`.
 */
const SCENE_SCALE = f(BUOYANCY_PER_K / f(G_M_S2 * BETA_AIR_OVEN));

/** Buoyant acceleration per kelvin for a fluid of expansion coefficient β. */
export function buoyancyForBeta(betaPerK: number): number {
  return f(f(G_M_S2 * betaPerK) * SCENE_SCALE);
}

/**
 * Motion parameters per regime. Transliterated from `thermo_core::regime_params`
 * and pinned value-for-value by the golden fixture's `simulation.regimes` block.
 */
export function regimeParams(regime: HeatRegime): RegimeParams {
  switch (regime) {
    case HeatRegime.BuoyantAir:
      return {
        buoyancyPerK: BUOYANCY_PER_K,
        swirl: SWIRL_AMPLITUDE,
        drag: CONVECTION_DRAG,
        nucleationPerS: 0,
        nucleationDir: 0,
        coolingSign: 1,
      };
    case HeatRegime.Oil:
      return {
        buoyancyPerK: buoyancyForBeta(BETA_OIL),
        swirl: f(0.22),
        drag: f(0.94),
        nucleationPerS: f(1.6),
        nucleationDir: 1,
        coolingSign: 1,
      };
    case HeatRegime.RollingBoil:
      return {
        buoyancyPerK: buoyancyForBeta(BETA_WATER_HOT),
        swirl: f(0.3),
        drag: f(0.965),
        nucleationPerS: f(3.2),
        nucleationDir: 1,
        coolingSign: 1,
      };
    case HeatRegime.CondensingSteam:
      return {
        buoyancyPerK: f(buoyancyForBeta(BETA_WATER_HOT) * f(0.5)),
        swirl: f(0.16),
        drag: f(0.97),
        nucleationPerS: f(2.4),
        nucleationDir: -1,
        coolingSign: 1,
      };
    case HeatRegime.StillLiquid:
      return {
        buoyancyPerK: buoyancyForBeta(BETA_WATER_HOT),
        swirl: f(0.09),
        drag: f(0.95),
        nucleationPerS: 0,
        nucleationDir: 0,
        coolingSign: 1,
      };
    case HeatRegime.Radiant:
      return {
        buoyancyPerK: f(buoyancyForBeta(BETA_AIR_OVEN) * f(0.6)),
        swirl: f(0.12),
        drag: f(0.96),
        nucleationPerS: 0,
        nucleationDir: 0,
        coolingSign: 1,
      };
    case HeatRegime.SolidContact:
      return {
        buoyancyPerK: f(buoyancyForBeta(BETA_AIR_OVEN) * f(0.25)),
        swirl: f(0.06),
        drag: f(0.93),
        nucleationPerS: f(0.5),
        nucleationDir: 1,
        coolingSign: 1,
      };
    case HeatRegime.Cryogenic:
      return {
        buoyancyPerK: buoyancyForBeta(BETA_LN2),
        swirl: f(0.14),
        drag: f(0.985),
        nucleationPerS: f(2),
        nucleationDir: 1,
        coolingSign: -1,
      };
    case HeatRegime.Diffusion:
      return {
        buoyancyPerK: 0,
        swirl: f(0.05),
        drag: f(0.992),
        nucleationPerS: 0,
        nucleationDir: 0,
        coolingSign: 0,
      };
    case HeatRegime.Distillation:
      return {
        buoyancyPerK: f(buoyancyForBeta(BETA_WATER_HOT) * f(0.8)),
        swirl: f(0.1),
        drag: f(0.972),
        nucleationPerS: f(2.8),
        nucleationDir: 1,
        coolingSign: 1,
      };
  }
}

/** Longest delta a single step will integrate, seconds. */
const MAX_STEP_S = 0.05;

/** Matches `MAX_PARTICLES` in `crates/thermo-wasm/src/lib.rs`. */
const MAX_PARTICLES = 4096;

/**
 * What the canvas talks to. Both the WASM engine and the fallback satisfy it,
 * so the render loop never branches on which one it got.
 */
export interface ThermoEngineHandle {
  /** Advance by `dtS` seconds in `regime`. */
  step(
    dtS: number,
    regime: HeatRegime,
    mediumTempC: number,
    hWm2K: number,
    radiantSourceK: number,
  ): void;
  /** Current particle state, `FLOATS_PER_PARTICLE` floats per particle. */
  view(): Float32Array;
  readonly particleCount: number;
  /** What is actually executing — rendered to the user, so it must be true. */
  readonly engine: "wasm" | "typescript";
  dispose(): void;
}

/**
 * The deterministic particle seed, transliterated from
 * `thermo_core::seeded_particles`.
 *
 * Closed form in the index, no RNG. That is what makes a cross-runtime trace
 * comparison possible at all.
 */
export function seedParticles(n: number): Float32Array {
  const buffer = new Float32Array(n * FLOATS_PER_PARTICLE);
  for (let i = 0; i < n; i += 1) {
    const fi = f(i);
    const o = i * FLOATS_PER_PARTICLE;
    buffer[o] = f(f(f(fi * f(0.37)) % 2) - 1);
    buffer[o + 1] = f(f(fi * f(0.191)) % 1);
    buffer[o + 2] = f(f(f(fi * f(0.53)) % 2) - 1);
    buffer[o + 3] = 0;
    buffer[o + 4] = 0;
    buffer[o + 5] = 0;
    buffer[o + 6] = f(20 + f(f(fi * f(0.7)) % 50));
    buffer[o + 7] = 0;
    // Staggered so nucleation does not pulse in unison. Closed form in the
    // index, like every other field — see `thermo_core::seeded_particles`.
    buffer[o + 8] = f(f(fi * f(0.113)) % 1);
  }
  return buffer;
}

/**
 * One simulation step in the [`HeatRegime.BuoyantAir`] regime.
 *
 * Retained as the entry point the pre-existing golden trace was generated
 * through — the trace reproducing byte-for-byte after the regime work is the
 * evidence that adding nine regimes did not perturb the shipped one.
 */
export function stepOvenSimulation(
  buffer: Float32Array,
  dtS: number,
  ovenTempC: number,
  hWm2K: number,
  radiantSourceK: number,
): void {
  stepMediumSimulation(buffer, dtS, HeatRegime.BuoyantAir, ovenTempC, hWm2K, radiantSourceK);
}

/**
 * One simulation step, transliterated from `thermo_core::step_medium_simulation`.
 *
 * Operates in place on a flat `Float32Array`. The association order of every
 * expression follows the Rust exactly; `a * b * c` is `(a * b) * c` in both
 * languages, and each intermediate is narrowed to f32 because the Rust
 * intermediates are f32.
 */
export function stepMediumSimulation(
  buffer: Float32Array,
  dtS: number,
  regime: HeatRegime,
  mediumTempC: number,
  hWm2K: number,
  radiantSourceK: number,
): void {
  const dt = f(dtS);
  const params = regimeParams(regime);
  // ⚠️ SIGNED, where the original clamped with `Math.max(0, ...)`. That clamp is
  // why a −196 °C cryogen animated as perfectly still air; cold media are denser
  // than the room and sink, and the sign of ΔT already says so.
  const buoyancy = f(f(f(mediumTempC) - RENDER_AMBIENT_C) * params.buoyancyPerK);
  const hRate = f(f(hWm2K) * f(0.001));

  // r⁴ is constant across particles, exactly as in the Rust.
  const r = f(f(radiantSourceK) / 1000);
  const quartic = f(f(f(f(r * r) * r) * r) * f(0.25));
  const radiantIntensity = quartic < 1 ? quartic : 1;

  const count = buffer.length / FLOATS_PER_PARTICLE;
  for (let i = 0; i < count; i += 1) {
    const o = i * FLOATS_PER_PARTICLE;
    let x = buffer[o];
    let y = buffer[o + 1];
    let z = buffer[o + 2];
    let vx = buffer[o + 3];
    let vy = buffer[o + 4];
    let vz = buffer[o + 5];
    let tempC = buffer[o + 6];
    let phaseFrac = buffer[o + 8];

    const phase = f(f(f(x * 2) + f(z * 3)) + f(f(i) * f(0.1)));
    // `sin_f32` in the Rust is `(x as f64).sin() as f32` — the transcendental
    // is evaluated in double precision and only then narrowed.
    const swirlX = f(f(Math.sin(phase)) * params.swirl);
    const swirlZ = f(f(Math.cos(phase)) * params.swirl);

    // Phase-change tracers carry an extra velocity along the transition
    // direction, ramped by how far through the cycle they are.
    const transit = f(f(params.nucleationDir * phaseFrac) * VAPOUR_TRANSIT);

    vx = f(f(vx + f(swirlX * dt)) * params.drag);
    vy = f(f(vy + f(f(buoyancy + transit) * dt)) * params.drag);
    vz = f(f(vz + f(swirlZ * dt)) * params.drag);

    x = f(x + f(vx * dt));
    y = f(y + f(vy * dt));
    z = f(z + f(vz * dt));

    // Wrap into the 1×1×1 render box. The y < 0 case is reachable only in the
    // regimes that travel downward — condensing steam, and anything below room
    // temperature.
    if (y > 1) y = 0;
    if (y < 0) y = 1;
    if (x < -1) x = 1;
    if (x > 1) x = -1;
    if (z < -1) z = 1;
    if (z > 1) z = -1;

    // Newton cooling toward the medium, paced by the method's own h. Gated
    // rather than scaled: a mass-transfer method has no heat flow, and letting
    // a borrowed h drive a temperature here is how the old canvas came to show
    // a fermentation crock equilibrating like a roast.
    if (params.coolingSign !== 0) {
      tempC = f(tempC + f(f(f(mediumTempC - tempC) * hRate) * dt));
    }

    // Advance the phase-change cycle. Deterministic and RNG-free, like the seed.
    if (params.nucleationPerS > 0) {
      phaseFrac = f(phaseFrac + f(params.nucleationPerS * dt));
      if (phaseFrac >= 1) phaseFrac = f(phaseFrac - 1);
    } else {
      phaseFrac = 0;
    }

    buffer[o] = x;
    buffer[o + 1] = y;
    buffer[o + 2] = z;
    buffer[o + 3] = vx;
    buffer[o + 4] = vy;
    buffer[o + 5] = vz;
    buffer[o + 6] = tempC;
    buffer[o + 7] = radiantIntensity;
    buffer[o + 8] = phaseFrac;
  }
}

/** The pure-TypeScript engine. Correct everywhere, just slower than WASM. */
export class FallbackThermoEngine implements ThermoEngineHandle {
  readonly engine = "typescript" as const;

  private readonly buffer: Float32Array;

  constructor(count: number) {
    const n = Math.min(Math.max(Math.trunc(count) || 1, 1), MAX_PARTICLES);
    this.buffer = seedParticles(n);
  }

  get particleCount(): number {
    return this.buffer.length / FLOATS_PER_PARTICLE;
  }

  step(
    dtS: number,
    regime: HeatRegime,
    mediumTempC: number,
    hWm2K: number,
    radiantSourceK: number,
  ): void {
    // Same clamp as the WASM engine. A backgrounded tab hands back a delta of
    // whole seconds when it wakes; integrating that in one step throws every
    // particle out of the box at once, which reads as the canvas resetting
    // itself whenever the user comes back to the page.
    const dt = Math.min(Math.max(dtS, 0), MAX_STEP_S);
    stepMediumSimulation(this.buffer, dt, regime, mediumTempC, hWm2K, radiantSourceK);
  }

  view(): Float32Array {
    return this.buffer;
  }

  dispose(): void {
    /* nothing to release */
  }
}

// ============================================================================
// WASM loading
// ============================================================================

/**
 * URL the wasm-bindgen bundle is served from.
 *
 * ⚠️ AN ABSOLUTE URL, NOT A MODULE SPECIFIER, and the difference is the whole
 * reason this constant has a comment. `[MEASURED 2026-08-16]` the first version
 * of this loader used `@/lib/wasm/generated/thermo_wasm.js` with
 * `webpackIgnore: true`. Those two cancel out: `webpackIgnore` hands the
 * specifier to the browser untouched, and the browser has never heard of the
 * `@/` alias. Every load failed with
 *
 *     TypeError: Failed to resolve module specifier '@/lib/wasm/generated/...'
 *
 * which the `catch` below swallowed into the fallback — so the canvas ran
 * TypeScript forever, in a build where the WASM module had been compiled,
 * verified and shipped. Nothing anywhere reported a problem.
 *
 * A path under `public/` is fetchable at runtime, so the browser can resolve
 * it, and when it has not been built the failure is an honest 404.
 */
const WASM_MODULE_URL = "/wasm/thermo_wasm.js";

/**
 * Shape of the wasm-bindgen `--target web` output we depend on.
 *
 * Declared structurally rather than imported, because the generated module is
 * a build product. public/wasm/ is committed as of 2026-08-22, so it is
 * normally present — but importing its .d.ts would make `bun run typecheck`
 * depend on a generated file, and the structural declaration also covers the
 * case this loader really has to survive: a BROWSER holding a cached older
 * bundle whose export set predates the current app JS. Every export added
 * after the particle engine is therefore optional and feature-detected.
 */
interface ThermoWasmModule {
  default: (input?: unknown) => Promise<{ memory: WebAssembly.Memory }>;
  ThermoEngine: new (count: number) => {
    step(
      dtS: number,
      regime: number,
      mediumTempC: number,
      hWm2K: number,
      radiantSourceK: number,
    ): boolean;
    readonly buffer_ptr: number;
    readonly buffer_len: number;
    readonly particle_count: number;
    free(): void;
  };
  floats_per_particle: () => number;

  // Scalar physics added alongside the particle engine. Declared STRUCTURALLY,
  // like everything above, so that typecheck never depends on a build product
  // and a cached older bundle cannot break the render. Every one of these is
  // optional at runtime: a browser may hold a CACHED older bundle that predates
  // them, and reading an undefined export would throw inside the render path.
  // `createThermoScalars` feature-detects each before use.
  latent_heat_vaporisation?: (celsius: number) => number;
  water_fusion_j_kg?: () => number;
  food_fusion_enthalpy?: (waterMassFraction: number) => number;
  food_vaporisation_enthalpy?: (waterMassFraction: number, celsius: number) => number;
  latent_as_temperature_rise?: (latentJkg: number, cpJkgK: number) => number;
  lid_balance_fields?: () => number;
  /* eslint-disable max-params --
   * These two mirror the arity of the Rust exports exactly, and that arity is
   * a consequence of a deliberate constraint rather than a style slip:
   * thermo-core is dependency-free (it is also linked into the SpacetimeDB
   * module), so there is no serde on either side and a struct has to cross the
   * boundary as positional scalars. Bundling them into an options object here
   * would hide the fact that the wire format IS positional, which is the one
   * property a reader of this interface most needs to know. */
  lid_heat_balance?: (
    lidAreaM2: number,
    lidPerimeterM: number,
    lidThicknessM: number,
    lidKWmK: number,
    headspaceC: number,
    ambientC: number,
    latentHeatJkg: number,
    emissivity: number,
  ) => Float64Array;

  // Boundary network. Returns a FLAT f64 buffer, not a struct — thermo-core is
  // dependency-free (it is also linked into the SpacetimeDB module) so there is
  // no serde on either side of this boundary.
  //
  // ⚠️ Memory: the generated glue does `getArrayF64FromWasm0(ptr, len).slice()`
  // and then frees the Rust allocation. The array handed to JS is therefore a
  // COPY, not a view into linear memory. That is the opposite of the particle
  // buffer contract — a `Float64Array` from here is safe to retain across
  // frames and cannot be detached by a later allocation, and there is nothing
  // for the caller to free.
  solve_boundary_network?: (
    sourceC: number,
    sinkC: number,
    hasVessel: boolean,
    vesselSourceHWm2K: number,
    vesselAreaM2: number,
    vesselKWmK: number,
    vesselThicknessM: number,
    vesselMediumHWm2K: number,
    hasFood: boolean,
    foodMediumHWm2K: number,
    foodGeometry: number,
    foodHalfDimensionM: number,
    foodKWmK: number,
    foodAreaM2: number,
  ) => Float64Array;
  /* eslint-enable max-params */
  boundary_network_link_ids?: (hasVessel: boolean, hasFood: boolean) => string;
  boundary_link_fields?: () => number;
  boundary_header_fields?: () => number;
  /** Wire-format version of the boundary buffer. Absent in bundles built
   *  before 2026-08-22 — see BOUNDARY_SCHEMA_VERSION below. */
  boundary_schema_version?: () => number;
}

class WasmThermoEngine implements ThermoEngineHandle {
  readonly engine = "wasm" as const;

  constructor(
    private readonly inner: InstanceType<ThermoWasmModule["ThermoEngine"]>,
    private readonly memory: WebAssembly.Memory,
  ) {}

  get particleCount(): number {
    return this.inner.particle_count;
  }

  step(
    dtS: number,
    regime: HeatRegime,
    mediumTempC: number,
    hWm2K: number,
    radiantSourceK: number,
  ): void {
    // The module REFUSES a regime it does not recognise rather than defaulting
    // to one. A stale bundle paired with a newer page would otherwise silently
    // render every method as an oven again — the precise regression this layer
    // exists to remove, and it would report nothing.
    if (!this.inner.step(dtS, regime, mediumTempC, hWm2K, radiantSourceK)) {
      throw new RangeError(`thermo-wasm rejected regime ${regime}`);
    }
  }

  view(): Float32Array {
    // Reconstructed every frame ON PURPOSE. Any allocation inside the module
    // can grow linear memory, and growing it detaches every existing
    // ArrayBuffer view — a cached view would silently start reading a
    // zero-length buffer, which renders as a canvas that simply stops.
    return new Float32Array(this.memory.buffer, this.inner.buffer_ptr, this.inner.buffer_len);
  }

  dispose(): void {
    this.inner.free();
  }
}

let modulePromise: Promise<ThermoWasmModule | null> | null = null;

/**
 * Load the WASM module once per page, or resolve null if it is unavailable.
 *
 * Never throws. Every failure path — no `WebAssembly` global, module not built,
 * fetch blocked, instantiation rejected — resolves to null so the caller takes
 * the fallback. A physics canvas is not worth a runtime error.
 */
async function loadModule(): Promise<ThermoWasmModule | null> {
  if (typeof WebAssembly === "undefined") return null;
  if (modulePromise) return modulePromise;

  modulePromise = (async (): Promise<ThermoWasmModule | null> => {
    try {
      // Probe before importing.
      //
      // ⚠️ A 404 HERE IS NO LONGER NORMAL. It was, while public/wasm/ was
      // gitignored — and that is exactly how production ran the TypeScript
      // engine unnoticed from the day this loader shipped: Vercel's build never
      // ran build:wasm, so alchm.kitchen answered 404 for the module and this
      // catch swallowed it into the fallback, honestly reporting
      // `engine: "typescript"` that nobody was reading. The artifact is
      // committed now, so a 404 means something is actually wrong — a broken
      // deploy or a stripped public/. The fallback still exists because
      // degrading to correct-but-slower physics beats a blank panel, but do not
      // read a fallback as expected. Next's dev overlay
      // surfaces a failed dynamic import as an error toast even when it is
      // caught. A 404 here is quiet and equally conclusive.
      const probe = await fetch(WASM_MODULE_URL, { method: "HEAD" });
      if (!probe.ok) return null;

      // `webpackIgnore` keeps the bundler from trying to resolve this at build
      // time — it cannot, the file may not exist yet — and leaves the browser
      // to fetch the URL, which it can.
      const mod = (await import(/* webpackIgnore: true */ WASM_MODULE_URL)) as unknown as ThermoWasmModule;
      if (typeof mod?.default !== "function" || typeof mod?.ThermoEngine !== "function") {
        return null;
      }
      return mod;
    } catch {
      return null;
    }
  })();

  return modulePromise;
}

/**
 * Create the best available engine for `count` particles.
 *
 * Resolves to a WASM engine where possible and a TypeScript one otherwise. The
 * caller reads `.engine` to label the panel — and that label must be whatever
 * actually ran, never a hopeful constant.
 */
export async function createThermoEngine(count: number): Promise<ThermoEngineHandle> {
  const mod = await loadModule();
  if (!mod) return new FallbackThermoEngine(count);

  try {
    const instance = await mod.default();
    // If the module and this file ever disagree about the buffer layout, every
    // particle would be read from the wrong offset — a scrambled canvas with
    // no error. Cheaper to check once than to debug once.
    if (mod.floats_per_particle() !== FLOATS_PER_PARTICLE) return new FallbackThermoEngine(count);
    const engine = new mod.ThermoEngine(count);
    return new WasmThermoEngine(engine, instance.memory);
  } catch {
    return new FallbackThermoEngine(count);
  }
}

/**
 * Which motion regime a method actually cooks in.
 *
 * DERIVED from the physics profile — `mediumKind`, `rateLimiter` and the
 * transfer-mode fractions — rather than read from a hand-written table of
 * method ids. That is deliberate: a lookup table would let a newly added method
 * fall through to a default, and the default would be the dry oven that every
 * method used to get. Here a new `MediumKind` is a compile error instead.
 *
 * The mapping, and why each branch is where it is:
 *
 *   no `h` at all      → Diffusion. The method is not heat-limited; the old
 *                        canvas borrowed the roasting profile for these and
 *                        animated a fermentation crock as a roast.
 *   saturated-water    → the rate limiter splits it. `phase-change` means the
 *                        transition is happening ON the food (steaming), so the
 *                        mass flux points inward; otherwise it is a boil.
 *   aqueous-subboiling → any phase-change fraction at all means vapour is being
 *                        generated (braise, simmer, stew). Zero means the
 *                        stillness IS the method (sous-vide, poaching).
 *   non-aqueous        → the sign of the superheat separates a cryogen from a
 *                        still. Both sit on a vapour-pressure curve; only one
 *                        of them takes heat OUT of the food.
 */
export function heatRegimeFor(physics: MethodPhysicsProfile): HeatRegime {
  // Checked first: `smoking`, `dehydrating` and `infusing` are mass-transfer
  // limited but DO carry a real `h`, so they keep their convective scene. Only
  // a method with no coefficient at all has no heat story to tell.
  if (physics.h === null) return HeatRegime.Diffusion;

  switch (physics.mediumKind) {
    case "dry-air":
      return HeatRegime.BuoyantAir;
    case "oil":
      return HeatRegime.Oil;
    case "solid-contact":
      return HeatRegime.SolidContact;
    case "radiant":
      return HeatRegime.Radiant;
    case "saturated-water":
      return physics.rateLimiter === "phase-change"
        ? HeatRegime.CondensingSteam
        : HeatRegime.RollingBoil;
    case "pressurised-steam":
      return HeatRegime.CondensingSteam;
    case "aqueous-subboiling":
      return physics.modes.phaseChange > 0 ? HeatRegime.RollingBoil : HeatRegime.StillLiquid;
    case "non-aqueous-saturated":
      return physics.mediumC < RENDER_AMBIENT_C ? HeatRegime.Cryogenic : HeatRegime.Distillation;
    case "ambient":
      return HeatRegime.Diffusion;
  }
}

/**
 * Pull the simulation's driving parameters out of a method's physics metrics.
 *
 * The `h` default is the roasting figure and is reached only by a method that
 * carries no coefficient at all. Those methods now run in
 * {@link HeatRegime.Diffusion}, where `coolingSign` is zero and the borrowed
 * number drives nothing — so the fallback no longer leaks a roast's pace into a
 * crock of pickles the way it used to.
 */
export function simulationInputs(metrics: MethodPhysicsMetrics): {
  regime: HeatRegime;
  ovenTempC: number;
  hWm2K: number;
  radiantSourceK: number;
} {
  return {
    regime: heatRegimeFor(metrics.physics),
    ovenTempC: metrics.medium.celsius,
    hWm2K: metrics.transfer?.typical ?? 25,
    radiantSourceK: metrics.physics.radiantSourceK ?? 505,
  };
}

// ============================================================================
// Scalar physics — dual runtime
// ============================================================================

/**
 * A value or a stated refusal.
 *
 * Structurally identical to `Reading<T>` in src/lib/cooking/labSolver.ts, and
 * declared here rather than imported so this module keeps its one-way
 * dependency on nothing under src/lib/cooking. TypeScript is structural, so the
 * two are interchangeable at every call site.
 */
export type ScalarReading<T> =
  | { available: true; value: T }
  | { available: false; reason: string };

const got = <T,>(value: T): ScalarReading<T> => ({ available: true, value });
const declined = <T,>(reason: string): ScalarReading<T> => ({
  available: false,
  reason,
});

/**
 * Convert the WASM boundary's NaN refusal into a stated one.
 *
 * ⚠️ This is the ONLY place a NaN from the module is allowed to exist. A NaN
 * that escapes into a component renders as "NaN" in the DOM, which reads as a
 * broken page rather than as "the correlation declined" — and worse, `NaN > 0`
 * is false, so a guard written the obvious way silently takes the wrong branch.
 */
function fromWasm(value: number, reason: string): ScalarReading<number> {
  return Number.isFinite(value) ? got(value) : declined(reason);
}

/**
 * Run a TypeScript kernel and convert its throw into a stated refusal.
 *
 * The kernels under src/lib/cooking throw `RangeError` with messages written
 * to be read by a person; that message is surfaced rather than replaced.
 */
function fromThrowing<T>(fn: () => T, context: string): ScalarReading<T> {
  try {
    const value = fn();
    if (typeof value === "number" && !Number.isFinite(value)) {
      return declined(`${context}: produced a non-finite value`);
    }
    return got(value);
  } catch (error) {
    return declined(
      error instanceof Error ? error.message : `${context}: refused`,
    );
  }
}

export interface LidBalanceReading {
  lidC: number;
  convectiveLossW: number;
  radiativeLossW: number;
  totalLossW: number;
  condensationCapacityKgS: number;
}

/**
 * Latent-heat and lid scalars, backed by whichever engine is actually present.
 *
 * `engine` is the engine that RAN, never a hopeful constant — the same rule the
 * particle canvas follows. A panel that labels itself "WASM" while running the
 * TypeScript path is the precise failure this pipeline was built to remove.
 */
export interface ThermoScalars {
  readonly engine: "wasm" | "typescript";
  latentHeatVaporisation(celsius: number): ScalarReading<number>;
  waterFusionJKg(): number;
  foodFusionEnthalpy(waterMassFraction: number): ScalarReading<number>;
  foodVaporisationEnthalpy(
    waterMassFraction: number,
    celsius: number,
  ): ScalarReading<number>;
  latentAsTemperatureRise(
    latentJkg: number,
    specificHeatJkgK: number,
  ): ScalarReading<number>;
  lidHeatBalance(input: {
    lidAreaM2: number;
    lidPerimeterM: number;
    lidThicknessM: number;
    lidKWmK: number;
    headspaceC: number;
    ambientC: number;
    latentHeatJkg: number;
    emissivity?: number;
  }): ScalarReading<LidBalanceReading>;
}

/**
 * The TypeScript half.
 *
 * Delegates to src/lib/cooking/* rather than transliterating the physics a
 * third time. There are already exactly two implementations under a byte-parity
 * contract pinned by one golden fixture; a third copy here would be a third
 * thing to keep in step, and nothing would notice when it fell behind.
 *
 * Imported lazily so a caller that only ever gets the WASM path does not pull
 * the whole cooking kernel into its bundle.
 */
async function typescriptScalars(): Promise<ThermoScalars> {
  const [latent, boundary] = await Promise.all([
    import("@/lib/cooking/latentHeat"),
    import("@/lib/cooking/boundaryNetwork"),
  ]);

  return {
    engine: "typescript",
    latentHeatVaporisation: (celsius) =>
      fromThrowing(
        () => latent.latentHeatVaporisation(celsius),
        "latentHeatVaporisation",
      ),
    waterFusionJKg: () => latent.WATER_FUSION_J_KG,
    foodFusionEnthalpy: (w) =>
      fromThrowing(() => latent.foodFusionEnthalpy(w), "foodFusionEnthalpy"),
    foodVaporisationEnthalpy: (w, c) =>
      fromThrowing(
        () => latent.foodVaporisationEnthalpy(w, c),
        "foodVaporisationEnthalpy",
      ),
    latentAsTemperatureRise: (j, cp) =>
      fromThrowing(
        () => latent.latentAsTemperatureRise(j, cp),
        "latentAsTemperatureRise",
      ),
    lidHeatBalance: (input) =>
      fromThrowing(() => {
        const r = boundary.lidHeatBalance({
          lidAreaM2: input.lidAreaM2,
          lidPerimeterM: input.lidPerimeterM,
          lidThicknessM: input.lidThicknessM,
          lidKWmK: input.lidKWmK,
          headspaceC: input.headspaceC,
          ambientC: input.ambientC,
          latentHeatJkg: input.latentHeatJkg,
          emissivity: input.emissivity ?? 0.9,
        });
        return {
          lidC: r.lidC,
          convectiveLossW: r.convectiveLossW,
          radiativeLossW: r.radiativeLossW,
          totalLossW: r.totalLossW,
          condensationCapacityKgS: r.condensationCapacityKgS,
        };
      }, "lidHeatBalance"),
  };
}

/**
 * Create the best available scalar engine.
 *
 * Falls back to TypeScript whenever the module is absent OR predates these
 * exports. The per-export feature detection matters: a browser holding a cached
 * bundle from before this change has `ThermoEngine` but not
 * `latent_heat_vaporisation`, and calling the missing one throws inside render.
 * Detecting the whole set together keeps a single engine label honest rather
 * than mixing runtimes call by call.
 */
export async function createThermoScalars(): Promise<ThermoScalars> {
  const mod = await loadModule();

  const complete =
    !!mod &&
    typeof mod.latent_heat_vaporisation === "function" &&
    typeof mod.water_fusion_j_kg === "function" &&
    typeof mod.food_fusion_enthalpy === "function" &&
    typeof mod.food_vaporisation_enthalpy === "function" &&
    typeof mod.latent_as_temperature_rise === "function" &&
    typeof mod.lid_heat_balance === "function" &&
    typeof mod.lid_balance_fields === "function";

  if (!mod || !complete) return typescriptScalars();

  try {
    await mod.default();
  } catch {
    return typescriptScalars();
  }

  // Stride check, same reasoning as floats_per_particle: if the module and this
  // file disagree about the buffer shape, every field is read from the wrong
  // index and the result is wrong numbers rather than an error.
  const LID_FIELDS = 5;
  if (mod.lid_balance_fields?.() !== LID_FIELDS) return typescriptScalars();

  return {
    engine: "wasm",
    latentHeatVaporisation: (celsius) =>
      fromWasm(
        mod.latent_heat_vaporisation!(celsius),
        `latent heat of vaporisation is fitted for 0–100 °C; ${celsius} °C is outside it`,
      ),
    waterFusionJKg: () => mod.water_fusion_j_kg!(),
    foodFusionEnthalpy: (w) =>
      fromWasm(
        mod.food_fusion_enthalpy!(w),
        `water mass fraction must be within 0–1; received ${w}`,
      ),
    foodVaporisationEnthalpy: (w, c) =>
      fromWasm(
        mod.food_vaporisation_enthalpy!(w, c),
        `composition or temperature outside the correlation range (w=${w}, ${c} °C)`,
      ),
    latentAsTemperatureRise: (j, cp) =>
      fromWasm(
        mod.latent_as_temperature_rise!(j, cp),
        `specific heat must be positive; received ${cp}`,
      ),
    lidHeatBalance: (input): ScalarReading<LidBalanceReading> => {
      const buf = mod.lid_heat_balance!(
        input.lidAreaM2,
        input.lidPerimeterM,
        input.lidThicknessM,
        input.lidKWmK,
        input.headspaceC,
        input.ambientC,
        input.latentHeatJkg,
        input.emissivity ?? 0.9,
      );
      // A refusal is a length-1 array. Checking LENGTH rather than NaN means a
      // caller never reads an element that does not exist.
      if (buf.length !== LID_FIELDS) {
        return declined(
          "lid heat balance refused: headspace must be above ambient and every geometry term positive",
        );
      }
      return got({
        lidC: buf[0],
        convectiveLossW: buf[1],
        radiativeLossW: buf[2],
        totalLossW: buf[3],
        condensationCapacityKgS: buf[4],
      });
    },
  };
}

// ============================================================================
// Boundary network — dual runtime
// ============================================================================

/**
 * Geometry discriminants, shared with `FoodGeometry` in thermo-core.
 *
 * ⚠️ A WIRE FORMAT. These integers cross the wasm boundary, so a stale cached
 * bundle paired with a newer page must still agree about them. Renumbering or
 * inserting a member silently changes which geometry the Bessel eigenvalue is
 * taken for — a wrong number that still looks like a number. The Rust side
 * REFUSES an unrecognised discriminant rather than defaulting to slab, which is
 * what turns a desync into a visible refusal instead of a quiet lie.
 */
// `number | undefined` is the type indexing ACTUALLY has. `Record<string,
// number>` claims every string key yields a number, which is false for an
// unmapped geometry and is exactly what the refusal below exists to catch;
// with `noUncheckedIndexedAccess: false` nothing else would tell the compiler.
//
// ⚠️ NULL PROTOTYPE, NOT AN OBJECT LITERAL. `[MEASURED 2026-08-22]` as a plain
// literal this leaked its prototype into the lookup: `constructor`,
// `toString`, `valueOf`, `hasOwnProperty` and `__proto__` all returned
// something non-undefined, so the refusal below PASSED them and handed a
// function to `solve_boundary_network`, where wasm-bindgen coerces it to NaN.
// The Rust side would still refuse an unrecognised discriminant, so this was
// never a wrong ANSWER — but it turned a clean JS-side refusal into a round
// trip that depends on the far side's guard, which is the sort of layering the
// rest of this file exists to avoid.
//
// Exported for the test that pins it: the refusal itself lives in the WASM arm,
// which jsdom cannot reach, so the dictionary is the piece coverage can hold.
export const GEOMETRY_DISCRIMINANT: Readonly<Record<string, number | undefined>> =
  Object.assign(Object.create(null) as Record<string, number | undefined>, {
    slab: 0,
    cylinder: 1,
    sphere: 2,
  });

/**
 * Link labels, keyed by the id the core emits.
 *
 * The Rust buffer carries no strings — `&'static str` cannot live in an f64
 * array — so the ids come from `boundary_network_link_ids` and the human labels
 * are attached here, matching the TypeScript implementation's wording exactly so
 * the two engines produce an identical `BoundaryNetworkResult`.
 */
const LINK_LABELS: Readonly<Record<string, string>> = {
  "source-to-vessel": "source → vessel outside",
  "vessel-wall": "through the vessel wall",
  "vessel-to-medium": "vessel inside → medium",
  "medium-to-food": "medium → food surface",
  "food-interior": "food surface → core",
};

export interface BoundarySolver {
  readonly engine: "wasm" | "typescript";
  /**
   * Solve the chain, or return null when the inputs fall outside the
   * correlations. Null is a REFUSAL, never a zeroed result — the panels render
   * it as an em dash with a reason.
   */
  solve(input: BoundaryNetworkInput): BoundaryNetworkResult | null;
}

/**
 * Decode the flat buffer into the same shape the TypeScript solver returns.
 *
 * Exported for `scripts/verify-boundary-solver-parity.mjs`, which A/Bs it
 * against the TypeScript solver. That script cannot go through
 * `createBoundarySolver` because the loader fetches public/wasm over HTTP and
 * the script has no browser — and a verifier that re-implements the decode
 * would be checking a copy, which is exactly how the link-id mirror in the Rust
 * crate drifted (`food-internal` vs the core's `food-interior`). Exporting the
 * real function is cheaper than maintaining a second one.
 */
export function decodeBoundaryBuffer(
  buf: Float64Array,
  ids: string[],
  headerFields: number,
  linkFields: number,
  sourceC: number,
): BoundaryNetworkResult | null {
  // A refusal is a length-1 array. Checking LENGTH rather than NaN means we
  // never index past the end of a buffer that was never populated.
  if (buf.length <= 1) return null;

  // Header, in the order documented on the Rust export. Destructured rather
  // than indexed so the field order is stated once and reads as a contract.
  const [
    totalResistanceKperW,
    uaWperK,
    heatFlowW,
    controllingIndex,
    foodBiotRaw,
    linkCount,
    nodeCount,
  ] = buf;

  // Guard the decode against a stale bundle whose layout differs. Without this
  // a shorter buffer reads undefined values as NaN and renders a full panel of
  // plausible-looking blanks instead of falling back to a working engine.
  const expected = headerFields + linkCount * linkFields + nodeCount;
  if (
    !Number.isInteger(linkCount) ||
    linkCount !== ids.length ||
    buf.length !== expected
  ) {
    return null;
  }

  const links: BoundaryLink[] = [];
  for (let i = 0; i < linkCount; i += 1) {
    const o = headerFields + i * linkFields;
    const id = ids[i];
    const h = buf[o + 2];
    links.push({
      id,
      label: LINK_LABELS[id] ?? id,
      resistanceKperW: buf[o + 0],
      areaM2: buf[o + 1],
      // NaN is how the core says "this link has no coefficient" — a pure
      // conduction leg. The TypeScript shape spells that as null.
      hWm2K: Number.isFinite(h) ? h : null,
      share: buf[o + 3],
      dropK: buf[o + 4],
    });
  }

  // Range-check the index itself rather than truthiness of the element.
  //
  // `controllingIndex` arrives from the WASM buffer and is not trusted. Two
  // things make the obvious `if (!links[i])` the wrong guard here:
  //
  //   - `tsconfig.json` sets `noUncheckedIndexedAccess: false`, so `links[i]`
  //     is typed as always present. The check reads as dead code to both the
  //     compiler and eslint, and annotating the variable `| undefined` does not
  //     help — TypeScript narrows straight back from the initializer.
  //   - `links.at(i)` would type correctly and behave WRONG: `.at(-1)` returns
  //     the LAST element, so a negative index from a malformed buffer would
  //     silently select a real link instead of being refused.
  //
  // An explicit numeric bound has neither problem, and says what it means.
  // Pinned by src/lib/wasm/__tests__/boundarySolver.test.ts.
  if (controllingIndex < 0 || controllingIndex >= links.length) return null;
  const controlling = links[controllingIndex];

  const nodeStart = headerFields + linkCount * linkFields;
  const nodes: Array<{ id: string; celsius: number }> = [];
  for (let i = 0; i < nodeCount; i += 1) {
    // Node 0 is the source; every later node is named for the link that
    // produced it, matching the TypeScript solver's `nodes` construction.
    nodes.push({
      id: i === 0 ? "source" : (ids[i - 1] ?? `node-${i}`),
      celsius: buf[nodeStart + i],
    });
  }
  if (nodes.length > 0) nodes[0].celsius = sourceC;

  return {
    links,
    totalResistanceKperW,
    uaWperK,
    heatFlowW,
    controlling,
    nodes,
    foodBiot: Number.isFinite(foodBiotRaw) ? foodBiotRaw : null,
  };
}

/**
 * Create the best available boundary solver.
 *
 * The two engines are under a byte-parity contract pinned by one golden
 * fixture, so this is NOT a choice between a good answer and a worse one —
 * they agree to a handful of ULP. It matters because the compiled engine is the
 * one the rest of the lab runs, and a panel silently on a different engine than
 * it claims is the failure this whole pipeline exists to prevent.
 */
/**
 * The boundary wire format this decoder understands.
 *
 * Must equal `boundary_schema_version()` in crates/thermo-wasm/src/lib.rs.
 * Bump BOTH together, in the same commit, whenever a header slot or link field
 * changes meaning — including changes that keep the field count identical.
 */
export const BOUNDARY_SCHEMA_VERSION = 1;

export async function createBoundarySolver(): Promise<BoundarySolver> {
  // NEVER REJECTS — same contract as `loadModule`, and for the same reason.
  // Callers await this inside an effect and set state from it; an unhandled
  // rejection there is an unhandled promise rejection AND a component wedged
  // on "loading" for the life of the page. `typescriptBoundarySolver` performs
  // a dynamic import, which is a real rejection path, so the guarantee has to
  // be enforced here rather than assumed.
  try {
    return await createBoundarySolverInner();
  } catch {
    try {
      return await typescriptBoundarySolver();
    } catch {
      return unavailableBoundarySolver();
    }
  }
}

async function createBoundarySolverInner(): Promise<BoundarySolver> {
  const mod = await loadModule();

  const usable =
    !!mod &&
    typeof mod.solve_boundary_network === "function" &&
    typeof mod.boundary_network_link_ids === "function" &&
    typeof mod.boundary_link_fields === "function" &&
    typeof mod.boundary_header_fields === "function";

  if (!mod || !usable) return typescriptBoundarySolver();

  try {
    await mod.default();
  } catch {
    return typescriptBoundarySolver();
  }

  // Bound to a non-null local: the narrowing from the guard above does not
  // reach into the hoisted helper below, and re-asserting `mod!` inside it
  // would be re-stating a fact the compiler already proved here.
  const m = mod;
  const linkFields = m.boundary_link_fields!();
  const headerFields = m.boundary_header_fields!();

  // Layout version, checked BEFORE the stride numbers because it is the
  // stricter test. A module may agree on 7 and 5 and still mean something
  // different by them — the count cannot distinguish "5 fields" from "the same
  // 5 fields in a different order", and a transposed pair decodes into a full
  // panel of plausible, wrong numbers rather than into an error.
  //
  // Feature-detected, not required: `boundary_schema_version` did not exist
  // before 2026-08-22, and a browser can hold a CACHED module from before then
  // while running today's app JS, because /wasm/thermo_wasm_bg.wasm is a stable
  // unhashed URL. A bundle that cannot state its version is a bundle whose
  // layout this decoder cannot vouch for, so it takes the TypeScript arm —
  // correct physics from the reference implementation, one engine label
  // different. Refusing is the honest reading of "I don't know".
  const version =
    typeof m.boundary_schema_version === "function"
      ? m.boundary_schema_version()
      : null;
  if (version !== BOUNDARY_SCHEMA_VERSION) return typescriptBoundarySolver();
  // Stride check: same reasoning as floats_per_particle. A disagreement here
  // means every field is read from the wrong index.
  if (linkFields !== 5 || headerFields !== 7) return typescriptBoundarySolver();

  return {
    engine: "wasm",
    solve(input): BoundaryNetworkResult | null {
      // ⚠️ try/catch is NOT belt-and-braces here. The release profile sets
      // `panic = "abort"`, so a panic inside the module TRAPS and wasm-bindgen
      // re-throws it as a JS exception. Unwrapped, that propagates out of the
      // useMemo a component calls this from and blanks the whole panel — the
      // same render-time failure class we just removed from ComparisonPanel.
      // The TypeScript half already normalises its kernel throws to null; this
      // makes the two engines fail the same way, which is the only reason a
      // caller can treat them as interchangeable.
      try {
        return solveViaWasm(input);
      } catch {
        return null;
      }
    },
  };

  function solveViaWasm(input: BoundaryNetworkInput): BoundaryNetworkResult | null {
    {
      const v = input.vessel;
      const f = input.food;
      const geometry = f ? GEOMETRY_DISCRIMINANT[f.geometry] : 0;
      // An unmapped geometry string would otherwise arrive as NaN and be
      // coerced by wasm-bindgen; refuse in JS instead of guessing.
      //
      // `f &&` was redundant and blocked narrowing: without food, `geometry`
      // is the literal 0 and can never be undefined, so this tests exactly the
      // unmapped-geometry case either way — and now the compiler can see that
      // the value reaching the call below is a number.
      if (geometry === undefined) return null;

      const buf = m.solve_boundary_network!(
        input.sourceC,
        input.sinkC,
        !!v,
        v?.sourceToVesselHWm2K ?? 0,
        v?.areaM2 ?? 0,
        v?.kWmK ?? 0,
        v?.thicknessM ?? 0,
        v?.vesselToMediumHWm2K ?? 0,
        !!f,
        f?.mediumToFoodHWm2K ?? 0,
        geometry,
        f?.halfDimensionM ?? 0,
        f?.kWmK ?? 0,
        f?.areaM2 ?? 0,
      );

      const ids = m.boundary_network_link_ids!(!!v, !!f);
      return decodeBoundaryBuffer(
        buf,
        ids.length > 0 ? ids.split(",") : [],
        headerFields,
        linkFields,
        input.sourceC,
      );
    }
  }
}

/**
 * Last resort: no engine at all.
 *
 * Reached only when even the TypeScript kernel fails to import. Every solve is
 * a refusal, which is the honest answer — the alternative is a promise that
 * never settles, leaving every caller on its loading state forever with no
 * error anywhere. A stuck spinner is indistinguishable from a slow network and
 * is the hardest kind of failure to diagnose from a bug report.
 */
function unavailableBoundarySolver(): BoundarySolver {
  return {
    engine: "typescript",
    solve: () => null,
  };
}

/** The TypeScript half — delegates to the existing kernel, refusal and all. */
async function typescriptBoundarySolver(): Promise<BoundarySolver> {
  const boundary = await import("@/lib/cooking/boundaryNetwork");
  return {
    engine: "typescript",
    solve(input): BoundaryNetworkResult | null {
      try {
        return boundary.solveBoundaryNetwork(input);
      } catch {
        // The kernel throws outside its envelope; the WASM half returns a
        // refusal. Normalise so a caller cannot tell the engines apart by how
        // they decline.
        return null;
      }
    },
  };
}
