/**
 * WebAssembly thermodynamics engine — loader, and the fallback that replaces it.
 *
 * The canvas in `OvenConvectionCanvas.tsx` runs a 60 FPS convection simulation.
 * That simulation is defined once, in Rust, at `crates/thermo-core`. This file
 * gives the browser two ways to execute it:
 *
 *   1. The compiled WASM module (`crates/thermo-wasm`), when it loads.
 *   2. {@link FallbackThermoEngine}, a transliteration of the same Rust,
 *      when it does not — server rendering, an offline Tauri window, a
 *      failed fetch, or a browser that declines the module.
 *
 * ── Why the fallback is transliterated rather than merely "equivalent" ──────
 *
 * `[MEASURED 2026-08-16]` Before this file existed, the Rust simulation and the
 * canvas's own TypeScript loop were two independently written models wearing
 * the same name. They disagreed on both constants that matter: buoyancy
 * 0.0005·ΔT against 0.003·ΔT (6× apart — 0.0775 vs 0.465 at a 175 °C oven) and
 * swirl amplitude 0.5 against 0.4. Since the browser silently falls back
 * whenever WASM is unavailable, "graceful degradation" meant rendering a
 * visibly different simulation with nothing anywhere to say so.
 *
 * So the fallback is a line-by-line transliteration, and it is held to that by
 * `src/__tests__/cookingThermoCrossRuntimeParity.test.ts`, which replays a
 * golden trace generated by the Rust and asserts this code reproduces it.
 *
 * ── f32 discipline ──────────────────────────────────────────────────────────
 *
 * The Rust simulation is `f32` throughout; JavaScript numbers are `f64`. Every
 * arithmetic step below is therefore wrapped in `Math.fround`, in the same
 * association order as the Rust. Dropping a single `fround` does not produce a
 * visible bug — it produces a slow divergence that only the golden trace
 * catches.
 */

import type { MethodPhysicsProfile } from "@/data/cooking/methodPhysics";
import type { MethodPhysicsMetrics } from "@/lib/cooking/methodMetrics";

/** f32 narrowing. Aliased because it appears on nearly every line below. */
const f = Math.fround;

/**
 * Simulation constants. These MUST equal `thermo_core::{BUOYANCY_PER_K,
 * SWIRL_AMPLITUDE, CONVECTION_DRAG}` and are asserted against the golden
 * fixture, which carries the Rust f32 values widened to f64.
 */
export const BUOYANCY_PER_K = f(0.003);
export const SWIRL_AMPLITUDE = f(0.4);
export const CONVECTION_DRAG = f(0.98);

/** Room temperature, the reference the buoyant ΔT is taken against, °C. */
export const RENDER_AMBIENT_C = f(20);

/** Extra velocity a phase-change tracer carries along its transition direction. */
export const VAPOUR_TRANSIT = f(0.55);

/**
 * Floats per particle:
 * `[x, y, z, vx, vy, vz, tempC, radiantIntensity, phaseFrac]`.
 */
export const FLOATS_PER_PARTICLE = 9;

/**
 * How a medium actually moves heat. Mirrors `thermo_core::HeatRegime`, and the
 * numeric values ARE the wire format — they cross into WASM as a `u8`.
 *
 * `[MEASURED 2026-08-17]` Before this existed the canvas ran one motion model
 * for all 26 methods, so `boiling` was drawn as a dry oven with a glowing
 * element, and `cryo_cooking` at −196 °C was drawn as a hot amber chamber with
 * perfectly still air (the old buoyancy clamped negative superheat to zero).
 * The data to tell them apart was already in `methodPhysics.ts` and none of it
 * reached the simulation.
 */
export const HeatRegime = {
  BuoyantAir: 0,
  Oil: 1,
  RollingBoil: 2,
  CondensingSteam: 3,
  StillLiquid: 4,
  Radiant: 5,
  SolidContact: 6,
  Cryogenic: 7,
  Diffusion: 8,
  Distillation: 9,
} as const;

export type HeatRegime = (typeof HeatRegime)[keyof typeof HeatRegime];

/** Motion parameters for one regime. Mirrors `thermo_core::RegimeParams`. */
export interface RegimeParams {
  buoyancyPerK: number;
  swirl: number;
  drag: number;
  nucleationPerS: number;
  nucleationDir: number;
  coolingSign: number;
}

// ── Volumetric thermal expansion, K⁻¹ ───────────────────────────────────────
// Mirrors `thermo_core::{BETA_AIR_OVEN, BETA_WATER_HOT, BETA_OIL, BETA_LN2}`.
// BASIS is stated once, in the Rust; duplicating the citations here would be a
// second place for them to rot.
const BETA_AIR_OVEN = f(f(1) / f(450));
const BETA_WATER_HOT = f(697.9e-6);
const BETA_OIL = f(7.0e-4);
const BETA_LN2 = f(5.7e-3);

/** Standard gravity as the ISA block fixes it, narrowed to f32. */
const G_M_S2 = f(9.80665);

/**
 * Render-box units per metre. DEFINED so `buoyancyForBeta(BETA_AIR_OVEN)`
 * reproduces {@link BUOYANCY_PER_K} exactly — asserted in the parity test, and
 * in `thermo_core`'s own `derived_air_buoyancy_reproduces_the_shipped_constant`.
 */
const SCENE_SCALE = f(BUOYANCY_PER_K / f(G_M_S2 * BETA_AIR_OVEN));

/** Buoyant acceleration per kelvin for a fluid of expansion coefficient β. */
export function buoyancyForBeta(betaPerK: number): number {
  return f(f(G_M_S2 * betaPerK) * SCENE_SCALE);
}

/**
 * Motion parameters per regime. Transliterated from `thermo_core::regime_params`
 * and pinned value-for-value by the golden fixture's `simulation.regimes` block.
 */
export function regimeParams(regime: HeatRegime): RegimeParams {
  switch (regime) {
    case HeatRegime.BuoyantAir:
      return {
        buoyancyPerK: BUOYANCY_PER_K,
        swirl: SWIRL_AMPLITUDE,
        drag: CONVECTION_DRAG,
        nucleationPerS: 0,
        nucleationDir: 0,
        coolingSign: 1,
      };
    case HeatRegime.Oil:
      return {
        buoyancyPerK: buoyancyForBeta(BETA_OIL),
        swirl: f(0.22),
        drag: f(0.94),
        nucleationPerS: f(1.6),
        nucleationDir: 1,
        coolingSign: 1,
      };
    case HeatRegime.RollingBoil:
      return {
        buoyancyPerK: buoyancyForBeta(BETA_WATER_HOT),
        swirl: f(0.3),
        drag: f(0.965),
        nucleationPerS: f(3.2),
        nucleationDir: 1,
        coolingSign: 1,
      };
    case HeatRegime.CondensingSteam:
      return {
        buoyancyPerK: f(buoyancyForBeta(BETA_WATER_HOT) * f(0.5)),
        swirl: f(0.16),
        drag: f(0.97),
        nucleationPerS: f(2.4),
        nucleationDir: -1,
        coolingSign: 1,
      };
    case HeatRegime.StillLiquid:
      return {
        buoyancyPerK: buoyancyForBeta(BETA_WATER_HOT),
        swirl: f(0.09),
        drag: f(0.95),
        nucleationPerS: 0,
        nucleationDir: 0,
        coolingSign: 1,
      };
    case HeatRegime.Radiant:
      return {
        buoyancyPerK: f(buoyancyForBeta(BETA_AIR_OVEN) * f(0.6)),
        swirl: f(0.12),
        drag: f(0.96),
        nucleationPerS: 0,
        nucleationDir: 0,
        coolingSign: 1,
      };
    case HeatRegime.SolidContact:
      return {
        buoyancyPerK: f(buoyancyForBeta(BETA_AIR_OVEN) * f(0.25)),
        swirl: f(0.06),
        drag: f(0.93),
        nucleationPerS: f(0.5),
        nucleationDir: 1,
        coolingSign: 1,
      };
    case HeatRegime.Cryogenic:
      return {
        buoyancyPerK: buoyancyForBeta(BETA_LN2),
        swirl: f(0.14),
        drag: f(0.985),
        nucleationPerS: f(2),
        nucleationDir: 1,
        coolingSign: -1,
      };
    case HeatRegime.Diffusion:
      return {
        buoyancyPerK: 0,
        swirl: f(0.05),
        drag: f(0.992),
        nucleationPerS: 0,
        nucleationDir: 0,
        coolingSign: 0,
      };
    case HeatRegime.Distillation:
      return {
        buoyancyPerK: f(buoyancyForBeta(BETA_WATER_HOT) * f(0.8)),
        swirl: f(0.1),
        drag: f(0.972),
        nucleationPerS: f(2.8),
        nucleationDir: 1,
        coolingSign: 1,
      };
  }
}

/** Longest delta a single step will integrate, seconds. */
const MAX_STEP_S = 0.05;

/** Matches `MAX_PARTICLES` in `crates/thermo-wasm/src/lib.rs`. */
const MAX_PARTICLES = 4096;

/**
 * What the canvas talks to. Both the WASM engine and the fallback satisfy it,
 * so the render loop never branches on which one it got.
 */
export interface ThermoEngineHandle {
  /** Advance by `dtS` seconds in `regime`. */
  step(
    dtS: number,
    regime: HeatRegime,
    mediumTempC: number,
    hWm2K: number,
    radiantSourceK: number,
  ): void;
  /** Current particle state, `FLOATS_PER_PARTICLE` floats per particle. */
  view(): Float32Array;
  readonly particleCount: number;
  /** What is actually executing — rendered to the user, so it must be true. */
  readonly engine: "wasm" | "typescript";
  dispose(): void;
}

/**
 * The deterministic particle seed, transliterated from
 * `thermo_core::seeded_particles`.
 *
 * Closed form in the index, no RNG. That is what makes a cross-runtime trace
 * comparison possible at all.
 */
export function seedParticles(n: number): Float32Array {
  const buffer = new Float32Array(n * FLOATS_PER_PARTICLE);
  for (let i = 0; i < n; i += 1) {
    const fi = f(i);
    const o = i * FLOATS_PER_PARTICLE;
    buffer[o] = f(f(f(fi * f(0.37)) % 2) - 1);
    buffer[o + 1] = f(f(fi * f(0.191)) % 1);
    buffer[o + 2] = f(f(f(fi * f(0.53)) % 2) - 1);
    buffer[o + 3] = 0;
    buffer[o + 4] = 0;
    buffer[o + 5] = 0;
    buffer[o + 6] = f(20 + f(f(fi * f(0.7)) % 50));
    buffer[o + 7] = 0;
    // Staggered so nucleation does not pulse in unison. Closed form in the
    // index, like every other field — see `thermo_core::seeded_particles`.
    buffer[o + 8] = f(f(fi * f(0.113)) % 1);
  }
  return buffer;
}

/**
 * One simulation step in the [`HeatRegime.BuoyantAir`] regime.
 *
 * Retained as the entry point the pre-existing golden trace was generated
 * through — the trace reproducing byte-for-byte after the regime work is the
 * evidence that adding nine regimes did not perturb the shipped one.
 */
export function stepOvenSimulation(
  buffer: Float32Array,
  dtS: number,
  ovenTempC: number,
  hWm2K: number,
  radiantSourceK: number,
): void {
  stepMediumSimulation(buffer, dtS, HeatRegime.BuoyantAir, ovenTempC, hWm2K, radiantSourceK);
}

/**
 * One simulation step, transliterated from `thermo_core::step_medium_simulation`.
 *
 * Operates in place on a flat `Float32Array`. The association order of every
 * expression follows the Rust exactly; `a * b * c` is `(a * b) * c` in both
 * languages, and each intermediate is narrowed to f32 because the Rust
 * intermediates are f32.
 */
export function stepMediumSimulation(
  buffer: Float32Array,
  dtS: number,
  regime: HeatRegime,
  mediumTempC: number,
  hWm2K: number,
  radiantSourceK: number,
): void {
  const dt = f(dtS);
  const params = regimeParams(regime);
  // ⚠️ SIGNED, where the original clamped with `Math.max(0, ...)`. That clamp is
  // why a −196 °C cryogen animated as perfectly still air; cold media are denser
  // than the room and sink, and the sign of ΔT already says so.
  const buoyancy = f(f(f(mediumTempC) - RENDER_AMBIENT_C) * params.buoyancyPerK);
  const hRate = f(f(hWm2K) * f(0.001));

  // r⁴ is constant across particles, exactly as in the Rust.
  const r = f(f(radiantSourceK) / 1000);
  const quartic = f(f(f(f(r * r) * r) * r) * f(0.25));
  const radiantIntensity = quartic < 1 ? quartic : 1;

  const count = buffer.length / FLOATS_PER_PARTICLE;
  for (let i = 0; i < count; i += 1) {
    const o = i * FLOATS_PER_PARTICLE;
    let x = buffer[o];
    let y = buffer[o + 1];
    let z = buffer[o + 2];
    let vx = buffer[o + 3];
    let vy = buffer[o + 4];
    let vz = buffer[o + 5];
    let tempC = buffer[o + 6];
    let phaseFrac = buffer[o + 8];

    const phase = f(f(f(x * 2) + f(z * 3)) + f(f(i) * f(0.1)));
    // `sin_f32` in the Rust is `(x as f64).sin() as f32` — the transcendental
    // is evaluated in double precision and only then narrowed.
    const swirlX = f(f(Math.sin(phase)) * params.swirl);
    const swirlZ = f(f(Math.cos(phase)) * params.swirl);

    // Phase-change tracers carry an extra velocity along the transition
    // direction, ramped by how far through the cycle they are.
    const transit = f(f(params.nucleationDir * phaseFrac) * VAPOUR_TRANSIT);

    vx = f(f(vx + f(swirlX * dt)) * params.drag);
    vy = f(f(vy + f(f(buoyancy + transit) * dt)) * params.drag);
    vz = f(f(vz + f(swirlZ * dt)) * params.drag);

    x = f(x + f(vx * dt));
    y = f(y + f(vy * dt));
    z = f(z + f(vz * dt));

    // Wrap into the 1×1×1 render box. The y < 0 case is reachable only in the
    // regimes that travel downward — condensing steam, and anything below room
    // temperature.
    if (y > 1) y = 0;
    if (y < 0) y = 1;
    if (x < -1) x = 1;
    if (x > 1) x = -1;
    if (z < -1) z = 1;
    if (z > 1) z = -1;

    // Newton cooling toward the medium, paced by the method's own h. Gated
    // rather than scaled: a mass-transfer method has no heat flow, and letting
    // a borrowed h drive a temperature here is how the old canvas came to show
    // a fermentation crock equilibrating like a roast.
    if (params.coolingSign !== 0) {
      tempC = f(tempC + f(f(f(mediumTempC - tempC) * hRate) * dt));
    }

    // Advance the phase-change cycle. Deterministic and RNG-free, like the seed.
    if (params.nucleationPerS > 0) {
      phaseFrac = f(phaseFrac + f(params.nucleationPerS * dt));
      if (phaseFrac >= 1) phaseFrac = f(phaseFrac - 1);
    } else {
      phaseFrac = 0;
    }

    buffer[o] = x;
    buffer[o + 1] = y;
    buffer[o + 2] = z;
    buffer[o + 3] = vx;
    buffer[o + 4] = vy;
    buffer[o + 5] = vz;
    buffer[o + 6] = tempC;
    buffer[o + 7] = radiantIntensity;
    buffer[o + 8] = phaseFrac;
  }
}

/** The pure-TypeScript engine. Correct everywhere, just slower than WASM. */
export class FallbackThermoEngine implements ThermoEngineHandle {
  readonly engine = "typescript" as const;

  private readonly buffer: Float32Array;

  constructor(count: number) {
    const n = Math.min(Math.max(Math.trunc(count) || 1, 1), MAX_PARTICLES);
    this.buffer = seedParticles(n);
  }

  get particleCount(): number {
    return this.buffer.length / FLOATS_PER_PARTICLE;
  }

  step(
    dtS: number,
    regime: HeatRegime,
    mediumTempC: number,
    hWm2K: number,
    radiantSourceK: number,
  ): void {
    // Same clamp as the WASM engine. A backgrounded tab hands back a delta of
    // whole seconds when it wakes; integrating that in one step throws every
    // particle out of the box at once, which reads as the canvas resetting
    // itself whenever the user comes back to the page.
    const dt = Math.min(Math.max(dtS, 0), MAX_STEP_S);
    stepMediumSimulation(this.buffer, dt, regime, mediumTempC, hWm2K, radiantSourceK);
  }

  view(): Float32Array {
    return this.buffer;
  }

  dispose(): void {
    /* nothing to release */
  }
}

// ============================================================================
// WASM loading
// ============================================================================

/**
 * URL the wasm-bindgen bundle is served from.
 *
 * ⚠️ AN ABSOLUTE URL, NOT A MODULE SPECIFIER, and the difference is the whole
 * reason this constant has a comment. `[MEASURED 2026-08-16]` the first version
 * of this loader used `@/lib/wasm/generated/thermo_wasm.js` with
 * `webpackIgnore: true`. Those two cancel out: `webpackIgnore` hands the
 * specifier to the browser untouched, and the browser has never heard of the
 * `@/` alias. Every load failed with
 *
 *     TypeError: Failed to resolve module specifier '@/lib/wasm/generated/...'
 *
 * which the `catch` below swallowed into the fallback — so the canvas ran
 * TypeScript forever, in a build where the WASM module had been compiled,
 * verified and shipped. Nothing anywhere reported a problem.
 *
 * A path under `public/` is fetchable at runtime, so the browser can resolve
 * it, and when it has not been built the failure is an honest 404.
 */
const WASM_MODULE_URL = "/wasm/thermo_wasm.js";

/**
 * Shape of the wasm-bindgen `--target web` output we depend on.
 *
 * Declared structurally rather than imported, because the generated module is
 * gitignored: it is a build product of `bun run build:wasm`, and a checkout
 * that has not run that step must still typecheck and still render.
 */
interface ThermoWasmModule {
  default: (input?: unknown) => Promise<{ memory: WebAssembly.Memory }>;
  ThermoEngine: new (count: number) => {
    step(
      dtS: number,
      regime: number,
      mediumTempC: number,
      hWm2K: number,
      radiantSourceK: number,
    ): boolean;
    readonly buffer_ptr: number;
    readonly buffer_len: number;
    readonly particle_count: number;
    free(): void;
  };
  floats_per_particle: () => number;
}

class WasmThermoEngine implements ThermoEngineHandle {
  readonly engine = "wasm" as const;

  constructor(
    private readonly inner: InstanceType<ThermoWasmModule["ThermoEngine"]>,
    private readonly memory: WebAssembly.Memory,
  ) {}

  get particleCount(): number {
    return this.inner.particle_count;
  }

  step(
    dtS: number,
    regime: HeatRegime,
    mediumTempC: number,
    hWm2K: number,
    radiantSourceK: number,
  ): void {
    // The module REFUSES a regime it does not recognise rather than defaulting
    // to one. A stale bundle paired with a newer page would otherwise silently
    // render every method as an oven again — the precise regression this layer
    // exists to remove, and it would report nothing.
    if (!this.inner.step(dtS, regime, mediumTempC, hWm2K, radiantSourceK)) {
      throw new RangeError(`thermo-wasm rejected regime ${regime}`);
    }
  }

  view(): Float32Array {
    // Reconstructed every frame ON PURPOSE. Any allocation inside the module
    // can grow linear memory, and growing it detaches every existing
    // ArrayBuffer view — a cached view would silently start reading a
    // zero-length buffer, which renders as a canvas that simply stops.
    return new Float32Array(this.memory.buffer, this.inner.buffer_ptr, this.inner.buffer_len);
  }

  dispose(): void {
    this.inner.free();
  }
}

let modulePromise: Promise<ThermoWasmModule | null> | null = null;

/**
 * Load the WASM module once per page, or resolve null if it is unavailable.
 *
 * Never throws. Every failure path — no `WebAssembly` global, module not built,
 * fetch blocked, instantiation rejected — resolves to null so the caller takes
 * the fallback. A physics canvas is not worth a runtime error.
 */
async function loadModule(): Promise<ThermoWasmModule | null> {
  if (typeof WebAssembly === "undefined") return null;
  if (modulePromise) return modulePromise;

  modulePromise = (async () => {
    try {
      // Probe before importing. A missing bundle is the NORMAL state of a
      // checkout that has not run `bun run build:wasm`, and Next's dev overlay
      // surfaces a failed dynamic import as an error toast even when it is
      // caught. A 404 here is quiet and equally conclusive.
      const probe = await fetch(WASM_MODULE_URL, { method: "HEAD" });
      if (!probe.ok) return null;

      // `webpackIgnore` keeps the bundler from trying to resolve this at build
      // time — it cannot, the file may not exist yet — and leaves the browser
      // to fetch the URL, which it can.
      const mod = (await import(/* webpackIgnore: true */ WASM_MODULE_URL)) as unknown as ThermoWasmModule;
      if (typeof mod?.default !== "function" || typeof mod?.ThermoEngine !== "function") {
        return null;
      }
      return mod;
    } catch {
      return null;
    }
  })();

  return modulePromise;
}

/**
 * Create the best available engine for `count` particles.
 *
 * Resolves to a WASM engine where possible and a TypeScript one otherwise. The
 * caller reads `.engine` to label the panel — and that label must be whatever
 * actually ran, never a hopeful constant.
 */
export async function createThermoEngine(count: number): Promise<ThermoEngineHandle> {
  const mod = await loadModule();
  if (!mod) return new FallbackThermoEngine(count);

  try {
    const instance = await mod.default();
    // If the module and this file ever disagree about the buffer layout, every
    // particle would be read from the wrong offset — a scrambled canvas with
    // no error. Cheaper to check once than to debug once.
    if (mod.floats_per_particle() !== FLOATS_PER_PARTICLE) return new FallbackThermoEngine(count);
    const engine = new mod.ThermoEngine(count);
    return new WasmThermoEngine(engine, instance.memory);
  } catch {
    return new FallbackThermoEngine(count);
  }
}

/**
 * Which motion regime a method actually cooks in.
 *
 * DERIVED from the physics profile — `mediumKind`, `rateLimiter` and the
 * transfer-mode fractions — rather than read from a hand-written table of
 * method ids. That is deliberate: a lookup table would let a newly added method
 * fall through to a default, and the default would be the dry oven that every
 * method used to get. Here a new `MediumKind` is a compile error instead.
 *
 * The mapping, and why each branch is where it is:
 *
 *   no `h` at all      → Diffusion. The method is not heat-limited; the old
 *                        canvas borrowed the roasting profile for these and
 *                        animated a fermentation crock as a roast.
 *   saturated-water    → the rate limiter splits it. `phase-change` means the
 *                        transition is happening ON the food (steaming), so the
 *                        mass flux points inward; otherwise it is a boil.
 *   aqueous-subboiling → any phase-change fraction at all means vapour is being
 *                        generated (braise, simmer, stew). Zero means the
 *                        stillness IS the method (sous-vide, poaching).
 *   non-aqueous        → the sign of the superheat separates a cryogen from a
 *                        still. Both sit on a vapour-pressure curve; only one
 *                        of them takes heat OUT of the food.
 */
export function heatRegimeFor(physics: MethodPhysicsProfile): HeatRegime {
  // Checked first: `smoking`, `dehydrating` and `infusing` are mass-transfer
  // limited but DO carry a real `h`, so they keep their convective scene. Only
  // a method with no coefficient at all has no heat story to tell.
  if (physics.h === null) return HeatRegime.Diffusion;

  switch (physics.mediumKind) {
    case "dry-air":
      return HeatRegime.BuoyantAir;
    case "oil":
      return HeatRegime.Oil;
    case "solid-contact":
      return HeatRegime.SolidContact;
    case "radiant":
      return HeatRegime.Radiant;
    case "saturated-water":
      return physics.rateLimiter === "phase-change"
        ? HeatRegime.CondensingSteam
        : HeatRegime.RollingBoil;
    case "pressurised-steam":
      return HeatRegime.CondensingSteam;
    case "aqueous-subboiling":
      return physics.modes.phaseChange > 0 ? HeatRegime.RollingBoil : HeatRegime.StillLiquid;
    case "non-aqueous-saturated":
      return physics.mediumC < RENDER_AMBIENT_C ? HeatRegime.Cryogenic : HeatRegime.Distillation;
    case "ambient":
      return HeatRegime.Diffusion;
  }
}

/**
 * Pull the simulation's driving parameters out of a method's physics metrics.
 *
 * The `h` default is the roasting figure and is reached only by a method that
 * carries no coefficient at all. Those methods now run in
 * {@link HeatRegime.Diffusion}, where `coolingSign` is zero and the borrowed
 * number drives nothing — so the fallback no longer leaks a roast's pace into a
 * crock of pickles the way it used to.
 */
export function simulationInputs(metrics: MethodPhysicsMetrics): {
  regime: HeatRegime;
  ovenTempC: number;
  hWm2K: number;
  radiantSourceK: number;
} {
  return {
    regime: heatRegimeFor(metrics.physics),
    ovenTempC: metrics.medium.celsius,
    hWm2K: metrics.transfer?.typical ?? 25,
    radiantSourceK: metrics.physics.radiantSourceK ?? 505,
  };
}
