/**
 * Alchemical Constitution — a user's four ESMS reserves and their archetype.
 *
 * The quantities (Spirit/Essence/Matter/Substance) come from which planets a
 * chart contains, plus sect, dignity and aspects. They CANNOT be derived from
 * the chart's elemental balance (Fire/Water/Earth/Air), which is a separate,
 * orthogonal reading taken from the signs those planets occupy — see the header
 * of `./planetaryAlchemyMapping.ts`, the authoritative source.
 *
 * Consumers pass the ESMS that `calculateNatalChart` already derives into
 * `alchemicalProperties`; this module only normalizes and interprets them.
 */

import type { AlchemicalProperties } from "@/types/celestial";

export const ESMS_KEYS = ["spirit", "essence", "matter", "substance"] as const;
export type EsmsKey = (typeof ESMS_KEYS)[number];

export type EsmsShares = Record<EsmsKey, number>;

export const ARCHETYPE_BY_QUANTITY: Record<EsmsKey, string> = {
  spirit: "Solar Forager",
  essence: "Lunar Adept",
  matter: "Root Alchemist",
  substance: "Wind Whisperer",
};

/**
 * Population baseline for each quantity's share of the chart total, per sect.
 *
 * ESMS comes from which planets are present, and every natal chart contains all
 * ten — so the profile is dominated by sect rather than by the individual chart
 * (day ~42/33/15/10, night ~24/18/39/19). Taking the raw maximum would therefore
 * hand every day-born user "Solar Forager" and every night-born user "Root
 * Alchemist", leaving the other archetypes effectively unreachable.
 *
 * Scoring each quantity against its own sect baseline instead makes the
 * archetype reflect what is genuinely distinctive about the chart.
 *
 * Generated by `scripts/generate-esms-baseline.ts` (20,000 charts per sect).
 * Regenerate — and paste the result here — if PLANETARY_ALCHEMY,
 * PLANETARY_SECTARIAN_ESMS, the dignity scales, or the aspect ESMS effects
 * change. `src/__tests__/alchemicalConstitution.test.ts` fails if these drift.
 *
 * Caveat: the generator samples signs uniformly, so the MEANS are exact (they
 * follow from planet presence and sect) while the SDs approximate a real
 * population, whose outer planets cluster by birth generation.
 */
export const ESMS_BASELINE: Record<
  "diurnal" | "nocturnal",
  Record<EsmsKey, { mean: number; sd: number }>
> = {
  diurnal: {
    spirit: { mean: 41.63, sd: 2.84 },
    essence: { mean: 33.37, sd: 2.82 },
    matter: { mean: 15.03, sd: 3.1 },
    substance: { mean: 9.98, sd: 2.26 },
  },
  nocturnal: {
    spirit: { mean: 24.02, sd: 2.87 },
    essence: { mean: 17.83, sd: 2.88 },
    matter: { mean: 39.13, sd: 3.21 },
    substance: { mean: 19.02, sd: 2.33 },
  },
};

/**
 * Normalize raw planetary ESMS sums to each quantity's percentage share of the
 * chart total. Returns exact (unrounded) shares — round only for display, and
 * never before {@link selectArchetype}, whose baselines have an sd well under
 * one point.
 */
export function toEsmsShares(esms: AlchemicalProperties): EsmsShares {
  const total = esms.Spirit + esms.Essence + esms.Matter + esms.Substance;
  const share = (value: number) => (total > 0 ? (value / total) * 100 : 0);
  return {
    spirit: share(esms.Spirit),
    essence: share(esms.Essence),
    matter: share(esms.Matter),
    substance: share(esms.Substance),
  };
}

/**
 * Pick the archetype for a chart: the quantity standing furthest above its sect
 * baseline wins. Ties resolve to the earlier key in {@link ESMS_KEYS}.
 *
 * @param shares - exact ESMS shares from {@link toEsmsShares}
 * @param diurnal - true for a day chart, false for a night chart
 */
export function selectArchetype(
  shares: EsmsShares,
  diurnal: boolean,
): { dominantToken: EsmsKey; baseArchetype: string; z: number } {
  const baseline = ESMS_BASELINE[diurnal ? "diurnal" : "nocturnal"];

  let dominantToken: EsmsKey = "spirit";
  let bestZ = -Infinity;
  for (const key of ESMS_KEYS) {
    const { mean, sd } = baseline[key];
    const z = sd > 0 ? (shares[key] - mean) / sd : 0;
    if (z > bestZ) {
      bestZ = z;
      dominantToken = key;
    }
  }

  return {
    dominantToken,
    baseArchetype: ARCHETYPE_BY_QUANTITY[dominantToken],
    z: bestZ,
  };
}
