/**
 * Sample-driven statistics layer.
 *
 * Reads the pre-computed alchemicalSamples.json (generated by
 * `scripts/generateAlchemicalSamples.ts`) and produces summary statistics
 * over arbitrary time windows without ever calling astronomy-engine.
 *
 * Server-only: imports the JSON synchronously at module scope. Client code
 * should hit `/api/alchm-quantities/statistics` instead.
 */

import samplesFile from "@/data/alchemicalSamples.json";
import {
  contextualize,
  histogram,
  type ContextualValue,
  type Histogram,
} from "@/utils/statisticsCalculations";

// ─── Types ────────────────────────────────────────────────────────────────────

interface CompactPlanetBreakdown {
  e: [number, number, number, number]; // ESMS
  l: [number, number, number, number]; // Fire/Water/Earth/Air
  s: string;
}

interface CompactSample {
  ts: number;
  esms: [number, number, number, number];
  thermo: [number, number, number, number, number, number];
  el: [number, number, number, number];
  pp: Record<string, CompactPlanetBreakdown>;
  d: 0 | 1;
}

interface SampleFile {
  version: number;
  generatedAt: string;
  intervalHours: number;
  startMs: number;
  endMs: number;
  count: number;
  samples: CompactSample[];
}

const FILE = samplesFile as unknown as SampleFile;

export type StatPeriod = "day" | "week" | "month" | "quarter" | "year" | "all";

const PERIOD_DAYS: Record<Exclude<StatPeriod, "all">, number> = {
  day: 1,
  week: 7,
  month: 30,
  quarter: 91,
  year: 365,
};

// ─── Slicing ──────────────────────────────────────────────────────────────────

/**
 * Slice samples that fall in [start, end] ms (inclusive). Falls back to
 * empty array when no samples land in the window. Uses binary search since
 * the file is sorted by ts.
 */
function sliceByMs(startMs: number, endMs: number): CompactSample[] {
  const arr = FILE.samples;
  if (arr.length === 0 || endMs < arr[0].ts || startMs > arr[arr.length - 1].ts) {
    return [];
  }
  let lo = 0;
  let hi = arr.length - 1;
  // First index >= startMs
  while (lo < hi) {
    const mid = (lo + hi) >>> 1;
    if (arr[mid].ts < startMs) lo = mid + 1;
    else hi = mid;
  }
  const startIdx = lo;
  hi = arr.length;
  // First index > endMs
  let l = startIdx;
  let h = arr.length;
  while (l < h) {
    const mid = (l + h) >>> 1;
    if (arr[mid].ts <= endMs) l = mid + 1;
    else h = mid;
  }
  const endIdx = l;
  return arr.slice(startIdx, endIdx);
}

export function periodWindow(
  period: StatPeriod,
  reference: Date = new Date(),
): { startMs: number; endMs: number } {
  const endMs = reference.getTime();
  if (period === "all") {
    return { startMs: FILE.startMs, endMs };
  }
  const days = PERIOD_DAYS[period];
  return { startMs: endMs - days * 24 * 60 * 60 * 1000, endMs };
}

/**
 * Find the sample nearest to a given moment.
 */
export function getSampleNearest(at: Date | number): CompactSample | null {
  const target = typeof at === "number" ? at : at.getTime();
  const arr = FILE.samples;
  if (arr.length === 0) return null;
  let lo = 0;
  let hi = arr.length - 1;
  while (lo < hi) {
    const mid = (lo + hi) >>> 1;
    if (arr[mid].ts < target) lo = mid + 1;
    else hi = mid;
  }
  // arr[lo].ts is the first ≥ target. Compare with neighbour for closer.
  const candidates = [arr[lo]];
  if (lo > 0) candidates.push(arr[lo - 1]);
  candidates.sort((a, b) => Math.abs(a.ts - target) - Math.abs(b.ts - target));
  return candidates[0];
}

// ─── Series accessors ─────────────────────────────────────────────────────────

const ESMS_KEYS = ["Spirit", "Essence", "Matter", "Substance"] as const;
const THERMO_KEYS = [
  "heat",
  "entropy",
  "reactivity",
  "gregsEnergy",
  "kalchm",
  "monica",
] as const;
const ELEMENT_KEYS = ["Fire", "Water", "Earth", "Air"] as const;

type EsmsKey = (typeof ESMS_KEYS)[number];
type ThermoKey = (typeof THERMO_KEYS)[number];
type ElementKey = (typeof ELEMENT_KEYS)[number];

function pickEsmsSeries(samples: CompactSample[], key: EsmsKey): number[] {
  const idx = ESMS_KEYS.indexOf(key);
  return samples.map((s) => s.esms[idx]);
}
function pickThermoSeries(samples: CompactSample[], key: ThermoKey): number[] {
  const idx = THERMO_KEYS.indexOf(key);
  return samples.map((s) => s.thermo[idx]);
}
function pickElementSeries(samples: CompactSample[], key: ElementKey): number[] {
  const idx = ELEMENT_KEYS.indexOf(key);
  return samples.map((s) => s.el[idx]);
}
function pickPlanetEsmsSeries(
  samples: CompactSample[],
  planet: string,
  key: EsmsKey,
): number[] {
  const idx = ESMS_KEYS.indexOf(key);
  return samples.map((s) => s.pp[planet]?.e[idx] ?? 0);
}
function pickPlanetElementSeries(
  samples: CompactSample[],
  planet: string,
  key: ElementKey,
): number[] {
  const idx = ELEMENT_KEYS.indexOf(key);
  return samples.map((s) => s.pp[planet]?.l[idx] ?? 0);
}

// ─── Contextual quantity (current + summary + sparkline + histogram) ──────────

export interface QuantityContext extends ContextualValue {
  /** Compact series for sparkline rendering (≤ 96 points). */
  spark: number[];
  /** Histogram of the period's values — the "wavefunction" envelope. */
  hist: Histogram;
}

const SPARK_LEN = 96;

function downsample(series: number[], target: number): number[] {
  if (series.length <= target) return [...series];
  const step = series.length / target;
  const out: number[] = new Array(target);
  for (let i = 0; i < target; i++) {
    const start = Math.floor(i * step);
    const end = Math.max(start + 1, Math.floor((i + 1) * step));
    let sum = 0;
    let count = 0;
    for (let j = start; j < end && j < series.length; j++) {
      sum += series[j];
      count++;
    }
    out[i] = count > 0 ? sum / count : series[start];
  }
  return out;
}

function build(series: number[], current: number, bins = 24): QuantityContext {
  const ctx = contextualize(series, current);
  return {
    ...ctx,
    spark: downsample(series, SPARK_LEN),
    hist: histogram(series, bins),
  };
}

// ─── Public API ───────────────────────────────────────────────────────────────

export interface PeriodStatistics {
  period: StatPeriod;
  startMs: number;
  endMs: number;
  sampleCount: number;
  intervalHours: number;
  current: {
    ts: number;
    isDiurnal: boolean;
  };
  esms: Record<EsmsKey, QuantityContext>;
  thermo: Record<ThermoKey, QuantityContext>;
  elemental: Record<ElementKey, QuantityContext>;
  /** A-Number (Spirit + Essence + Matter + Substance) treated as its own quantity. */
  aNumber: QuantityContext;
  /** GregsEnergy − Heat × Reactivity, all the derived metrics aggregated. */
  derived: {
    aNumber: QuantityContext;
  };
  perPlanet: Record<
    string,
    {
      esms: Record<EsmsKey, QuantityContext>;
      elements: Record<ElementKey, QuantityContext>;
    }
  >;
  meta: {
    fileGeneratedAt: string;
    fileVersion: number;
    fileCount: number;
  };
}

function detectPlanets(samples: CompactSample[]): string[] {
  const set = new Set<string>();
  for (const s of samples) {
    for (const p of Object.keys(s.pp)) set.add(p);
    if (set.size >= 12) break;
  }
  return Array.from(set);
}

/**
 * Build the full statistics payload for a period, ending at `reference`.
 * Returns null if the window contains < 2 samples (no meaningful stats).
 */
export function getStatisticsForPeriod(
  period: StatPeriod,
  reference: Date = new Date(),
): PeriodStatistics | null {
  const { startMs, endMs } = periodWindow(period, reference);
  const samples = sliceByMs(startMs, endMs);
  if (samples.length < 2) return null;

  // "Current" = sample nearest the reference moment, sourced from the slice.
  const refMs = reference.getTime();
  let current = samples[samples.length - 1];
  let bestDelta = Math.abs(current.ts - refMs);
  for (const s of samples) {
    const d = Math.abs(s.ts - refMs);
    if (d < bestDelta) {
      bestDelta = d;
      current = s;
    }
  }

  const esms = {} as Record<EsmsKey, QuantityContext>;
  for (const k of ESMS_KEYS) {
    esms[k] = build(
      pickEsmsSeries(samples, k),
      current.esms[ESMS_KEYS.indexOf(k)],
    );
  }
  const thermo = {} as Record<ThermoKey, QuantityContext>;
  for (const k of THERMO_KEYS) {
    thermo[k] = build(
      pickThermoSeries(samples, k),
      current.thermo[THERMO_KEYS.indexOf(k)],
    );
  }
  const elemental = {} as Record<ElementKey, QuantityContext>;
  for (const k of ELEMENT_KEYS) {
    elemental[k] = build(
      pickElementSeries(samples, k),
      current.el[ELEMENT_KEYS.indexOf(k)],
    );
  }

  const aNumberSeries = samples.map(
    (s) => s.esms[0] + s.esms[1] + s.esms[2] + s.esms[3],
  );
  const aNumberCurrent =
    current.esms[0] + current.esms[1] + current.esms[2] + current.esms[3];
  const aNumberCtx = build(aNumberSeries, aNumberCurrent);

  const planets = detectPlanets(samples);
  const perPlanet: PeriodStatistics["perPlanet"] = {};
  for (const planet of planets) {
    const planetEsms = {} as Record<EsmsKey, QuantityContext>;
    for (const k of ESMS_KEYS) {
      const idx = ESMS_KEYS.indexOf(k);
      planetEsms[k] = build(
        pickPlanetEsmsSeries(samples, planet, k),
        current.pp[planet]?.e[idx] ?? 0,
      );
    }
    const planetEl = {} as Record<ElementKey, QuantityContext>;
    for (const k of ELEMENT_KEYS) {
      const idx = ELEMENT_KEYS.indexOf(k);
      planetEl[k] = build(
        pickPlanetElementSeries(samples, planet, k),
        current.pp[planet]?.l[idx] ?? 0,
      );
    }
    perPlanet[planet] = { esms: planetEsms, elements: planetEl };
  }

  return {
    period,
    startMs: samples[0].ts,
    endMs: samples[samples.length - 1].ts,
    sampleCount: samples.length,
    intervalHours: FILE.intervalHours,
    current: {
      ts: current.ts,
      isDiurnal: current.d === 1,
    },
    esms,
    thermo,
    elemental,
    aNumber: aNumberCtx,
    derived: {
      aNumber: aNumberCtx,
    },
    perPlanet,
    meta: {
      fileGeneratedAt: FILE.generatedAt,
      fileVersion: FILE.version,
      fileCount: FILE.count,
    },
  };
}

/**
 * Convenience: given a reference moment, return per-period stats for ALL
 * standard periods, used by the "Statistics" tab to show day/week/month/year
 * side-by-side.
 */
export function getAllPeriodStatistics(
  reference: Date = new Date(),
): Record<StatPeriod, PeriodStatistics | null> {
  const periods: StatPeriod[] = ["day", "week", "month", "quarter", "year", "all"];
  return periods.reduce(
    (acc, p) => {
      acc[p] = getStatisticsForPeriod(p, reference);
      return acc;
    },
    {} as Record<StatPeriod, PeriodStatistics | null>,
  );
}

export function getSampleFileMeta() {
  return {
    version: FILE.version,
    generatedAt: FILE.generatedAt,
    intervalHours: FILE.intervalHours,
    startMs: FILE.startMs,
    endMs: FILE.endMs,
    count: FILE.count,
  };
}
