/**
 * §18o STAGE 2 — move each construction into its own column, and give the
 * chart-bearing agents a real full-chart monica.
 *
 * DRY RUN BY DEFAULT. `--write` snapshots first, then migrates in ONE transaction.
 *
 *   railway run --service Postgres -- bun scripts/backfillMonicaPerConstruction.ts
 *   railway run --service Postgres -- bun scripts/backfillMonicaPerConstruction.ts --write
 *
 * Requires database/init/71-monica-per-construction.sql (stage 1) to be applied.
 * Stage 3 (tightening constraints) is deliberately separate and comes after.
 *
 * ── What it does ────────────────────────────────────────────────────────────
 *
 *  1. SINGLE-BODY  copy monica_constant -> monica_single. `monica_constant` keeps
 *                  its value: §18o rules it single-body-only, so for this
 *                  population the two columns agree by definition.
 *  2. TWO-BODY     copy monica_constant -> monica_two_body, then NULL
 *                  monica_constant. These 469 rows were written there before the
 *                  ruling and must not stay in a single-body-only column.
 *  3. FULL-CHART   compute from natal_positions, BOTH SECTS (0 of 71 have birth
 *                  data, so sect is unresolvable — §18n), write
 *                  monica_diurnal/nocturnal + monica_full_chart, stamp
 *                  monica_method='full-chart', and NULL monica_constant, which
 *                  currently holds a hand-authored literal.
 *
 * ── Reversibility ───────────────────────────────────────────────────────────
 *
 * Steps 1-2 are recomputable from the agent's own name (proven: 4750 rows match
 * a fresh recomputation to 1e-5), so they need no snapshot to be recoverable.
 * Step 3 does: the 71 values it overwrites are HAND-AUTHORED and cannot be
 * regenerated by any engine. The snapshot exists for them specifically.
 */
import pg from "pg";
import { MONICA_EQUILIBRIUM } from "@/data/unified/alchemicalCalculations";
import {
  agentMonicaFromName,
  parseAgentPlacement,
  twoBodyMonicaFromName,
} from "@/utils/agentMonicaResolver";
import { fullChartMonica } from "@/utils/fullChartMonica";

const WRITE = process.argv.includes("--write");
const f = (n: number) => n.toFixed(6);
const q = (xs: number[], p: number) => {
  const s = [...xs].sort((a, b) => a - b);
  return s[Math.floor((s.length - 1) * p)];
};

const client = new pg.Client({
  connectionString: process.env.DATABASE_PUBLIC_URL,
  ssl: { rejectUnauthorized: false },
});
await client.connect();

// Stage 1 must have run. Fail loudly rather than writing nothing and reporting success.
const cols = await client.query<{ column_name: string }>(
  `SELECT column_name FROM information_schema.columns
    WHERE table_name = 'user_profiles'
      AND column_name IN ('monica_single','monica_two_body','monica_full_chart')`,
);
if (cols.rowCount !== 3) {
  const msg =
    `per-construction columns missing (found ${cols.rowCount} of 3). ` +
    `Apply database/init/71-monica-per-construction.sql first.`;
  if (WRITE) {
    console.error(`FATAL: ${msg}`);
    await client.end();
    process.exit(1);
  }
  console.warn(`WARNING: ${msg}\n(dry run continues — it only reads)\n`);
}

interface Row {
  user_id: string;
  name: string;
  monica_constant: string | null;
  monica_method: string | null;
  natal_positions: unknown;
}
const { rows } = await client.query<Row>(
  `SELECT up.user_id, up.name, up.monica_constant::text, up.monica_method, up.natal_positions
     FROM user_profiles up JOIN users u ON u.id = up.user_id
    WHERE u.is_agent AND up.name IS NOT NULL
    ORDER BY up.name`,
);

interface Move { user_id: string; name: string; value: number }
interface FullChart extends Move { diurnal: number; nocturnal: number; before: number | null }

const single: Move[] = [];
const twoBody: Move[] = [];
const fullChart: FullChart[] = [];
const unusableChart: string[] = [];
const unaccounted: string[] = [];

// Classify by NAME, which is authoritative, and RECOMPUTE the value rather than
// copying monica_constant.
//
// ⚠️ An earlier draft classified on the stored value ("has a monica → it is the
// kind its name says; otherwise try the chart"). That mis-routed every row whose
// backfill had not yet run into the full-chart branch — and there are always
// such rows, because the agent population grows continuously (43 new arrivals
// were sitting at NULL when this was written). Recomputing also makes the script
// self-sufficient and idempotent: it does not care what is currently stored, so
// it picks up new agents instead of skipping them.
let newlyComputed = 0;

for (const r of rows) {
  const stored = r.monica_constant === null ? null : Number(r.monica_constant);
  const placement = parseAgentPlacement(r.name);

  if (placement?.kind === "single") {
    const m = agentMonicaFromName(r.name);
    if (!m) {
      unaccounted.push(`${r.name}  (parsed single, but no monica computable)`);
      continue;
    }
    if (stored === null) newlyComputed++;
    single.push({ user_id: r.user_id, name: r.name, value: m.combined });
    continue;
  }

  if (placement?.kind === "phase") {
    let m: { combined: number } | null = null;
    try {
      m = twoBodyMonicaFromName(r.name);
    } catch {
      unaccounted.push(`${r.name}  (unclassifiable phase — must be reported, never defaulted)`);
      continue;
    }
    if (!m) {
      unaccounted.push(`${r.name}  (parsed phase, but no monica computable)`);
      continue;
    }
    if (stored === null) newlyComputed++;
    twoBody.push({ user_id: r.user_id, name: r.name, value: m.combined });
    continue;
  }

  // Not a placement at all: a chart-bearing agent, if it has a usable chart.
  const m = fullChartMonica(r.natal_positions);
  if (m) {
    fullChart.push({
      user_id: r.user_id,
      name: r.name,
      value: m.combined,
      diurnal: m.diurnal,
      nocturnal: m.nocturnal,
      before: stored,
    });
    continue;
  }
  if (Array.isArray(r.natal_positions)) unusableChart.push(r.name);
  else unaccounted.push(r.name);
}

// ---------------------------------------------------------------- report ----
console.log(`\n=== §18o per-construction split ${WRITE ? "WRITE" : "DRY RUN"} ===`);
console.log(`agent rows scanned          : ${rows.length}`);
console.log(`  single-body  -> monica_single      : ${single.length}`);
console.log(`  two-body     -> monica_two_body    : ${twoBody.length}  (monica_constant -> NULL)`);
console.log(`  full-chart   -> monica_full_chart  : ${fullChart.length}  (computed, both sects)`);
console.log(`  chart present but unusable         : ${unusableChart.length}`);
console.log(`  no placement, no chart             : ${unaccounted.length}`);
console.log(`  NEW arrivals (were NULL, now computed): ${newlyComputed}`);
const accounted =
  single.length + twoBody.length + fullChart.length + unusableChart.length + unaccounted.length;
console.log(`  accounted for                      : ${accounted} / ${rows.length}` +
  (accounted === rows.length ? "  OK" : "  *** MISMATCH ***"));

const dist = (label: string, xs: number[]) => {
  if (!xs.length) return console.log(`  ${label}: (none)`);
  console.log(
    `  ${label.padEnd(12)} [${f(Math.min(...xs))}, ${f(Math.max(...xs))}]  median ${f(q(xs, 0.5))}` +
      `  distinct ${new Set(xs.map((v) => v.toFixed(6))).size}/${xs.length}` +
      `  φ ${xs.filter((v) => v === MONICA_EQUILIBRIUM).length}`,
  );
};
console.log(`\nper-construction distributions (each on its OWN scale — §18o):`);
dist("single-body", single.map((m) => m.value));
dist("two-body", twoBody.map((m) => m.value));
dist("full-chart", fullChart.map((m) => m.value));

if (fullChart.length) {
  const before = fullChart.filter((r) => r.before !== null).map((r) => r.before!);
  if (before.length) {
    const ratios = fullChart
      .filter((r) => r.before !== null && r.value !== 0)
      .map((r) => Math.abs(r.before! / r.value));
    console.log(
      `\nfull-chart: replacing ${before.length} HAND-AUTHORED literals ` +
        `[${f(Math.min(...before))}, ${f(Math.max(...before))}]`,
    );
    console.log(
      `  |authored / computed| median ${q(ratios, 0.5).toFixed(1)}x  max ${Math.max(...ratios).toFixed(1)}x` +
        `  <- these are NOT recomputable; the snapshot exists for them`,
    );
  }
  console.log(`\nfull-chart sample (both sects stored — sect is unresolvable, §18n):`);
  console.table(
    fullChart.slice(0, 8).map((r) => ({
      name: r.name.slice(0, 26),
      authored: r.before,
      diurnal: Number(r.diurnal.toFixed(6)),
      nocturnal: Number(r.nocturnal.toFixed(6)),
      combined: Number(r.value.toFixed(6)),
    })),
  );
}

if (unusableChart.length) {
  console.log(`\n⚠️ chart present but UNUSABLE (fewer than 5 resolvable bodies) — left untouched:`);
  console.log("  " + unusableChart.slice(0, 20).join("\n  "));
}
if (unaccounted.length) {
  console.log(`\nno placement and no chart — left untouched (first 20):`);
  console.log("  " + unaccounted.slice(0, 20).join("\n  "));
}

const nonFinite = [...single, ...twoBody, ...fullChart].filter((m) => !Number.isFinite(m.value));
console.log(`\nNON-FINITE (must be 0)      : ${nonFinite.length}`);
if (nonFinite.length) {
  console.error("FATAL:", nonFinite.slice(0, 10).map((m) => m.name));
  await client.end();
  process.exit(1);
}

// ----------------------------------------------------------------- write ----
if (!WRITE) {
  console.log(`\nDRY RUN — nothing written. Re-run with --write to commit.`);
  await client.end();
  process.exit(0);
}

const stamp = new Date().toISOString().replace(/[-:]/g, "").replace(/\..+/, "").replace("T", "_");
const snapshot = `monica_preconstruction_${stamp}`;
if (!/^monica_preconstruction_\d{8}_\d{6}$/.test(snapshot)) {
  throw new Error(`unexpected snapshot name: ${snapshot}`);
}

console.log(`\nsnapshotting to ${snapshot}, then migrating in one transaction...`);
await client.query("BEGIN");
try {
  await client.query(
    `CREATE TABLE ${snapshot} AS
       SELECT up.user_id, up.name, up.monica_constant, up.monica_diurnal,
              up.monica_nocturnal, up.monica_method, now() AS snapshotted_at
         FROM user_profiles up JOIN users u ON u.id = up.user_id
        WHERE u.is_agent`,
  );

  // 1. single-body: populate the typed column, monica_constant unchanged.
  await client.query(
    `UPDATE user_profiles up SET monica_single = v.val, updated_at = now()
       FROM (SELECT * FROM unnest($1::uuid[], $2::numeric[]) AS t(user_id, val)) v
      WHERE up.user_id = v.user_id`,
    [single.map((m) => m.user_id), single.map((m) => m.value)],
  );

  // 2. two-body: move out of monica_constant.
  await client.query(
    `UPDATE user_profiles up
        SET monica_two_body = v.val, monica_constant = NULL, updated_at = now()
       FROM (SELECT * FROM unnest($1::uuid[], $2::numeric[]) AS t(user_id, val)) v
      WHERE up.user_id = v.user_id`,
    [twoBody.map((m) => m.user_id), twoBody.map((m) => m.value)],
  );

  // 3. full-chart: computed value + both sects, and drop the authored literal.
  await client.query(
    `UPDATE user_profiles up SET
       monica_full_chart = v.combined,
       monica_diurnal    = v.diurnal,
       monica_nocturnal  = v.nocturnal,
       monica_method     = 'full-chart',
       monica_constant   = NULL,
       updated_at        = now()
     FROM (
       SELECT * FROM unnest($1::uuid[], $2::numeric[], $3::numeric[], $4::numeric[])
              AS t(user_id, combined, diurnal, nocturnal)
     ) v
     WHERE up.user_id = v.user_id`,
    [
      fullChart.map((m) => m.user_id),
      fullChart.map((m) => m.value),
      fullChart.map((m) => m.diurnal),
      fullChart.map((m) => m.nocturnal),
    ],
  );

  await client.query("COMMIT");
  console.log("COMMIT ok");
} catch (err) {
  await client.query("ROLLBACK");
  console.error("ROLLBACK —", err);
  await client.end();
  process.exit(1);
}

// --------------------------------------------------------------- verify ----
const check = await client.query<Record<string, string>>(
  `SELECT coalesce(monica_method,'(null)') AS method,
          count(*)::text AS n,
          count(monica_constant)::text   AS has_constant,
          count(monica_single)::text     AS has_single,
          count(monica_two_body)::text   AS has_two_body,
          count(monica_full_chart)::text AS has_full_chart
     FROM user_profiles up JOIN users u ON u.id = up.user_id
    WHERE u.is_agent GROUP BY 1 ORDER BY 2 DESC`,
);
console.log("\npost-write verification (monica_constant must be 0 for two-body/full-chart):");
console.table(check.rows);
console.log(`\nTo reverse: restore from ${snapshot} (it holds the pre-migration`);
console.log(`monica_constant/diurnal/nocturnal/method for every agent row).`);

await client.end();
