/**
 * Regenerates the ESMS_BASELINE constants in src/utils/alchemicalConstitution.ts.
 *
 * Why a baseline exists at all: ESMS comes from which planets a chart contains,
 * and every chart contains all ten. Layers 1-2 of the engine (sect + dignity)
 * therefore land nearly every chart on the same profile, and sect — not the
 * individual chart — dominates. Selecting an archetype by raw maximum would hand
 * every day-born user "Lunar Adept" and every night-born user "Root Alchemist",
 * because Essence draws on 7 planets and Matter on 6 while Spirit draws on 4 and
 * Substance on 2. Scoring each quantity against its own sect baseline fixes that.
 *
 * Run when PLANETARY_ALCHEMY, PLANETARY_SECTARIAN_ESMS, the dignity scales, or
 * the aspect ESMS effects change:
 *
 *   bun run scripts/generate-esms-baseline.ts
 *
 * then paste the printed block into ESMS_BASELINE. The unit test
 * src/__tests__/alchemicalConstitution.test.ts asserts the committed constants
 * still match this computation, so CI fails if they drift.
 *
 * Sampling model: signs and longitudes are drawn uniformly for every body, with
 * the sign derived from the longitude so dignity and aspects agree. Real
 * populations are not uniform — outer planets cluster by birth generation, and
 * Mercury/Venus are bounded near the Sun — so the MEANS here are exact (they are
 * driven by planet presence and sect) while the SDs are an approximation of a
 * real population's spread. Deterministic seed: reruns reproduce byte-for-byte.
 */

import { buildAspectsWithStrength } from "@/utils/aspectCalculator";
import { calculateEnhancedAlchemicalFromPlanets } from "@/utils/planetaryAlchemyMapping";

const SIGNS = [
  "aries", "taurus", "gemini", "cancer", "leo", "virgo",
  "libra", "scorpio", "sagittarius", "capricorn", "aquarius", "pisces",
];
const BODIES = [
  "Sun", "Moon", "Mercury", "Venus", "Mars", "Jupiter",
  "Saturn", "Uranus", "Neptune", "Pluto", "Ascendant",
];
const KEYS = ["spirit", "essence", "matter", "substance"] as const;
type Key = (typeof KEYS)[number];

export const SAMPLE_SIZE = 20000;
export const SEED = 20260716;

/** Deterministic LCG so the committed constants are reproducible. */
function makeRng(seed: number) {
  let s = seed;
  return () => (s = (s * 1103515245 + 12345) % 2147483648) / 2147483648;
}

/**
 * Sample one sect's ESMS share distribution through the real engine.
 *
 * Exported so the unit test can re-run it against the committed constants; the
 * test passes a smaller sampleSize to stay inside its timeout, which is fine
 * because the means converge quickly (standard error < 0.03 by n=2000).
 */
export function sampleSect(
  diurnal: boolean,
  sampleSize: number = SAMPLE_SIZE,
): Record<Key, { mean: number; sd: number }> {
  const rnd = makeRng(SEED);
  const samples: Record<Key, number[]> = { spirit: [], essence: [], matter: [], substance: [] };

  for (let i = 0; i < sampleSize; i++) {
    const aspectPositions: Record<string, { sign: string; exactLongitude: number }> = {};
    const signMap: Record<string, string> = {};
    for (const body of BODIES) {
      const longitude = rnd() * 360;
      const sign = SIGNS[Math.floor(longitude / 30)];
      aspectPositions[body] = { sign, exactLongitude: longitude };
      signMap[body] = sign;
    }

    // Layer 3 — the same aspects natalChartService now feeds the engine.
    const aspects = buildAspectsWithStrength(aspectPositions);

    const esms = calculateEnhancedAlchemicalFromPlanets(signMap, diurnal, aspects);
    const total = esms.Spirit + esms.Essence + esms.Matter + esms.Substance;
    samples.spirit.push(total > 0 ? (esms.Spirit / total) * 100 : 0);
    samples.essence.push(total > 0 ? (esms.Essence / total) * 100 : 0);
    samples.matter.push(total > 0 ? (esms.Matter / total) * 100 : 0);
    samples.substance.push(total > 0 ? (esms.Substance / total) * 100 : 0);
  }

  const out = {} as Record<Key, { mean: number; sd: number }>;
  for (const key of KEYS) {
    const a = samples[key];
    const mean = a.reduce((s, v) => s + v, 0) / a.length;
    const sd = Math.sqrt(a.reduce((s, v) => s + (v - mean) ** 2, 0) / a.length);
    out[key] = { mean: Math.round(mean * 100) / 100, sd: Math.round(sd * 100) / 100 };
  }
  return out;
}

function main() {
  const diurnal = sampleSect(true);
  const nocturnal = sampleSect(false);

  const fmt = (s: Record<Key, { mean: number; sd: number }>) =>
    KEYS.map((k) => `    ${k}: { mean: ${s[k].mean}, sd: ${s[k].sd} },`).join("\n");

  console.log(`// Generated by scripts/generate-esms-baseline.ts (n=${SAMPLE_SIZE}/sect, seed=${SEED})`);
  console.log("  diurnal: {");
  console.log(fmt(diurnal));
  console.log("  },");
  console.log("  nocturnal: {");
  console.log(fmt(nocturnal));
  console.log("  },");
}

// Run main() only when invoked directly, never when the test imports sampleSect.
// (Deliberately not `import.meta.main`: that is Bun-only and breaks under ts-jest.)
if (process.argv[1]?.includes("generate-esms-baseline")) main();
