/**
 * Generates src/data/cuisines/derivedProfiles.json: each cuisine's elemental
 * profile, COMPUTED from its own dishes (src/data/cuisines/deriveProfile.ts),
 * and copies the profiles into the backend's cuisine JSON, which main.py serves.
 *
 *   bun run generate:cuisine-profiles
 *
 * Run it after changing any dish's elementalProperties.
 * src/__tests__/cuisineDerivedProfiles.test.ts fails while either file is stale.
 */
import fs from "fs";
import path from "path";
import { deriveCuisineProfile, type DerivedCuisineProfile } from "../src/data/cuisines/deriveProfile";
import { PRIMARY_CUISINE_KEYS, loadRawCuisine } from "../src/data/cuisines/index";

const PROFILES_PATH = path.join(process.cwd(), "src/data/cuisines/derivedProfiles.json");
const BACKEND_JSON = path.join(process.cwd(), "backend/alchm_kitchen/data/json");

const BASIS =
  "COMPUTED: the mean of the cuisine's distinct dish profiles, each taken as shares of 1. " +
  "A dish listed under several meals or seasons counts once, with its entries averaged. " +
  "Generated by scripts/generateCuisineProfiles.ts; do not edit by hand.";

const normKey = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, "");

async function deriveAll(): Promise<Record<string, DerivedCuisineProfile>> {
  const profiles: Record<string, DerivedCuisineProfile> = {};
  for (const key of PRIMARY_CUISINE_KEYS) {
    const profile = deriveCuisineProfile(await loadRawCuisine(key));
    if (!profile) throw new Error(`${key}: no dish carries a full elemental profile`);
    profiles[key] = profile;
  }
  return profiles;
}

/** Overwrite a backend cuisine record's profile with the derived one, keeping key order */
function patchRecord(record: Record<string, unknown>, profile: DerivedCuisineProfile): void {
  record.elementalProperties = profile.elementalProperties;
  record.elementalProfileBasis = { method: "recipe-mean", recipes: profile.recipes };
}

function patchBackend(profiles: Record<string, DerivedCuisineProfile>): string[] {
  const byNorm = new Map(Object.entries(profiles).map(([k, p]) => [normKey(k), p]));
  const written: string[] = [];

  const combinedPath = path.join(BACKEND_JSON, "cuisines.json");
  const combined = JSON.parse(fs.readFileSync(combinedPath, "utf8")) as Record<string, Record<string, unknown>>;
  for (const [key, record] of Object.entries(combined)) {
    const profile = byNorm.get(normKey(key));
    if (profile) patchRecord(record, profile);
  }
  fs.writeFileSync(combinedPath, JSON.stringify(combined, null, 2));
  written.push(combinedPath);

  const dir = path.join(BACKEND_JSON, "cuisines");
  for (const file of fs.readdirSync(dir).filter((f) => f.endsWith(".json"))) {
    const profile = byNorm.get(normKey(path.basename(file, ".json")));
    if (!profile) continue;
    const filePath = path.join(dir, file);
    const record = JSON.parse(fs.readFileSync(filePath, "utf8")) as Record<string, unknown>;
    patchRecord(record, profile);
    fs.writeFileSync(filePath, JSON.stringify(record, null, 2));
    written.push(filePath);
  }
  return written;
}

async function main() {
  const profiles = await deriveAll();
  fs.writeFileSync(PROFILES_PATH, `${JSON.stringify({ basis: BASIS, cuisines: profiles }, null, 2)}\n`);
  const written = patchBackend(profiles);
  for (const [key, p] of Object.entries(profiles)) {
    const e = p.elementalProperties;
    console.log(`${key.padEnd(14)} n=${String(p.recipes).padStart(3)}  F ${e.Fire}  W ${e.Water}  E ${e.Earth}  A ${e.Air}`);
  }
  console.log(`wrote ${path.relative(process.cwd(), PROFILES_PATH)} and ${written.length} backend files`);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
