//! Emit the cross-runtime golden vectors as JSON.
//!
//! Run: `cargo run -p thermo-core --example emit_golden > \
//!       crates/thermo-core/tests/thermo_golden_vectors.json`
//!
//! ## What this file is, and what it is NOT
//!
//! It is a convenience for REGENERATING the fixture after a deliberate change
//! to the physics, so the expected values are not hand-transcribed (which is
//! how transcription drift gets in — see `food_effusivity_lean_meat`).
//!
//! It is NOT the authority on whether those values are correct. A fixture
//! generated from Rust and then asserted by Rust proves nothing; that test
//! would pass just as happily against a defect. The fixture earns its keep in
//! two other places:
//!
//!   1. `src/__tests__/cookingThermoCrossRuntimeParity.test.ts` asserts the
//!      TypeScript implementation reproduces it EXACTLY. That is the drift
//!      detector, and it is the reason this file exists.
//!   2. The `externalAnchors` block is checked against published figures that
//!      come from outside this repository entirely — Denver's boiling point,
//!      Baldwin's sous-vide tables, the ISA published exponent. Regenerating
//!      cannot launder a wrong number past those.
//!
//! So: regenerate freely, but read the diff. A vector that moves without a
//! corresponding change to a named constant is the bug announcing itself.

use thermo_core::*;

/// Print an f64 in the SHORTEST form that round-trips back to the same bits.
///
/// `[MEASURED 2026-08-16]` The first version of this used `{v:.17e}` on the
/// reasoning that 17 significant digits is the IEEE-754 round-trip guarantee.
/// It round-tripped through Rust's own `str::parse` — which is what the
/// assertion below checked — and then lost the last bit in `serde_json`,
/// failing 7 of 10 golden tests by exactly 1 ULP. The guarantee is about
/// *sufficiency*, not about every parser agreeing on how to consume the extra
/// digits.
///
/// Rust's `{:?}` for f64 emits the shortest decimal that identifies the value
/// uniquely, which every correctly-rounded parser — `serde_json` here,
/// `JSON.parse` on the TypeScript side — is obliged to map back to the same
/// double. That is the property actually needed, and it is cheaper to read.
fn j(v: f64) -> String {
    if v.is_nan() {
        return "null".to_string();
    }
    assert!(v.is_finite(), "infinite value {v} has no JSON representation");
    let s = format!("{v:?}");
    let back: f64 = s.parse().expect("formatted value must parse");
    assert_eq!(back.to_bits(), v.to_bits(), "value {v} did not round-trip");
    s
}

fn main() {
    let mut out = String::new();
    out.push_str("{\n");
    out.push_str(
        "  \"_comment\": \"GENERATED by `cargo run -p thermo-core --example emit_golden`. \
Asserted by crates/thermo-core/tests/golden.rs AND \
src/__tests__/cookingThermoCrossRuntimeParity.test.ts. Both must reproduce every value EXACTLY.\",\n",
    );

    // ── Constants ───────────────────────────────────────────────────────────
    out.push_str("  \"constants\": {\n");
    let constants: Vec<(&str, f64)> = vec![
        ("STEFAN_BOLTZMANN", STEFAN_BOLTZMANN),
        ("KPA_TO_MMHG", KPA_TO_MMHG),
        ("ANTOINE_A", ANTOINE_A),
        ("ANTOINE_B", ANTOINE_B),
        ("ANTOINE_C", ANTOINE_C),
        ("ISA_EXPONENT", ISA_EXPONENT),
        ("ISA_LAPSE_RATIO", ISA_LAPSE_RATIO),
        ("ISA_P0_KPA", ISA_P0_KPA),
        ("Z_VALUE_CULINARY_C", Z_VALUE_CULINARY_C),
        ("Q10_CULINARY", Q10_CULINARY),
        ("Z_FROM_Q10", z_value_from_q10(Q10_CULINARY)),
        ("FOOD_EFFUSIVITY_LEAN_MEAT", food_effusivity_lean_meat()),
    ];
    for (i, (name, value)) in constants.iter().enumerate() {
        out.push_str(&format!(
            "    \"{}\": {}{}\n",
            name,
            j(*value),
            if i + 1 < constants.len() { "," } else { "" }
        ));
    }
    out.push_str("  },\n");

    // ── Boiling point ───────────────────────────────────────────────────────
    out.push_str("  \"boilingPoint\": [\n");
    let pressures = [101.325, 95.0, 83.4, 70.0, 50.0, 20.0, 5.0];
    for (i, p) in pressures.iter().enumerate() {
        let bp = boiling_point_c(*p).unwrap_or(f64::NAN);
        out.push_str(&format!(
            "    {{ \"pressureKpa\": {}, \"celsius\": {} }}{}\n",
            j(*p),
            j(bp),
            if i + 1 < pressures.len() { "," } else { "" }
        ));
    }
    out.push_str("  ],\n");

    // ── Elevation ───────────────────────────────────────────────────────────
    out.push_str("  \"elevation\": [\n");
    let elevations = [0.0, 500.0, 1609.0, 2240.0, 2640.0, 3000.0, 5100.0];
    for (i, e) in elevations.iter().enumerate() {
        out.push_str(&format!(
            "    {{ \"elevationM\": {}, \"pressureKpa\": {}, \"boilingC\": {}, \
\"softeningMultiplier\": {}, \"pasteurisationMultiplier\": {} }}{}\n",
            j(*e),
            j(pressure_from_elevation(*e).unwrap_or(f64::NAN)),
            j(boiling_point_at_elevation(*e).unwrap_or(f64::NAN)),
            j(altitude_time_multiplier(*e, AltitudeRegime::Softening).unwrap_or(f64::NAN)),
            j(altitude_time_multiplier(*e, AltitudeRegime::Pasteurisation).unwrap_or(f64::NAN)),
            if i + 1 < elevations.len() { "," } else { "" }
        ));
    }
    out.push_str("  ],\n");

    // ── Eigenvalue / coefficient ────────────────────────────────────────────
    out.push_str("  \"slabEigen\": [\n");
    let biots = [0.001, 0.01, 0.1, 0.5, 1.0, 2.0, 10.0, 100.0, 10000.0];
    for (i, b) in biots.iter().enumerate() {
        let lambda = slab_eigenvalue(*b).unwrap();
        out.push_str(&format!(
            "    {{ \"biot\": {}, \"lambda1\": {}, \"coefficientA1\": {} }}{}\n",
            j(*b),
            j(lambda),
            j(slab_coefficient(lambda)),
            if i + 1 < biots.len() { "," } else { "" }
        ));
    }
    out.push_str("  ],\n");

    // ── Bessel series ───────────────────────────────────────────────────────
    // Emitted separately from the eigenvalues so a drift in the SERIES is
    // distinguishable from a drift in the BISECTION that consumes it. These
    // are pure arithmetic — no transcendental — so unlike the tan family they
    // are expected to reproduce bit-exactly on every platform.
    out.push_str("  \"bessel\": [\n");
    let bessel_args = [
        0.0,
        0.5,
        1.0,
        1.5,
        2.0,
        BESSEL_J0_FIRST_ZERO,
    ];
    for (i, x) in bessel_args.iter().enumerate() {
        out.push_str(&format!(
            "    {{ \"x\": {}, \"j0\": {}, \"j1\": {} }}{}\n",
            j(*x),
            j(bessel_j0(*x)),
            j(bessel_j1(*x)),
            if i + 1 < bessel_args.len() { "," } else { "" }
        ));
    }
    out.push_str("  ],\n");

    // ── Geometry eigenvalue / coefficient ───────────────────────────────────
    // The cylinder and sphere halves of the one-term family. `slab` is emitted
    // here too, through the geometry entry point rather than `slab_eigenvalue`,
    // so that the two paths cannot silently diverge.
    out.push_str("  \"geometryEigen\": [\n");
    let geometries = [
        ("slab", FoodGeometry::Slab),
        ("cylinder", FoodGeometry::Cylinder),
        ("sphere", FoodGeometry::Sphere),
    ];
    let mut rows: Vec<String> = Vec::new();
    for (name, geom) in geometries.iter() {
        for b in biots.iter() {
            let lambda = geometry_eigenvalue(*geom, *b).unwrap();
            rows.push(format!(
                "    {{ \"geometry\": \"{}\", \"biot\": {}, \"lambda1\": {}, \"coefficientA1\": {}, \"lengthRatio\": {} }}",
                name,
                j(*b),
                j(lambda),
                j(geometry_coefficient(*geom, lambda)),
                j(geom.characteristic_length_ratio()),
            ));
        }
    }
    out.push_str(&rows.join(",\n"));
    out.push_str("\n  ],\n");

    // ── Choi & Okos component properties ────────────────────────────────────
    // Sampled across the published fit range, INCLUDING below freezing so the
    // water specific-heat branch is exercised on both sides of 32 F.
    out.push_str("  \"choiOkosComponents\": [\n");
    let comps: [(&str, FoodComponent); 7] = [
        ("water", FoodComponent::Water),
        ("protein", FoodComponent::Protein),
        ("fat", FoodComponent::Fat),
        ("carbohydrate", FoodComponent::Carbohydrate),
        ("fibre", FoodComponent::Fibre),
        ("ash", FoodComponent::Ash),
        ("ice", FoodComponent::Ice),
    ];
    let temps = [-40.0_f64, -10.0, 0.0, 5.0, 20.0, 75.0, 100.0, 148.0];
    let mut crows: Vec<String> = Vec::new();
    for (name, c) in comps.iter() {
        for t in temps.iter() {
            crows.push(format!(
                "    {{ \"component\": \"{}\", \"celsius\": {}, \"k\": {}, \"rho\": {}, \"cp\": {} }}",
                name,
                j(*t),
                j(component_conductivity(*c, *t).unwrap()),
                j(component_density(*c, *t).unwrap()),
                j(component_specific_heat(*c, *t).unwrap()),
            ));
        }
    }
    out.push_str(&crows.join(",\n"));
    out.push_str("\n  ],\n");

    // ── Choi & Okos mixtures ────────────────────────────────────────────────
    // Real compositions from src/data/ingredients, plus the ASHRAE worked
    // example, plus a food that does NOT close (vanilla extract, a third
    // ethanol) so the unaccounted fraction is pinned rather than assumed zero.
    out.push_str("  \"choiOkosMixtures\": [\n");
    let mixes: [(&str, MassFractions, f64); 6] = [
        ("ashrae_lamb_example", MassFractions { water: 0.7342, protein: 0.2029, fat: 0.0525, carbohydrate: 0.0, fibre: 0.0, ash: 0.0106 }, 5.0),
        ("carrot", MassFractions { water: 0.883, protein: 0.0093, fat: 0.0024, carbohydrate: 0.0958, fibre: 0.0, ash: 0.0097 }, 20.0),
        ("butter", MassFractions { water: 0.162, protein: 0.0085, fat: 0.8111, carbohydrate: 0.0006, fibre: 0.0, ash: 0.0009 }, 20.0),
        ("chicken_roasted", MassFractions { water: 0.653, protein: 0.3102, fat: 0.0357, carbohydrate: 0.0, fibre: 0.0, ash: 0.0106 }, 70.0),
        ("potato", MassFractions { water: 0.792, protein: 0.0205, fat: 0.0009, carbohydrate: 0.175, fibre: 0.0, ash: 0.0111 }, 100.0),
        ("vanilla_extract_open", MassFractions { water: 0.526, protein: 0.0006, fat: 0.0006, carbohydrate: 0.126, fibre: 0.0, ash: 0.0026 }, 20.0),
    ];
    let mut mrows: Vec<String> = Vec::new();
    for (name, f, t) in mixes.iter() {
        let r = food_properties(*f, *t, 0.0).unwrap();
        mrows.push(format!(
            "    {{ \"name\": \"{}\", \"celsius\": {}, \"water\": {}, \"protein\": {}, \"fat\": {}, \"carbohydrate\": {}, \"fibre\": {}, \"ash\": {}, \"density\": {}, \"specificHeat\": {}, \"conductivity\": {}, \"diffusivity\": {}, \"unaccounted\": {} }}",
            name, j(*t), j(f.water), j(f.protein), j(f.fat), j(f.carbohydrate), j(f.fibre), j(f.ash),
            j(r.density_kg_m3), j(r.specific_heat_j_kg_k), j(r.conductivity_w_m_k),
            j(r.diffusivity_m2_s), j(r.unaccounted_fraction),
        ));
    }
    out.push_str(&mrows.join(",\n"));
    out.push_str("\n  ],\n");

    // ── Latent heat ─────────────────────────────────────────────────────────
    out.push_str("  \"latentHeat\": {\n");
    out.push_str(&format!(
        "    \"waterFusionJkg\": {},\n    \"boundWaterFraction\": {},\n",
        j(water_fusion_j_kg()),
        j(BOUND_WATER_FRACTION),
    ));
    out.push_str("    \"vaporisation\": [\n");
    let vtemps = [0.0_f64, 20.0, 50.0, 72.0, 100.0];
    let vrows: Vec<String> = vtemps
        .iter()
        .map(|t| {
            format!(
                "      {{ \"celsius\": {}, \"jPerKg\": {} }}",
                j(*t),
                j(latent_heat_vaporisation(*t).unwrap())
            )
        })
        .collect();
    out.push_str(&vrows.join(",\n"));
    out.push_str("\n    ],\n");

    // Real ingredient compositions, so the food-level helpers are pinned too.
    out.push_str("    \"foods\": [\n");
    let foods: [(&str, f64, f64, f64); 4] = [
        ("chicken_roasted", 0.653, 0.0357, 70.0),
        ("carrot", 0.883, 0.0024, 100.0),
        ("butter", 0.162, 0.8111, 40.0),
        ("potato", 0.792, 0.0009, 100.0),
    ];
    let frows: Vec<String> = foods
        .iter()
        .map(|(name, water, fat, t)| {
            format!(
                "      {{ \"name\": \"{}\", \"water\": {}, \"fat\": {}, \"celsius\": {}, \"freezable\": {}, \"fusionJkg\": {}, \"vaporisationJkg\": {}, \"lossFivePercentJkg\": {} }}",
                name,
                j(*water),
                j(*fat),
                j(*t),
                j(freezable_water_fraction(*water).unwrap()),
                j(food_fusion_enthalpy(*water).unwrap()),
                j(food_vaporisation_enthalpy(*water, *t).unwrap()),
                j(evaporative_energy_loss(0.05, *t).unwrap()),
            )
        })
        .collect();
    out.push_str(&frows.join(",\n"));
    out.push_str("\n    ]\n  },\n");

    // ── Slab core time ──────────────────────────────────────────────────────
    // Every method regime the panels actually render: oven, bath, fryer,
    // boiling water, steam, and a one-sided pan sear.
    out.push_str("  \"slabCookTime\": [\n");
    struct Case(&'static str, f64, f64, f64, f64, f64, bool);
    let cases = [
        Case("roasting", 25.0, 175.0, 5.0, 60.0, 25.0, false),
        Case("sous_vide_baldwin", 25.0, 55.0, 5.0, 54.5, 95.0, false),
        Case("deep_frying", 25.0, 180.0, 5.0, 60.0, 500.0, false),
        Case("boiling", 25.0, 100.0, 5.0, 60.0, 3000.0, false),
        Case("steaming", 25.0, 100.0, 5.0, 60.0, 9000.0, false),
        Case("pan_sear_one_sided", 12.0, 220.0, 5.0, 60.0, 500.0, true),
        Case("thin_cutlet", 8.0, 190.0, 5.0, 70.0, 250.0, false),
        Case("thick_roast", 80.0, 160.0, 5.0, 60.0, 20.0, false),
    ];
    for (i, c) in cases.iter().enumerate() {
        let input = SlabCookInput {
            thickness_mm: c.1,
            medium_c: c.2,
            initial_c: c.3,
            target_c: c.4,
            h_w_m2_k: c.5,
            k_w_m_k: LEAN_MEAT_K_W_M_K,
            alpha_m2_s: LEAN_MEAT_ALPHA_M2_S,
            one_sided: c.6,
        };
        let r = slab_core_time(input).expect("golden cases must be reachable");
        out.push_str(&format!(
            "    {{ \"name\": \"{}\", \"thicknessMm\": {}, \"mediumC\": {}, \"initialC\": {}, \
\"targetC\": {}, \"hWm2K\": {}, \"oneSided\": {}, \"minutes\": {}, \"biot\": {}, \
\"fourier\": {}, \"lambda1\": {}, \"coefficientA1\": {}, \"oneTermValid\": {} }}{}\n",
            c.0,
            j(c.1),
            j(c.2),
            j(c.3),
            j(c.4),
            j(c.5),
            c.6,
            j(r.minutes),
            j(r.biot),
            j(r.fourier),
            j(r.lambda1),
            j(r.coefficient_a1),
            r.one_term_valid,
            if i + 1 < cases.len() { "," } else { "" }
        ));
    }
    out.push_str("  ],\n");

    // ── Radiation ───────────────────────────────────────────────────────────
    out.push_str("  \"radiation\": [\n");
    let rad = [
        (505.0, 298.0, 0.85, 1.0),
        (1200.0, 298.0, 0.85, 1.0),
        (811.0, 373.0, 0.9, 0.5),
        (700.0, 420.0, 0.75, 1.0),
    ];
    for (i, (s, sf, e, v)) in rad.iter().enumerate() {
        out.push_str(&format!(
            "    {{ \"sourceK\": {}, \"surfaceK\": {}, \"emissivity\": {}, \"viewFactor\": {}, \
\"fluxKwM2\": {}, \"radiativeH\": {} }}{}\n",
            j(*s),
            j(*sf),
            j(*e),
            j(*v),
            j(radiant_flux_kw_m2(*s, *sf, *e, *v)),
            j(radiative_h(*s, *sf, *e)),
            if i + 1 < rad.len() { "," } else { "" }
        ));
    }
    out.push_str("  ],\n");

    // ── Contact temperature ─────────────────────────────────────────────────
    out.push_str("  \"contact\": [\n");
    let mats: [(&str, f64, f64, f64); 5] = [
        ("cast_iron", 52.0, 7200.0, 460.0),
        ("carbon_steel", 51.0, 7850.0, 486.0),
        ("stainless_304", 16.2, 8000.0, 500.0),
        ("aluminium", 237.0, 2700.0, 900.0),
        ("copper", 401.0, 8960.0, 385.0),
    ];
    let food_e = food_effusivity_lean_meat();
    for (i, (name, k, rho, c)) in mats.iter().enumerate() {
        let e = effusivity(*k, *rho, *c);
        out.push_str(&format!(
            "    {{ \"material\": \"{}\", \"kWmK\": {}, \"rhoKgM3\": {}, \"cJkgK\": {}, \
\"effusivity\": {}, \"contactC\": {} }}{}\n",
            name,
            j(*k),
            j(*rho),
            j(*c),
            j(e),
            j(contact_temperature_c(230.0, 5.0, e, food_e)),
            if i + 1 < mats.len() { "," } else { "" }
        ));
    }
    out.push_str("  ],\n");

    // ── Wet bulb ────────────────────────────────────────────────────────────
    out.push_str("  \"wetBulb\": [\n");
    let wb = [
        (20.0, 50.0),
        (25.0, 80.0),
        (35.0, 20.0),
        (5.0, 95.0),
        (-10.0, 60.0),
        (50.0, 99.0),
    ];
    for (i, (t, rh)) in wb.iter().enumerate() {
        let v = wet_bulb_c(*t, *rh);
        out.push_str(&format!(
            "    {{ \"dryBulbC\": {}, \"relativeHumidityPct\": {}, \"wetBulbC\": {} }}{}\n",
            j(*t),
            j(*rh),
            match v {
                Some(x) => j(x),
                None => "null".to_string(),
            },
            if i + 1 < wb.len() { "," } else { "" }
        ));
    }
    out.push_str("  ],\n");

    // ── External anchors ────────────────────────────────────────────────────
    // Values from OUTSIDE this repository. Regenerating the file cannot move
    // these, because both test suites assert the computed result lands inside
    // the published band rather than reading it back from here.
    out.push_str("  \"externalAnchors\": {\n");
    out.push_str("    \"denverBoilingF\": { \"published\": 202.0, \"toleranceF\": 1.0, \"elevationM\": 1609.0, \"source\": \"widely published Denver boiling point\" },\n");
    out.push_str("    \"seaLevelBoilingC\": { \"published\": 100.0, \"toleranceC\": 0.005, \"source\": \"definition of the Celsius scale at 101.325 kPa\" },\n");
    out.push_str("    \"baldwinSousVideMin\": { \"low\": 55.0, \"high\": 85.0, \"case\": \"sous_vide_baldwin\", \"source\": \"Baldwin, A Practical Guide to Sous Vide Cooking — 25 mm slab tables give 60-70 min\" },\n");
    out.push_str("    \"isaExponent\": { \"published\": 5.25588, \"tolerance\": 5e-6, \"source\": \"US Standard Atmosphere 1976\" },\n");
    out.push_str("    \"stefanBoltzmann\": { \"published\": 5.670374419e-8, \"tolerance\": 0.0, \"source\": \"CODATA 2018, exact by SI definition\" }\n");
    out.push_str("  },\n");

    // ── Simulation trace ────────────────────────────────────────────────────
    // Pins the render-loop model itself, so the TypeScript fallback cannot
    // quietly become a different simulation from the WASM engine it replaces.
    out.push_str("  \"simulation\": {\n");
    out.push_str(&format!(
        "    \"buoyancyPerK\": {}, \"swirlAmplitude\": {}, \"drag\": {}, \"floatsPerParticle\": {},\n",
        j(BUOYANCY_PER_K as f64),
        j(SWIRL_AMPLITUDE as f64),
        j(CONVECTION_DRAG as f64),
        FLOATS_PER_PARTICLE
    ));
    out.push_str("    \"trace\": [\n");
    let mut ps = seeded_particles(8);
    let mut rows: Vec<String> = Vec::new();
    for step in 1..=60 {
        step_oven_simulation(&mut ps, 1.0 / 60.0, 175.0, 25.0, 505.0);
        if step % 20 == 0 {
            let p = ps[3];
            rows.push(format!(
                "      {{ \"step\": {}, \"particle\": 3, \"x\": {}, \"y\": {}, \"z\": {}, \
\"vx\": {}, \"vy\": {}, \"vz\": {}, \"tempC\": {}, \"radiantIntensity\": {} }}",
                step,
                j(p.x as f64),
                j(p.y as f64),
                j(p.z as f64),
                j(p.vx as f64),
                j(p.vy as f64),
                j(p.vz as f64),
                j(p.temp_c as f64),
                j(p.radiant_intensity as f64)
            ));
        }
    }
    out.push_str(&rows.join(",\n"));
    out.push_str("\n    ],\n");

    // ── Per-regime traces ───────────────────────────────────────────────────
    //
    // The block above pins ONE motion model. It cannot detect a regime that
    // exists on one runtime and not the other, or two regimes that have
    // silently collapsed into each other — which is the failure this whole
    // layer was built to remove, so it gets its own vectors.
    //
    // Each case is driven with the REAL numbers of a method that cooks in that
    // regime, named in `method`, so a diff here reads as "distilling changed"
    // rather than "case 9 changed".
    out.push_str("    \"regimes\": [\n");
    let cases: [(HeatRegime, &str, &str, f32, f32, f32); 10] = [
        (HeatRegime::BuoyantAir, "BuoyantAir", "roasting", 190.0, 25.0, 505.0),
        (HeatRegime::Oil, "Oil", "frying", 177.0, 500.0, 505.0),
        (HeatRegime::RollingBoil, "RollingBoil", "boiling", 100.0, 3000.0, 505.0),
        (HeatRegime::CondensingSteam, "CondensingSteam", "steaming", 100.0, 9000.0, 505.0),
        (HeatRegime::StillLiquid, "StillLiquid", "sous_vide", 60.0, 95.0, 505.0),
        (HeatRegime::Radiant, "Radiant", "grilling", 260.0, 60.0, 1200.0),
        (HeatRegime::SolidContact, "SolidContact", "tilt_skillet", 218.0, 700.0, 505.0),
        (HeatRegime::Cryogenic, "Cryogenic", "cryo_cooking", -196.0, 250.0, 505.0),
        (HeatRegime::Diffusion, "Diffusion", "pickling", 20.0, 25.0, 505.0),
        (HeatRegime::Distillation, "Distillation", "distilling", 78.0, 3000.0, 505.0),
    ];
    let mut regime_rows: Vec<String> = Vec::new();
    for (regime, name, method, medium_c, h, radiant_k) in cases {
        let params = regime_params(regime);
        let mut ps = seeded_particles(8);
        let mut samples: Vec<String> = Vec::new();
        for step in 1..=60 {
            step_medium_simulation(&mut ps, 1.0 / 60.0, regime, medium_c, h, radiant_k);
            if step % 30 == 0 {
                let p = ps[3];
                samples.push(format!(
                    "        {{ \"step\": {}, \"particle\": 3, \"x\": {}, \"y\": {}, \"z\": {}, \
\"vx\": {}, \"vy\": {}, \"vz\": {}, \"tempC\": {}, \"phaseFrac\": {} }}",
                    step,
                    j(p.x as f64),
                    j(p.y as f64),
                    j(p.z as f64),
                    j(p.vx as f64),
                    j(p.vy as f64),
                    j(p.vz as f64),
                    j(p.temp_c as f64),
                    j(p.phase_frac as f64)
                ));
            }
        }
        regime_rows.push(format!(
            "      {{ \"regime\": {}, \"name\": \"{}\", \"method\": \"{}\", \
\"mediumC\": {}, \"hWm2K\": {}, \"radiantSourceK\": {},\n        \
\"params\": {{ \"buoyancyPerK\": {}, \"swirl\": {}, \"drag\": {}, \
\"nucleationPerS\": {}, \"nucleationDir\": {}, \"coolingSign\": {} }},\n        \
\"trace\": [\n{}\n        ] }}",
            regime as u8,
            name,
            method,
            j(medium_c as f64),
            j(h as f64),
            j(radiant_k as f64),
            j(params.buoyancy_per_k as f64),
            j(params.swirl as f64),
            j(params.drag as f64),
            j(params.nucleation_per_s as f64),
            j(params.nucleation_dir as f64),
            j(params.cooling_sign as f64),
            samples.join(",\n")
        ));
    }
    out.push_str(&regime_rows.join(",\n"));
    out.push_str("\n    ]\n  },\n");

    // ── Boundary network ───────────────────────────────────────────────────
    out.push_str("  \"boundaryNetwork\": {\n");

    out.push_str("    \"air\": [\n");
    let air_rows: Vec<String> = [-20.0_f64, 0.0, 20.0, 60.0, 100.0, 180.0, 250.0, 400.0, 500.0]
        .iter()
        .map(|c| {
            let a = air_properties(*c).unwrap();
            format!(
                "      {{ \"celsius\": {}, \"rho\": {}, \"cp\": {}, \"mu\": {}, \"k\": {}, \
\"nu\": {}, \"alpha\": {}, \"prandtl\": {}, \"beta\": {} }}",
                j(*c), j(a.rho_kg_m3), j(a.cp_j_kg_k), j(a.mu_pa_s), j(a.k_w_m_k),
                j(a.nu_m2_s), j(a.alpha_m2_s), j(a.prandtl), j(a.beta_per_k)
            )
        })
        .collect();
    out.push_str(&air_rows.join(",\n"));
    out.push_str("\n    ],\n");

    out.push_str("    \"water\": [\n");
    let water_rows: Vec<String> = [10.0_f64, 25.0, 50.0, 75.0, 95.0, 100.0]
        .iter()
        .map(|c| {
            let w = saturated_water_properties(*c).unwrap();
            format!(
                "      {{ \"celsius\": {}, \"rho\": {}, \"cp\": {}, \"mu\": {}, \"k\": {}, \
\"nu\": {}, \"alpha\": {}, \"prandtl\": {}, \"beta\": {}, \"sigma\": {}, \"hfg\": {}, \
\"rhoVapour\": {} }}",
                j(*c), j(w.fluid.rho_kg_m3), j(w.fluid.cp_j_kg_k), j(w.fluid.mu_pa_s),
                j(w.fluid.k_w_m_k), j(w.fluid.nu_m2_s), j(w.fluid.alpha_m2_s),
                j(w.fluid.prandtl), j(w.fluid.beta_per_k), j(w.sigma_n_m), j(w.hfg_j_kg),
                j(w.rho_vapour_kg_m3)
            )
        })
        .collect();
    out.push_str(&water_rows.join(",\n"));
    out.push_str("\n    ],\n");

    out.push_str("    \"vapour\": [\n");
    let vap_rows: Vec<String> = [
        1.0_f64, 5.0, 10.0, 15.0, 20.0, 25.0, 30.0, 37.0, 45.0, 55.0, 60.0, 70.0, 80.0, 90.0, 95.0,
        99.0, 100.0,
    ]
        .iter()
        .map(|c| {
            let p = saturation_pressure_kpa(*c).unwrap();
            format!(
                "      {{ \"celsius\": {}, \"satKpa\": {}, \"rhoSat\": {}, \"absHumid50\": {}, \
\"heatedTo200\": {} }}",
                j(*c), j(p), j(vapour_density_kg_m3(p, *c)),
                j(absolute_humidity_kg_m3(*c, 50.0).unwrap()),
                j(humid_air_vapour_density(*c, 50.0, 200.0).unwrap())
            )
        })
        .collect();
    out.push_str(&vap_rows.join(",\n"));
    out.push_str("\n    ],\n");

    out.push_str("    \"convection\": [\n");
    let film = air_properties(60.0).unwrap();
    let surfaces = [
        (ConvectiveSurface::Vertical, "vertical", 0.15_f64),
        (ConvectiveSurface::HorizontalUp, "horizontal-up", 0.05),
        (ConvectiveSurface::HorizontalDown, "horizontal-down", 0.05),
        (ConvectiveSurface::HorizontalCylinder, "horizontal-cylinder", 0.08),
    ];
    let conv_rows: Vec<String> = surfaces
        .iter()
        .map(|(s, name, l)| {
            let r = natural_convection_h(&film, *s, 80.0, *l).unwrap();
            format!(
                "      {{ \"surface\": \"{}\", \"lengthM\": {}, \"rayleigh\": {}, \
\"nusselt\": {}, \"h\": {} }}",
                name, j(*l), j(r.dimensionless), j(r.nusselt), j(r.h_w_m2_k)
            )
        })
        .collect();
    out.push_str(&conv_rows.join(",\n"));
    out.push_str("\n    ],\n");

    let forced = forced_convection_h_flat_plate(&film, 3.0, 0.3).unwrap();
    let forced_turb = forced_convection_h_flat_plate(&film, 40.0, 0.3).unwrap();
    out.push_str(&format!(
        "    \"forced\": {{ \"laminarRe\": {}, \"laminarNu\": {}, \"laminarH\": {}, \
\"turbulentRe\": {}, \"turbulentNu\": {}, \"turbulentH\": {} }},\n",
        j(forced.dimensionless), j(forced.nusselt), j(forced.h_w_m2_k),
        j(forced_turb.dimensionless), j(forced_turb.nusselt), j(forced_turb.h_w_m2_k)
    ));

    let w100 = saturated_water_properties(100.0).unwrap();
    out.push_str(&format!(
        "    \"criticalHeatFlux\": {},\n",
        j(critical_heat_flux_wm2(&w100))
    ));
    out.push_str("    \"boiling\": [\n");
    let boil_cases = [
        (3.0_f64, BoilingSurface::StainlessEtched, "stainless-etched"),
        (10.0, BoilingSurface::StainlessEtched, "stainless-etched"),
        (20.0, BoilingSurface::StainlessEtched, "stainless-etched"),
        (5.0, BoilingSurface::StainlessPolished, "stainless-polished"),
        (5.0, BoilingSurface::StainlessScored, "stainless-scored"),
        (8.0, BoilingSurface::CopperPolished, "copper-polished"),
    ];
    let boil_rows: Vec<String> = boil_cases
        .iter()
        .map(|(dt, s, name)| {
            let b = nucleate_boiling_flux(&w100, *dt, *s).unwrap();
            format!(
                "      {{ \"excessK\": {}, \"surface\": \"{}\", \"flux\": {}, \"h\": {}, \
\"burnout\": {} }}",
                j(*dt), name, j(b.flux_w_m2), j(b.h_w_m2_k), j(b.burnout_fraction)
            )
        })
        .collect();
    out.push_str(&boil_rows.join(",\n"));
    out.push_str("\n    ],\n");

    out.push_str("    \"evaporation\": [\n");
    let kitchen = absolute_humidity_kg_m3(20.0, 50.0).unwrap();
    let evap_cases = [
        (8.531_f64, 100.0_f64, 20.0_f64, kitchen, "open pot"),
        (15.0, 60.0, 200.0, humid_air_vapour_density(20.0, 50.0, 200.0).unwrap(), "oven surface"),
        (10.0, 5.0, 25.0, absolute_humidity_kg_m3(25.0, 80.0).unwrap(), "cold plate"),
    ];
    let evap_rows: Vec<String> = evap_cases
        .iter()
        .map(|(h, ts, ta, bulk, name)| {
            let w = saturated_water_properties(ts.clamp(WATER_MIN_C, WATER_MAX_C)).unwrap();
            let e = evaporative_flux(*h, *ts, *ta, *bulk, w.hfg_j_kg).unwrap();
            format!(
                "      {{ \"case\": \"{}\", \"h\": {}, \"surfaceC\": {}, \"airC\": {}, \
\"bulkVapour\": {}, \"lewis\": {}, \"hMass\": {}, \"massFlux\": {}, \"latentFlux\": {} }}",
                name, j(*h), j(*ts), j(*ta), j(*bulk), j(e.lewis), j(e.h_mass_m_s),
                j(e.mass_flux_kg_m2_s), j(e.latent_flux_w_m2)
            )
        })
        .collect();
    out.push_str(&evap_rows.join(",\n"));
    out.push_str("\n    ],\n");

    out.push_str("    \"pinnedSurface\": [\n");
    let oven_vapour = humid_air_vapour_density(20.0, 50.0, 200.0).unwrap();
    let pin_cases = [
        (200.0_f64, oven_vapour, 15.0_f64, 200.0_f64, 100.0_f64, "still oven"),
        (200.0, oven_vapour, 40.0, 200.0, 100.0, "convection oven"),
        (200.0, oven_vapour, 15.0, 600.0, 100.0, "broiler"),
        (200.0, oven_vapour, 15.0, 600.0, 94.7, "broiler at altitude"),
    ];
    let pin_rows: Vec<String> = pin_cases
        .iter()
        .map(|(air, vap, h, rad, ceiling, name)| {
            let r = evaporative_pinned_surface_c(*air, *vap, *h, *rad, 0.9, *ceiling).unwrap();
            format!(
                "      {{ \"case\": \"{}\", \"airC\": {}, \"bulkVapour\": {}, \"h\": {}, \
\"radiantC\": {}, \"ceilingC\": {}, \"celsius\": {}, \"convGain\": {}, \"radGain\": {}, \
\"evapLoss\": {}, \"massFlux\": {}, \"saturated\": {} }}",
                name, j(*air), j(*vap), j(*h), j(*rad), j(*ceiling), j(r.celsius),
                j(r.convective_gain_w_m2), j(r.radiative_gain_w_m2), j(r.evaporative_loss_w_m2),
                j(r.mass_flux_kg_m2_s), r.saturated
            )
        })
        .collect();
    out.push_str(&pin_rows.join(",\n"));
    out.push_str("\n    ],\n");

    out.push_str("    \"network\": [\n");
    let potato = FoodLeg {
        medium_to_food_h_w_m2_k: 15.0,
        geometry: FoodGeometry::Sphere,
        half_dimension_m: 0.025,
        k_w_m_k: 0.55,
        area_m2: 4.0 * core::f64::consts::PI * 0.025 * 0.025,
    };
    let pot_leg = VesselLeg {
        source_to_vessel_h_w_m2_k: 60.0,
        area_m2: 0.05,
        k_w_m_k: 15.0,
        thickness_m: 0.003,
        vessel_to_medium_h_w_m2_k: 5000.0,
    };
    let net_cases: [(&str, f64, f64, Option<VesselLeg>, Option<FoodLeg>); 3] = [
        ("oven-rack", 200.0, 20.0, None, Some(potato)),
        (
            "boiling-pot",
            250.0,
            20.0,
            Some(pot_leg),
            Some(FoodLeg { medium_to_food_h_w_m2_k: 1500.0, ..potato }),
        ),
        ("empty-pot", 250.0, 100.0, Some(pot_leg), None),
    ];
    let net_rows: Vec<String> = net_cases
        .iter()
        .map(|(name, src, sink, v, f)| {
            let n = solve_boundary_network(*src, *sink, *v, *f).unwrap();
            let links: Vec<String> = n
                .links
                .iter()
                .map(|l| {
                    format!(
                        "          {{ \"id\": \"{}\", \"r\": {}, \"share\": {}, \"dropK\": {} }}",
                        l.id, j(l.resistance_k_per_w), j(l.share), j(l.drop_k)
                    )
                })
                .collect();
            format!(
                "      {{ \"case\": \"{}\", \"totalR\": {}, \"ua\": {}, \"heatFlowW\": {}, \
\"controlling\": \"{}\", \"foodBiot\": {},\n        \"links\": [\n{}\n        ] }}",
                name, j(n.total_resistance_k_per_w), j(n.ua_w_per_k), j(n.heat_flow_w),
                n.links[n.controlling].id,
                match n.food_biot { Some(b) => j(b), None => "null".to_string() },
                links.join(",\n")
            )
        })
        .collect();
    out.push_str(&net_rows.join(",\n"));
    out.push_str("\n    ]\n  }\n}\n");

    print!("{out}");
}
