//! Emit the cross-runtime golden vectors as JSON.
//!
//! Run: `cargo run -p thermo-core --example emit_golden > \
//!       crates/thermo-core/tests/thermo_golden_vectors.json`
//!
//! ## What this file is, and what it is NOT
//!
//! It is a convenience for REGENERATING the fixture after a deliberate change
//! to the physics, so the expected values are not hand-transcribed (which is
//! how transcription drift gets in — see `food_effusivity_lean_meat`).
//!
//! It is NOT the authority on whether those values are correct. A fixture
//! generated from Rust and then asserted by Rust proves nothing; that test
//! would pass just as happily against a defect. The fixture earns its keep in
//! two other places:
//!
//!   1. `src/__tests__/cookingThermoCrossRuntimeParity.test.ts` asserts the
//!      TypeScript implementation reproduces it EXACTLY. That is the drift
//!      detector, and it is the reason this file exists.
//!   2. The `externalAnchors` block is checked against published figures that
//!      come from outside this repository entirely — Denver's boiling point,
//!      Baldwin's sous-vide tables, the ISA published exponent. Regenerating
//!      cannot launder a wrong number past those.
//!
//! So: regenerate freely, but read the diff. A vector that moves without a
//! corresponding change to a named constant is the bug announcing itself.

use thermo_core::*;

/// Print an f64 in the SHORTEST form that round-trips back to the same bits.
///
/// `[MEASURED 2026-08-16]` The first version of this used `{v:.17e}` on the
/// reasoning that 17 significant digits is the IEEE-754 round-trip guarantee.
/// It round-tripped through Rust's own `str::parse` — which is what the
/// assertion below checked — and then lost the last bit in `serde_json`,
/// failing 7 of 10 golden tests by exactly 1 ULP. The guarantee is about
/// *sufficiency*, not about every parser agreeing on how to consume the extra
/// digits.
///
/// Rust's `{:?}` for f64 emits the shortest decimal that identifies the value
/// uniquely, which every correctly-rounded parser — `serde_json` here,
/// `JSON.parse` on the TypeScript side — is obliged to map back to the same
/// double. That is the property actually needed, and it is cheaper to read.
fn j(v: f64) -> String {
    if v.is_nan() {
        return "null".to_string();
    }
    assert!(v.is_finite(), "infinite value {v} has no JSON representation");
    let s = format!("{v:?}");
    let back: f64 = s.parse().expect("formatted value must parse");
    assert_eq!(back.to_bits(), v.to_bits(), "value {v} did not round-trip");
    s
}

fn main() {
    let mut out = String::new();
    out.push_str("{\n");
    out.push_str(
        "  \"_comment\": \"GENERATED by `cargo run -p thermo-core --example emit_golden`. \
Asserted by crates/thermo-core/tests/golden.rs AND \
src/__tests__/cookingThermoCrossRuntimeParity.test.ts. Both must reproduce every value EXACTLY.\",\n",
    );

    // ── Constants ───────────────────────────────────────────────────────────
    out.push_str("  \"constants\": {\n");
    let constants: Vec<(&str, f64)> = vec![
        ("STEFAN_BOLTZMANN", STEFAN_BOLTZMANN),
        ("KPA_TO_MMHG", KPA_TO_MMHG),
        ("ANTOINE_A", ANTOINE_A),
        ("ANTOINE_B", ANTOINE_B),
        ("ANTOINE_C", ANTOINE_C),
        ("ISA_EXPONENT", ISA_EXPONENT),
        ("ISA_LAPSE_RATIO", ISA_LAPSE_RATIO),
        ("ISA_P0_KPA", ISA_P0_KPA),
        ("Z_VALUE_CULINARY_C", Z_VALUE_CULINARY_C),
        ("Q10_CULINARY", Q10_CULINARY),
        ("Z_FROM_Q10", z_value_from_q10(Q10_CULINARY)),
        ("FOOD_EFFUSIVITY_LEAN_MEAT", food_effusivity_lean_meat()),
    ];
    for (i, (name, value)) in constants.iter().enumerate() {
        out.push_str(&format!(
            "    \"{}\": {}{}\n",
            name,
            j(*value),
            if i + 1 < constants.len() { "," } else { "" }
        ));
    }
    out.push_str("  },\n");

    // ── Boiling point ───────────────────────────────────────────────────────
    out.push_str("  \"boilingPoint\": [\n");
    let pressures = [101.325, 95.0, 83.4, 70.0, 50.0, 20.0, 5.0];
    for (i, p) in pressures.iter().enumerate() {
        let bp = boiling_point_c(*p).unwrap_or(f64::NAN);
        out.push_str(&format!(
            "    {{ \"pressureKpa\": {}, \"celsius\": {} }}{}\n",
            j(*p),
            j(bp),
            if i + 1 < pressures.len() { "," } else { "" }
        ));
    }
    out.push_str("  ],\n");

    // ── Elevation ───────────────────────────────────────────────────────────
    out.push_str("  \"elevation\": [\n");
    let elevations = [0.0, 500.0, 1609.0, 2240.0, 2640.0, 3000.0, 5100.0];
    for (i, e) in elevations.iter().enumerate() {
        out.push_str(&format!(
            "    {{ \"elevationM\": {}, \"pressureKpa\": {}, \"boilingC\": {}, \
\"softeningMultiplier\": {}, \"pasteurisationMultiplier\": {} }}{}\n",
            j(*e),
            j(pressure_from_elevation(*e).unwrap_or(f64::NAN)),
            j(boiling_point_at_elevation(*e).unwrap_or(f64::NAN)),
            j(altitude_time_multiplier(*e, AltitudeRegime::Softening).unwrap_or(f64::NAN)),
            j(altitude_time_multiplier(*e, AltitudeRegime::Pasteurisation).unwrap_or(f64::NAN)),
            if i + 1 < elevations.len() { "," } else { "" }
        ));
    }
    out.push_str("  ],\n");

    // ── Eigenvalue / coefficient ────────────────────────────────────────────
    out.push_str("  \"slabEigen\": [\n");
    let biots = [0.001, 0.01, 0.1, 0.5, 1.0, 2.0, 10.0, 100.0, 10000.0];
    for (i, b) in biots.iter().enumerate() {
        let lambda = slab_eigenvalue(*b).unwrap();
        out.push_str(&format!(
            "    {{ \"biot\": {}, \"lambda1\": {}, \"coefficientA1\": {} }}{}\n",
            j(*b),
            j(lambda),
            j(slab_coefficient(lambda)),
            if i + 1 < biots.len() { "," } else { "" }
        ));
    }
    out.push_str("  ],\n");

    // ── Slab core time ──────────────────────────────────────────────────────
    // Every method regime the panels actually render: oven, bath, fryer,
    // boiling water, steam, and a one-sided pan sear.
    out.push_str("  \"slabCookTime\": [\n");
    struct Case(&'static str, f64, f64, f64, f64, f64, bool);
    let cases = [
        Case("roasting", 25.0, 175.0, 5.0, 60.0, 25.0, false),
        Case("sous_vide_baldwin", 25.0, 55.0, 5.0, 54.5, 95.0, false),
        Case("deep_frying", 25.0, 180.0, 5.0, 60.0, 500.0, false),
        Case("boiling", 25.0, 100.0, 5.0, 60.0, 3000.0, false),
        Case("steaming", 25.0, 100.0, 5.0, 60.0, 9000.0, false),
        Case("pan_sear_one_sided", 12.0, 220.0, 5.0, 60.0, 500.0, true),
        Case("thin_cutlet", 8.0, 190.0, 5.0, 70.0, 250.0, false),
        Case("thick_roast", 80.0, 160.0, 5.0, 60.0, 20.0, false),
    ];
    for (i, c) in cases.iter().enumerate() {
        let input = SlabCookInput {
            thickness_mm: c.1,
            medium_c: c.2,
            initial_c: c.3,
            target_c: c.4,
            h_w_m2_k: c.5,
            k_w_m_k: LEAN_MEAT_K_W_M_K,
            alpha_m2_s: LEAN_MEAT_ALPHA_M2_S,
            one_sided: c.6,
        };
        let r = slab_core_time(input).expect("golden cases must be reachable");
        out.push_str(&format!(
            "    {{ \"name\": \"{}\", \"thicknessMm\": {}, \"mediumC\": {}, \"initialC\": {}, \
\"targetC\": {}, \"hWm2K\": {}, \"oneSided\": {}, \"minutes\": {}, \"biot\": {}, \
\"fourier\": {}, \"lambda1\": {}, \"coefficientA1\": {}, \"oneTermValid\": {} }}{}\n",
            c.0,
            j(c.1),
            j(c.2),
            j(c.3),
            j(c.4),
            j(c.5),
            c.6,
            j(r.minutes),
            j(r.biot),
            j(r.fourier),
            j(r.lambda1),
            j(r.coefficient_a1),
            r.one_term_valid,
            if i + 1 < cases.len() { "," } else { "" }
        ));
    }
    out.push_str("  ],\n");

    // ── Radiation ───────────────────────────────────────────────────────────
    out.push_str("  \"radiation\": [\n");
    let rad = [
        (505.0, 298.0, 0.85, 1.0),
        (1200.0, 298.0, 0.85, 1.0),
        (811.0, 373.0, 0.9, 0.5),
        (700.0, 420.0, 0.75, 1.0),
    ];
    for (i, (s, sf, e, v)) in rad.iter().enumerate() {
        out.push_str(&format!(
            "    {{ \"sourceK\": {}, \"surfaceK\": {}, \"emissivity\": {}, \"viewFactor\": {}, \
\"fluxKwM2\": {}, \"radiativeH\": {} }}{}\n",
            j(*s),
            j(*sf),
            j(*e),
            j(*v),
            j(radiant_flux_kw_m2(*s, *sf, *e, *v)),
            j(radiative_h(*s, *sf, *e)),
            if i + 1 < rad.len() { "," } else { "" }
        ));
    }
    out.push_str("  ],\n");

    // ── Contact temperature ─────────────────────────────────────────────────
    out.push_str("  \"contact\": [\n");
    let mats: [(&str, f64, f64, f64); 5] = [
        ("cast_iron", 52.0, 7200.0, 460.0),
        ("carbon_steel", 51.0, 7850.0, 486.0),
        ("stainless_304", 16.2, 8000.0, 500.0),
        ("aluminium", 237.0, 2700.0, 900.0),
        ("copper", 401.0, 8960.0, 385.0),
    ];
    let food_e = food_effusivity_lean_meat();
    for (i, (name, k, rho, c)) in mats.iter().enumerate() {
        let e = effusivity(*k, *rho, *c);
        out.push_str(&format!(
            "    {{ \"material\": \"{}\", \"kWmK\": {}, \"rhoKgM3\": {}, \"cJkgK\": {}, \
\"effusivity\": {}, \"contactC\": {} }}{}\n",
            name,
            j(*k),
            j(*rho),
            j(*c),
            j(e),
            j(contact_temperature_c(230.0, 5.0, e, food_e)),
            if i + 1 < mats.len() { "," } else { "" }
        ));
    }
    out.push_str("  ],\n");

    // ── Wet bulb ────────────────────────────────────────────────────────────
    out.push_str("  \"wetBulb\": [\n");
    let wb = [
        (20.0, 50.0),
        (25.0, 80.0),
        (35.0, 20.0),
        (5.0, 95.0),
        (-10.0, 60.0),
        (50.0, 99.0),
    ];
    for (i, (t, rh)) in wb.iter().enumerate() {
        let v = wet_bulb_c(*t, *rh);
        out.push_str(&format!(
            "    {{ \"dryBulbC\": {}, \"relativeHumidityPct\": {}, \"wetBulbC\": {} }}{}\n",
            j(*t),
            j(*rh),
            match v {
                Some(x) => j(x),
                None => "null".to_string(),
            },
            if i + 1 < wb.len() { "," } else { "" }
        ));
    }
    out.push_str("  ],\n");

    // ── External anchors ────────────────────────────────────────────────────
    // Values from OUTSIDE this repository. Regenerating the file cannot move
    // these, because both test suites assert the computed result lands inside
    // the published band rather than reading it back from here.
    out.push_str("  \"externalAnchors\": {\n");
    out.push_str("    \"denverBoilingF\": { \"published\": 202.0, \"toleranceF\": 1.0, \"elevationM\": 1609.0, \"source\": \"widely published Denver boiling point\" },\n");
    out.push_str("    \"seaLevelBoilingC\": { \"published\": 100.0, \"toleranceC\": 0.005, \"source\": \"definition of the Celsius scale at 101.325 kPa\" },\n");
    out.push_str("    \"baldwinSousVideMin\": { \"low\": 55.0, \"high\": 85.0, \"case\": \"sous_vide_baldwin\", \"source\": \"Baldwin, A Practical Guide to Sous Vide Cooking — 25 mm slab tables give 60-70 min\" },\n");
    out.push_str("    \"isaExponent\": { \"published\": 5.25588, \"tolerance\": 5e-6, \"source\": \"US Standard Atmosphere 1976\" },\n");
    out.push_str("    \"stefanBoltzmann\": { \"published\": 5.670374419e-8, \"tolerance\": 0.0, \"source\": \"CODATA 2018, exact by SI definition\" }\n");
    out.push_str("  },\n");

    // ── Simulation trace ────────────────────────────────────────────────────
    // Pins the render-loop model itself, so the TypeScript fallback cannot
    // quietly become a different simulation from the WASM engine it replaces.
    out.push_str("  \"simulation\": {\n");
    out.push_str(&format!(
        "    \"buoyancyPerK\": {}, \"swirlAmplitude\": {}, \"drag\": {}, \"floatsPerParticle\": {},\n",
        j(BUOYANCY_PER_K as f64),
        j(SWIRL_AMPLITUDE as f64),
        j(CONVECTION_DRAG as f64),
        FLOATS_PER_PARTICLE
    ));
    out.push_str("    \"trace\": [\n");
    let mut ps = seeded_particles(8);
    let mut rows: Vec<String> = Vec::new();
    for step in 1..=60 {
        step_oven_simulation(&mut ps, 1.0 / 60.0, 175.0, 25.0, 505.0);
        if step % 20 == 0 {
            let p = ps[3];
            rows.push(format!(
                "      {{ \"step\": {}, \"particle\": 3, \"x\": {}, \"y\": {}, \"z\": {}, \
\"vx\": {}, \"vy\": {}, \"vz\": {}, \"tempC\": {}, \"radiantIntensity\": {} }}",
                step,
                j(p.x as f64),
                j(p.y as f64),
                j(p.z as f64),
                j(p.vx as f64),
                j(p.vy as f64),
                j(p.vz as f64),
                j(p.temp_c as f64),
                j(p.radiant_intensity as f64)
            ));
        }
    }
    out.push_str(&rows.join(",\n"));
    out.push_str("\n    ]\n  }\n}\n");

    print!("{out}");
}
